### ISSUE TITLE
On the Consumer Tool Homepage, "60% of college graduates started college at age 24 or older" should actually be 30% and age 25

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1010]
In the Fun Facts. A little too much fun!
Can you please change to 30% and age 25 or older?

**Comment by meiqimichelle** [comment]
Grabbed this one in passing. Fix should be live on `dev`.

![screen shot 2015-09-03 at 11 17 26 pm](https://cloud.githubusercontent.com/assets/4827522/9677708/2164d920-5292-11e5-9b3c-883da43cb117.png)

**Comment by ErieMeyer** [comment]
Lgtm
