### ISSUE TITLE
On the Consumer Tool Homepage, change "of free money" to "for free"

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1011]
In the Fun Fact:
"You could be eligible for up to $5,775 of free money in federal grants to help pay for college. No repayment needed!"

Replace "of free money" to "for free"

**Comment by meiqimichelle** [comment]
Should be live on dev.

![screen shot 2015-09-04 at 8 33 08 am](https://cloud.githubusercontent.com/assets/4827522/9687705/b4484d88-52df-11e5-95a3-4251c828f9b8.png)

**Comment by ErieMeyer** [comment]
Looks good on dev!

**Comment by ErieMeyer** [comment]
Great on staging!
