### ISSUE TITLE
BUG: can't click into religious affiliation on iphone

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#1012]
When in the "type" section, and I click on "religious affiliation" it opens the "special designation" drop down. I click out of it and back on to religious affiliation and it goes back to special designation.

IPhone 5, 8:21 am, Safari (screenshot coming)

**Comment by ErieMeyer** [comment]
![image](https://cloud.githubusercontent.com/assets/1626026/9683471/6f411a90-52de-11e5-8042-89756b44b698.jpg)

**Comment by meiqimichelle** [comment]
Fix should be live on `dev` @ErieMeyer :us: :us: :us:

**Comment by ErieMeyer** [comment]
Works great on dev now!

**Comment by ErieMeyer** [comment]
Great on staging!
