### ISSUE TITLE
DISPLAY: Reduce space around "Find Schools" button

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1021]
Desktop screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9690651/c5d50d44-530b-11e5-8317-32ec4762689e.png)

Would limit to ~30px top and bottom margin around the button.

**Comment by ErieMeyer** [comment]
Looks good on dev!

**Comment by ErieMeyer** [comment]
:us:
