### ISSUE TITLE
DISPLAY: Hero image should scroll with the rest of the page

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1022]
The hero image appears to be fixed now (perhaps as part of the background). Possible for it to also scroll?

**Comment by meiqimichelle** [comment]
Totally possible. I just like fixed background images the let the rest scroll. No bueno?

**Comment by jjoteal** [comment]
I think this is a personal preference thing. It kinda makes me dizzy, but maybe I'm the only one!

**Comment by meiqimichelle** [comment]
Dizzy is bad! Let's freeze it.

**Comment by ErieMeyer** [comment]
Frozen on dev!

**Comment by ErieMeyer** [comment]
Hmmm -- there's a chance I misunderstood this one. Looping in @jjoteal to review.

**Comment by jjoteal** [comment]
This looks good on prod! Accepting and closing!
