### ISSUE TITLE
DISPLAY: Should be ~20px space between laurel icon and "check out these schools" line item text

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1023]
![image](https://cloud.githubusercontent.com/assets/12192706/9690775/6acf28fc-530c-11e5-8de5-17134d6ea47a.png)

Should be ~20px space between the laurel icon and the beginning of the text.

**Comment by ErieMeyer** [comment]
Looks good on dev!

**Comment by ErieMeyer** [comment]
:us:
