### ISSUE TITLE
DISPLAY: Reduce spacing around text in footer

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1024]
Desktop screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9690815/aa0ae7e0-530c-11e5-99fa-fc027ccd9275.png)

Reduce to ~40px top and bottom margin around the text.

**Comment by ErieMeyer** [comment]
Looks beautiful!

**Comment by ErieMeyer** [comment]
:us:
