### ISSUE TITLE
Update footer to credit GeoNames

### ISSUE THREAD

**Issue by hollyallen** [18F/college-choice#1026]
Update the footer to credit GeoNames, as required by CCBY, and because it is the right thing to do.

Zipcode latitude and longitude provided by [GeoNames](http://www.geonames.org/) under under a Creative Commons Attribution 3.0 License.

**Comment by meiqimichelle** [comment]
@jjoteal Thoughts on how to the footer should look with this addition?

**Comment by jjoteal** [comment]
Well, without a full redesign of the footer at this point, I would recommend adding that line of text ("Zipcode latitude and longitude provided by GeoNames under under a Creative Commons Attribution 3.0 License.") in 12px #666 type under the Contact Us link.

**Comment by jjoteal** [comment]
Reassigning to @meiqimichelle for implementation.

**Comment by meiqimichelle** [comment]
Should be live on `dev`

**Comment by ErieMeyer** [comment]
Looks great!
