### ISSUE TITLE
DISPLAY: iphone 5 issues on "Get the Best Deal" block

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1029]
Screenshot:

![image](https://cloud.githubusercontent.com/assets/12192706/9691164/d9bbae3c-530e-11e5-9174-3c54ea9ffdd5.png)

Possible to: 
- Reduce the space above the buttons?
- On the "Estimate Your Aid" button, can "Your Aid" be on the 2nd line?

**Comment by meiqimichelle** [comment]
I reduced the space above, and also made the text a bit smaller at smaller sizes, plus pumped up the inner padding so the word would be forced onto more than one line earlier. However, I can't tell it to make the words two lines when we want them to be -- there are too many permutations of browser widths to make it work :(

Here's how it looks now on a small size:
![screen shot 2015-09-05 at 2 12 03 pm](https://cloud.githubusercontent.com/assets/4827522/9701320/6add9c12-53d8-11e5-8f0d-6970689b6076.png)

And a teeeny size:
![screen shot 2015-09-05 at 2 12 18 pm](https://cloud.githubusercontent.com/assets/4827522/9701322/746dba50-53d8-11e5-80ff-8c986e1721a3.png)

**Comment by meiqimichelle** [comment]
(or rather -- you can make the space thing happen with a lot of effort, but it's likely not worth the effort)

**Comment by ErieMeyer** [comment]
Looks good on dev!

**Comment by ErieMeyer** [comment]
:us:
