### ISSUE TITLE
DISPLAY: Fix footer background color on iphone 5

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1030]
Screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9691198/10abb4a0-530f-11e5-8cc4-b4f62093bc98.png)

Light gray background color should extend to the bottom.

**Comment by meiqimichelle** [comment]
@jjoteal I think this was fixed in passing when we added/adjusted the footer yesterday. Check?

**Comment by jjoteal** [comment]
Looks good! Closing!
