### ISSUE TITLE
DISPLAY: Supporting text under School name on individual school page should also be #040404

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1032]
![image](https://cloud.githubusercontent.com/assets/12192706/9691526/e99db578-5310-11e5-849d-393f06c6ee83.png)

"Milwaukee, WI
8,190 undergraduate students"

Should be #040404.

Also, can you confirm the text size is ~24px? It looks a little large... if it is ~24px, perhaps we bring down to ~21px?

**Comment by meiqimichelle** [comment]
The size was ~24 so I dropped it to ~21px (and changed to color to #040404). Looks like this:

![screen shot 2015-09-05 at 10 16 58 am](https://cloud.githubusercontent.com/assets/4827522/9700426/566021fe-53b7-11e5-9e26-ddef40f3f099.png)

Should the size be dropped further on mobile?
![screen shot 2015-09-05 at 10 17 56 am](https://cloud.githubusercontent.com/assets/4827522/9700429/6a05fc92-53b7-11e5-92d3-9f7eb1b97e9c.png)

**Comment by ErieMeyer** [comment]
Looks good on dev!

**Comment by ErieMeyer** [comment]
:us:
