### ISSUE TITLE
DISPLAY: Add label + tooltip to Earnings > % earning more than those with only a high school diploma

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1033]
This is the only stat without a label + tooltip, so for consistency's sake, we should add one.

For the time being add "Earning Potential" as the label and add a tooltip that is associated with the glossary.yaml term "earnings-25k"

**Comment by meiqimichelle** [comment]
I think this is the same as #926, which was fixed with #1063. @jjoteal I am closing this for now. Please reopen if this is something else.

**Comment by jjoteal** [comment]
Nope, this is not a dupe. I'm hoping to add a label + tooltip above the metric so that it is in a consistent format with all the other items on the page.

So, looking at this screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9704397/60f585c0-5473-11e5-88b8-447f5cbc5e03.png)

I'd like to add a label "Earning Potential" (wording will change once Lisa gets final text from Ed) with the "i" tooltip in the same style as "Salary After Attending" right next door.

A good reference for this format is also:

![image](https://cloud.githubusercontent.com/assets/12192706/9704407/9610a8b6-5473-11e5-8400-3e72fe0a872b.png)


As it uses the same text layout as the "Earning Potential" metric.

**Comment by meiqimichelle** [comment]
OOoooooooh, go it! Yeah, it will be much more balanced this way!

**Comment by meiqimichelle** [comment]
Looks like

![screen shot 2015-09-06 at 7 59 47 am](https://cloud.githubusercontent.com/assets/4827522/9705070/4cf15910-546d-11e5-967b-10b49ef4f058.png)

**Comment by jjoteal** [comment]
Not seeing this on dev yet, but your screenshot looks good!

**Comment by ErieMeyer** [comment]
Looks good on dev now!

**Comment by ErieMeyer** [comment]
:us:
