### ISSUE TITLE
DISPLAY: Race/Ethnicity bar graphs look and feel

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1034]
Current screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9692071/9fdefaec-5314-11e5-9250-91a6f3983555.png)

Should look like:
![image](https://cloud.githubusercontent.com/assets/12192706/9692059/9103cb1a-5314-11e5-9c8a-79c24a98eda0.png)

**Comment by meiqimichelle** [comment]
Looks like this:
![screen shot 2015-09-05 at 1 53 54 pm](https://cloud.githubusercontent.com/assets/4827522/9701254/98da3c22-53d5-11e5-9440-06a46f8ffe63.png)

**Comment by ErieMeyer** [comment]
Looks good on dev!

**Comment by ErieMeyer** [comment]
Styles are correct on prod!
