### ISSUE TITLE
DISPLAY: Top of map should top align with top of Name of School

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1035]
Desktop screenshot:

![image](https://cloud.githubusercontent.com/assets/12192706/9692206/82e60fce-5315-11e5-8ab2-ceb5b125c9f9.png)

Top of map should top align with "Marquette"

**Comment by meiqimichelle** [comment]
Looks like

![screen shot 2015-09-05 at 3 49 51 pm](https://cloud.githubusercontent.com/assets/4827522/9701601/ca08330c-53e5-11e5-89c2-34c3fc06769d.png)

**Comment by ErieMeyer** [comment]
Looks like that on dev!

**Comment by ErieMeyer** [comment]
:us:
