### ISSUE TITLE
BUG: Sidebar on Individual School page should be the new "Get the Best Deal" buttons and no longer the CFPB Promo

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1036]
Current screenshot:

![image](https://cloud.githubusercontent.com/assets/12192706/9692250/c849ebe4-5315-11e5-9a44-c303cdf3d347.png)

Should be "Get the Best Deal" title with the 3 green buttons from the homepage:
![image](https://cloud.githubusercontent.com/assets/12192706/9692277/f9a44022-5315-11e5-8dbe-f33234c40308.png)

**Comment by meiqimichelle** [comment]
@jjoteal this looks like
![screen shot 2015-09-05 at 7 25 41 am](https://cloud.githubusercontent.com/assets/4827522/9699642/b549e2ee-539f-11e5-96c0-86553e087b00.png)

You can review on `dev`.

**Comment by ErieMeyer** [comment]
Looks fantastic!
