### ISSUE TITLE
DISPLAY: Pagination presentation on iphone 5

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1038]
Screenshot:

![image](https://cloud.githubusercontent.com/assets/12192706/9692474/52992458-5317-11e5-85a3-bf6bc80b023e.png)

Display improvement requests:
- Possible to have the pagination align left with the sort dropdown?
- Decrease the space between the dropdown and the pagination to be only about ~20px?

**Comment by ErieMeyer** [comment]
Looks good on dev!

**Comment by ErieMeyer** [comment]
:us:
