### ISSUE TITLE
DISPLAY: On iphone 5, Name of School on Individual School page is too large

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1039]
Screenshot:

![image](https://cloud.githubusercontent.com/assets/12192706/9692626/5aa3a136-5318-11e5-9715-7bf38585520b.png)

Original design:
![image](https://cloud.githubusercontent.com/assets/12192706/9692646/6eff382a-5318-11e5-929b-e9b7e269c024.png)

Should be ~24px

**Comment by ErieMeyer** [comment]
Looks great on dev!

**Comment by ErieMeyer** [comment]
:us:
