### ISSUE TITLE
DISPLAY: On individual school page, size of basic information icons should get smaller on mobile to fit on one line

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1040]
Screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9692679/b5c794aa-5318-11e5-99a9-76c5fee7d0c8.png)

Original design:
![image](https://cloud.githubusercontent.com/assets/12192706/9692686/c0232946-5318-11e5-837a-9a0786f389cf.png)

**Comment by barkimedes** [comment]
@jjoteal I don't see this problem on my phone, but I'm wondering if that is just because I have a big screen (Nexus 6). Is this still an issue on smaller screens?
