### ISSUE TITLE
DISPLAY: On mobile, add more space between different sections/metrics of information contained within the expand/collapse units on the Individual School page

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1042]
Screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9693009/078a481c-531b-11e5-818b-62402ee92a0b.png)

Add more space between bottom of "Students Paying Down Their Debt" metric and top of "Get Help Paying for College" block as well as "Get Help Paying for College" and  "Typical Total Debt"

We add the same amount of space consistently throughout all the various expand/collapse units.

**Comment by ErieMeyer** [comment]
Space looks great on dev

**Comment by ErieMeyer** [comment]
:us:
