### ISSUE TITLE
DISPLAY: On mobile, "Start My Application" button need more inner padding

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1043]
Screenshots:

![image](https://cloud.githubusercontent.com/assets/12192706/9693063/7e396290-531b-11e5-904e-cd2bf5b994a4.png)

In the original design, it wrapped onto 2 lines:
![image](https://cloud.githubusercontent.com/assets/12192706/9693084/9f62405e-531b-11e5-9917-b0a02c6552a4.png)

**Comment by meiqimichelle** [comment]
Looks like

![screen shot 2015-09-05 at 3 34 48 pm](https://cloud.githubusercontent.com/assets/4827522/9701552/d206d060-53e3-11e5-8f8a-ace43dc04d75.png)

**Comment by ErieMeyer** [comment]
Looks great on dev!

**Comment by ErieMeyer** [comment]
:us:
