### ISSUE TITLE
DISPLAY: On mobile, on individual school page expand/collapse containers, ensure there is ~10-15px of inner margin so the text doesn't run into the border

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1045]
Screenshot:

![image](https://cloud.githubusercontent.com/assets/12192706/9693128/f99294e8-531b-11e5-8c52-0825bebb16c7.png)

The "mo" should only go as wide as the inner horizontal rule.

Original design:
![image](https://cloud.githubusercontent.com/assets/12192706/9693150/1b65a22c-531c-11e5-88e8-99078bb76810.png)

Changing the "/mo" font weight from bold to regular might help with this a bit, but not sure if it will eradicate the issue.

**Comment by meiqimichelle** [comment]
Make text size slightly smaller on small screens. This still runs over when you have "fat" numbers (does not with skinny numbers).

**Comment by barkimedes** [comment]
@jjoteal @meiqimichelle Another one that looks fixed on everything I can try it on, but I don't have a really small phone screen. Is this fixed and can we close the issue?
