### ISSUE TITLE
DISPLAY: On iphone 5, to much space between "of" and "students" on % earning over $25K metric

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1046]
Screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9693272/187a4abc-531d-11e5-8be4-234ddf595219.png)

Reduce the line space between "86% of" and "students"

**Comment by barkimedes** [comment]
@jjoteal @meiqimichelle This is another one that looks fixed on everything I can try it on. Can we close it?
