### ISSUE TITLE
DISPLAY: On iphone 5, possible to fit full-time/part-time % on one line?

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1047]
Screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9693313/64aab516-531d-11e5-9742-7fd6f6b63715.png)

**Comment by meiqimichelle** [comment]
This is a little bit non-trivial. I did adjust the spacing and sizing here to make it flow a tiny bit more gracefully, looks like this now:

![screen shot 2015-09-05 at 12 59 59 pm](https://cloud.githubusercontent.com/assets/4827522/9701050/21b4b480-53ce-11e5-9fae-241e2a9d9941.png)

**Comment by meiqimichelle** [comment]
Assigning this to you @jjoteal for your thoughts

**Comment by jjoteal** [comment]
Unable to truly test on iphone right now, as dev results in errors, but when I shrink my browser window on desktop to approximate mobile size, it looks great!

![image](https://cloud.githubusercontent.com/assets/12192706/9704374/aad22cbc-5472-11e5-86f9-e8eb6dab3a06.png)

**Comment by barkimedes** [comment]
@jjoteal @meiqimichelle  It's all one line on my phone (Nexus 6) and when I made my desktop window as small as possible, it was all one line. So is this still an issue on iPhone or can we close this?

**Comment by jjoteal** [comment]
This is still an issue on iphone. Will post the iphone screenshot as soon as it comes through.
