### ISSUE TITLE
DIPLAY: Numbers under value snapshot displaying too small on iphone 5

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1048]
Screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9693411/3f666588-531e-11e5-817d-5b02963396bf.png)

Original design:
![image](https://cloud.githubusercontent.com/assets/12192706/9693415/516e80b2-531e-11e5-929e-9c6c55781767.png)

Possible to make this text under the bar graphs a little larger?

**Comment by meiqimichelle** [comment]
This size was confirmed via #1052. Check again?

**Comment by jjoteal** [comment]
Unable to test on dev right now, as page results in error:

![image](https://cloud.githubusercontent.com/assets/12192706/9704340/b42fe098-5471-11e5-9eed-5222a0d1a7a9.png)

**Comment by ErieMeyer** [comment]
Here's what's on dev right now:
![image](https://cloud.githubusercontent.com/assets/1626026/9718901/a2fecab4-554d-11e5-9f55-54e6107989c9.png)

Numbers look bigger but not quite as big as in the design.

**Comment by jjoteal** [comment]
These look good! Accepting and closing!

**Comment by ErieMeyer** [comment]
We shouldn't close until we can accept on testing

**Comment by ErieMeyer** [comment]
Err -- staging.

**Comment by jjoteal** [comment]
Closing as this is live.
