### ISSUE TITLE
BUG/ENHANCEMENT: Do not have any search parameters open by default on homepage

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1051]
The original design intended for the "Find Schools" button to be visible within the first screen of the mobile interface so the user would not have to scroll to see the button (and actually, could just hit 'Find Schools' right away if he/she wanted to to get instant results). If we have a section like "Programs/Degrees" open by default, we force the user to scroll to get the 'Find Schools' button, which isn't ideal.

Leaving this up to @LisaGee to decide upon, of course, but wanted folks to know the original intent of having all sections closed by default.

**Comment by LisaGee** [comment]
@jjoteal I also think this is a good idea, b/c that's how I think it should be on the Search Results page when you Refine Results.

**Comment by ErieMeyer** [comment]
Love this. Looks great on dev.

**Comment by ErieMeyer** [comment]
:us:
