### ISSUE TITLE
DISPLAY: Confirming font sizes in Individual School Card

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1052]
Just confirming a few font sizes in the individual school cards, as things generally look a little "off" on my iphone 5. Here's a screenshot from the iphone:

![image](https://cloud.githubusercontent.com/assets/12192706/9694048/366ecd8a-5323-11e5-9d7a-5458384d25a5.png)

And here's the original design:
![image](https://cloud.githubusercontent.com/assets/12192706/9694109/c57993f2-5323-11e5-921c-bdf65762d944.png)

Font sizes in the PSD:
- Name of School: 24px bold
- Location/Size: 16px regular
- Labels Above Value Snapshot: 11px bold
- Numbers Below Graphs: 14px bold
- View More Details: 12px bold

**Comment by meiqimichelle** [comment]
With some adjustments:

![screen shot 2015-09-05 at 10 37 40 am](https://cloud.githubusercontent.com/assets/4827522/9700505/27ed80d4-53ba-11e5-977c-0cc70b0eff30.png)

**Comment by ErieMeyer** [comment]
Will need @jjoteal to acceptance test -- my font eyes aren't good enough (yet!)

**Comment by jjoteal** [comment]
This looks good! Accepting and closing!
