### ISSUE TITLE
DISPLAY: Text flow for "By the Numbers" facts on iphone 5

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1053]
Screenshot:

![image](https://cloud.githubusercontent.com/assets/12192706/9694238/c1d15ec8-5324-11e5-90ac-9866eea36d5e.png)

Possible to take out the hard line breaks so "pay for" isn't on a line by itself?

**Comment by ErieMeyer** [comment]
Looks great on dev!

**Comment by ErieMeyer** [comment]
:us:
