### ISSUE TITLE
DISPLAY: Adjust Data homepage design

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1057]
Because of the major cuts to the homepage content, change the homepage layout from this (screenshot):
![image](https://cloud.githubusercontent.com/assets/12192706/9695066/4d7ff284-532c-11e5-8bac-74ba007b70db.png)

To this:

![image](https://cloud.githubusercontent.com/assets/12192706/9695058/39df2bf0-532c-11e5-98f3-45ad53464817.png)

**Comment by meiqimichelle** [comment]
Oooo, nice! :heart_eyes: On it!

**Comment by ErieMeyer** [comment]
Looks :heart_eyes: on dev!

**Comment by ErieMeyer** [comment]
:us: :heart_eyes:
