### ISSUE TITLE
DISPLAY: Data Documentation Page Visual Improvements

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1059]
Screenshot:

![image](https://cloud.githubusercontent.com/assets/12192706/9695541/de23782a-5330-11e5-82fa-fee6d37750ac.png)

Recommend the following:
- Making "Structure" and Sample API Calls" larger so they stand out as subheaders
- Inserting thin horizontal rules between the sections in the sidebar with at least 20px margin above and below them. Insert those HRs above "Structure" and "Sample API Calls"
- Implement new "Join the Conversation" area layout: 
![image](https://cloud.githubusercontent.com/assets/12192706/9695601/66649e3a-5331-11e5-9031-a23e5afe3d38.png)
(FYI gray bar in the design is ~128px tall)
- Insert ~100px top padding above where the content starts on the white background (it's starting a little too close to the gray bar at this point)
- Implement same footer spacing from https://github.com/18F/college-choice/issues/1024 (so only ~40px of light gray above and below the text)

**Comment by ErieMeyer** [comment]
Looks great on dev!

**Comment by ErieMeyer** [comment]
:us:
