### ISSUE TITLE
Contact Us link in Footer should go to an RTI email address, not the Contact Us page on ED

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1060]
@ErieMeyer can you dig out the proper email address to use?

**Comment by LisaGee** [comment]
then assigne to @meiqimichelle

**Comment by LisaGee** [comment]
Email address to use: scorecarddata@rti.org

**Comment by meiqimichelle** [comment]
Ready for review on dev

**Comment by ErieMeyer** [comment]
looks good on dev!

**Comment by ErieMeyer** [comment]
Looks good on staging!
