### ISSUE TITLE
BUG: iPhone display weirdness for data tool

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#1070]
This is on an iPhone in safari
![image](https://cloud.githubusercontent.com/assets/1626026/9697661/94e45e76-5363-11e5-8f46-a0620676fe66.jpg)
![image](https://cloud.githubusercontent.com/assets/1626026/9697662/94f77394-5363-11e5-91a5-293772356f2d.jpg)
![image](https://cloud.githubusercontent.com/assets/1626026/9697663/94f802dc-5363-11e5-8058-8f9c7b2ef524.jpg)

**Comment by meiqimichelle** [comment]
The data part of the site does not have much responsive code. Desktop users were prioritized for that part of the site so unfortunately this display is as expected for those pages. /cc @LisaGee

**Comment by LisaGee** [comment]
Dupe of #1251
