### ISSUE TITLE
BUG overflow at small screen sizes

### ISSUE THREAD

**Issue by meiqimichelle** [18F/college-choice#1071]
This was discovered while working on #1008, and has something to do with the value meters (not pagination).

  ![image](https://cloud.githubusercontent.com/assets/113896/9697359/5acc3dcc-533f-11e5-8e89-80804285d26d.png)

**Comment by meiqimichelle** [comment]
I thought this might have something to do with #971 and so worked on this in hopes of solving that. It is unrelated, but is now fixed and ready for review on dev.

**Comment by ErieMeyer** [comment]
Looks great on Dev!

**Comment by ErieMeyer** [comment]
:us:
