### ISSUE TITLE
should we increase quota for Cloud Foundry?

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#1073]
We're now at 83%... probably because of the recent logging / monitoring additions.  That feels high.

**Comment by ultrasaurus** [comment]
@ozzyjohnson what do you think?

**Comment by ozzyjohnson** [comment]
@ultrasaurus - It does seem high, but the monitoring apps are tiny (16MB) and services are counted different than applications for quota purposes. Thing is, unless we add more spaces / multiple instances of an app the quota will stay steady.

I can certainly raise it, it means a higher daily cost for the project.

**Comment by ultrasaurus** [comment]
@ozzyjohnson will we get notified if it gets dangerous?

**Comment by ultrasaurus** [comment]
Sounds like this is fine.

**Comment by ultrasaurus** [comment]
I will move to accept for @LisaGee to review, since this is something she should be aware of, I think

**Comment by barkimedes** [comment]
I think we're good. Closing :smile:
