### ISSUE TITLE
Font size in drop downs seem too large, as compared to other elements

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1076]
Elements in entry fields, like ZIP code and Special Designation are larger than the labels. I don't think they should be.

![image](https://cloud.githubusercontent.com/assets/12847090/9699571/cc643c48-53b5-11e5-999f-c2b570cb549d.png)

**Comment by jjoteal** [comment]
This would actually need to be assigned to @meiqimichelle to adjust in the code.
