### ISSUE TITLE
Clear All Filters Button

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1085]
Now that Filters are separated into their own section, it would be great to have a Clear All or Reset option.

@jjoteal What would be the best way to make it work?

**Comment by jjoteal** [comment]
I recommend something like this:

![image](https://cloud.githubusercontent.com/assets/12192706/9700141/afe814e8-53c6-11e5-98de-05915d8c234f.png)

If you approve, we can assign for implementation.
