### ISSUE TITLE
Recommend changing "Enter a ZIP code" to just "ZIP code"

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1086]
![image](https://cloud.githubusercontent.com/assets/12192706/9700092/6d2aa1b2-53c5-11e5-9cac-ce8c2096f934.png)

Change to "ZIP Code"

Assigning to @LisaGee for consideration.

**Comment by ErieMeyer** [comment]
Agree! PR here: https://github.com/18F/college-choice/pull/1123

**Comment by barkimedes** [comment]
@LisaGee It looks like #1123 was closed because "Enter a ZIP code" matched the actiony writing of other fields. But "MIle radius" (which is right next to it) doesn't match that actiony tone. So I would recommend "ZIP code" and "Mile radius" for these fields. 

If not, we should close this issue.
