### ISSUE TITLE
DISPLAY: In footer, for the GeoNames attribution, possible to have the text only on 2 lines and smaller?

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1088]
Screenshot:

![image](https://cloud.githubusercontent.com/assets/12192706/9700234/c2be5d36-53c9-11e5-9ff8-cd510c9768bf.png)

Reduce font size to ~12px or ~11px and put text onto 2 lines (i know it will be 3 on mobile)

**Comment by ErieMeyer** [comment]
Looks good on dev!

**Comment by ErieMeyer** [comment]
:us:
