### ISSUE TITLE
DISPLAY: When selection made in search criteria, change selected item text to be #040404

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1089]
Screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9700264/8882881c-53ca-11e5-8741-700d3c9aa7be.png)

In this case, "New Jersey" should change from #666 to #040404 once it is selected.

**Comment by barkimedes** [comment]
@jjoteal It still looks like a lighter gray color when I run it locally, so I don't know if @jfredrickson's change was supposed to fix it or if it actually fixed it. So I'll prioritize it in the backlog as though it isn't fixed, but if someone else thinks it is fixed and wants to close the issue, that's cool.
