### ISSUE TITLE
consider setting API limit to page size

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#1092]
see related:  https://github.com/18F/open-data-maker/issues/191

We need to do something so that it is not so easy to cause the server to crash simply by using the API as documented

**Comment by ultrasaurus** [comment]
For post launch, I've written up this issue:  https://github.com/18F/college-choice/issues/1155  to look at allowing for a larger page size for data analysis

**Comment by yozlet** [comment]
Now the maximum `per_page` is 100, even when you try to set it higher. Example: https://ccapi-ex.18f.gov/v1/schools?_per_page=2000&school.degrees_awarded.predominant__range=2..3&_debug=1&fields=school.name,id,2013.cost.avg_net_price.overall&sort=2013.cost.avg_net_price.overall:asc

**Comment by ultrasaurus** [comment]
it appears that search time goes up linaerly with the size of the page, tho this at least caps the slowness.  So will accept / clost.
