### ISSUE TITLE
Data issue: Columbus State Community College missing

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#1096]
On staging, looks like Columbus State Community College is missing: http://www.cscc.edu

**Comment by barkimedes** [comment]
This school could be missing for any number of reasons, some of which may be valid, some may be invalid. It is worth understanding why this school is gone and make sure its for a valid reason. Otherwise, we could have a very serious bug in which schools we expect to be showing up are not.

**Comment by LisaGee** [comment]
@barkimedes - Can you confirm in the data that the school should be showing in the Consumer Tool?

**Comment by LisaGee** [comment]
CURROPER==1 and PREDDEG==2||3 is what is required for a school to show up at the moment in the Consumer Tool.

**Comment by barkimedes** [comment]
related to #951. Need to go through and make sure the info is shared appropriately.

**Comment by barkimedes** [comment]
@ErieMeyer I checked on this--rest assured that Columbus State Community College will be included in the tool once #951 is committed. :us:

**Comment by yozlet** [comment]
Confirmed that it's in there after indexing: https://ccapi-indexing.18f.gov/v1/schools?school.name=Columbus%20State%20Community%20College&fields=id,school.name,2012.academics.program.assoc.any,2012.academics.program.bachelors.any,2012.academics.program.assoc_or_bachelors.any
