### ISSUE TITLE
eservice proxy bad gateway?

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#1099]
https://ed-dev-eservice-proxy.18f.gov/

502 Bad Gateway

**Comment by ultrasaurus** [comment]
@ozzyjohnson am I using the right URL?

**Comment by ozzyjohnson** [comment]
This is resolved, we ended up with two proxy instances one created before the script, one after. Though, it shouldn't change often the `make-proxy` script will recreate / reset the proxy and always provide the current route with the `-p` switch.

**Comment by ultrasaurus** [comment]
works for me
