### ISSUE TITLE
Alpha-sort isn't working

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#1101]
For instance, search all HBCUs (92 results) and sort A to Z. See below.

![image](https://cloud.githubusercontent.com/assets/13874735/9705320/2839b410-548f-11e5-923f-5fb629f61dc0.png)

**Comment by LisaGee** [comment]
@ultrasaurus This sort used to work.

**Comment by ultrasaurus** [comment]
yeah, I'll be the different approach to name matching also affects sort, though I had thought that it was set up independently.  Will look

**Comment by LisaGee** [comment]
broke with change in name sorting.
implementation was same type as did before when it was working.
Will require that we spot check that data is correct, given that we have to re-index.

If the re-index doesn't work, would roll back. Have a snapshot of the index we are using.
[ull request 194 on open data maker

**Comment by LisaGee** [comment]
@ultrasaurus @hollyallen @yozlet Assume this has been pushed to Dev, b/c it's working in Dev.

**Comment by hollyallen** [comment]
Yes, @ultrasaurus pushed it to dev around 9am PT, during our morning meeting. Looks great to me.

**Comment by ErieMeyer** [comment]
looks good on dev!

**Comment by jjoteal** [comment]
Looks good on staging! Accepting and closing!
