### ISSUE TITLE
Requested Copy Edits

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1104]
![image](https://cloud.githubusercontent.com/assets/12847090/9705995/a3df4dee-54a5-11e5-91db-d8c8c09e5f66.png)

![image](https://cloud.githubusercontent.com/assets/12847090/9706002/0c5775ae-54a6-11e5-9b7e-f7d8a098d353.png)
![image](https://cloud.githubusercontent.com/assets/12847090/9706004/1b931dac-54a6-11e5-827c-a797d3f59abd.png)
![image](https://cloud.githubusercontent.com/assets/12847090/9706011/4faa1d66-54a6-11e5-935a-b7c4cbfd8e69.png)
![image](https://cloud.githubusercontent.com/assets/12847090/9706019/7e562948-54a6-11e5-8539-af00c81f6be8.png)
Programs/Degree	Programs/Degrees (plural)	Homepage	Grammar

**Comment by ErieMeyer** [comment]
Working on a PR for these

**Comment by ErieMeyer** [comment]
Lisa finished a PR for this one here: https://github.com/18F/college-choice/pull/1105/files

**Comment by meiqimichelle** [comment]
Should be live on dev for review

**Comment by ErieMeyer** [comment]
Looks good on dev!

**Comment by ErieMeyer** [comment]
:us:
