### ISSUE TITLE
Changes to Special Designation copy in Search drop-down

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1106]
![image](https://cloud.githubusercontent.com/assets/12847090/9706077/bf72415e-54a7-11e5-98fc-d6e2c7dcc44e.png)
![image](https://cloud.githubusercontent.com/assets/12847090/9706091/56ce85e4-54a8-11e5-98be-1af4d293bb75.png)

**Comment by meiqimichelle** [comment]
Ready for review on `dev`

**Comment by ErieMeyer** [comment]
Looks great on dev!

**Comment by ErieMeyer** [comment]
:us:
