### ISSUE TITLE
HP Fun Facts Edits

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1109]
![image](https://cloud.githubusercontent.com/assets/12847090/9706284/ea648d2a-54ae-11e5-90a2-672ecdbb9d67.png)

![image](https://cloud.githubusercontent.com/assets/12847090/9706328/b1484b20-54af-11e5-8371-5527b4c8900b.png)

**Comment by meiqimichelle** [comment]
Ready for review on `dev`

**Comment by ErieMeyer** [comment]
Looks great on Dev!

**Comment by ErieMeyer** [comment]
:us:
