### ISSUE TITLE
Search Page Copy Changes

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1111]
1. Size (small to large)	Size (Small to Large)--capitalize	Search resultsSize sort label	Consistency /grammar

2. Under Investigation	Under ED Monitoring	Search Results pageLabel for HCM2 schools	Per Mushtaq’s emails	My concern is that going forward we will want this flag to be used for more than just HCM2. What will it read at that point?

**Comment by meiqimichelle** [comment]
Ready for review on dev

**Comment by ErieMeyer** [comment]
:us:
