### ISSUE TITLE
As a Student, I'd like to be able to enter multiple school names, much like I can do for States, so that I can compare the several schools I'm thinking of attending in on easy search.

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1117]
@jjoteal How should this be laid out?

**Comment by jjoteal** [comment]
@LisaGee I would lay this out exactly like we do for adding more than 1 state and region -- keep it consistent.  So:

![image](https://cloud.githubusercontent.com/assets/12192706/9707031/2b136a8e-54c9-11e5-8272-0eb522bc8a4d.png)

But with the Name field, obv.

**Comment by ErieMeyer** [comment]
Sounds good!
