### ISSUE TITLE
As a developer, I would like API documentation to be correct, so I can write apps

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#1127]
latest API is at /v1/schools
I know it is not correct grammar but i think the period at the end of the URL was confusing (top right of page)
Also the ‘location’ category needs to be at the root --  we won’t be able to fix that for v1 API

**Comment by ultrasaurus** [comment]
I did a PR:  https://github.com/18F/college-choice/pull/1125
just adding an issue for awareness

**Comment by ultrasaurus** [comment]
@meiqimichelle can you review that I didn't screw up formatting and merge?

**Comment by yozlet** [comment]
I'm also working on some URL syntax docs here: https://github.com/18F/open-data-maker/blob/api-docs/API.md

**Comment by barkimedes** [comment]
LGTM. @ultrasaurus Feel free to reopen if there's anything else that needs to be done here, but it looks done to me :smiley_cat:
