### ISSUE TITLE
Replace Actual Cost with Average Annual Cost or Avg Annual Cost where tight on space

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1129]

**Comment by meiqimichelle** [comment]
At a small sliver of screen widths, this change does this:
![screenshot 2015-09-07 07 43 55](https://cloud.githubusercontent.com/assets/4827522/9718911/8c6bb9ec-5534-11e5-886b-3077345443c7.png)

Do you still want the change?

**Comment by meiqimichelle** [comment]
Ok, I introduced a new setting that pops these cards over to one-up earlier. Now it looks like:
![screenshot 2015-09-07 07 54 36](https://cloud.githubusercontent.com/assets/4827522/9719039/b69d2204-5535-11e5-92de-53aff70a6a00.png)

**Comment by meiqimichelle** [comment]
Ready for review on dev

**Comment by ErieMeyer** [comment]
Looks good on prod!
