### ISSUE TITLE
Finalize tooltips

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1134]
Ensure consistency.
* Avg annual cost: The average annual net price for federal financial aid recipients, after aid from the school, state, or federal government. For public schools, this is only the average cost for in-state students. (Was: The average annual cost of attendance for Title IV students less any state, federal, or institutional grant aid.)
* Graduation rate: The graduation rate after six years for schools that award predominantly four-year degrees and after four years for all other schools. These rates are only for full-time students enrolled for the first time. (Was: The completion rate for first—time, full—time students within 150 percent of  the expected time to completion for predominantly four-year schools, and within 200 percent for less-than-four-year schools.)
* Salary after attending: The median earnings of former students who received federal financial aid, at 10 years after entering the school. (Was: The median earnings of students who are working and not enrolled in college, measured 10 years after they first enroll.)
* Typical Total Debt: The median federal debt of undergraduate borrowers who completed. This figure includes only federal loans; it excludes private student loans and Parent PLUS loans. (Was: Says typical total debt twice. Also add “undergraduate borrowers” instead of just “borrowers.” Take out the word Stafford.)
* HCM2: Heightened Cash Monitoring is when the Department of Education provides additional oversight because of financial or federal compliance issues, including but not limited to, concern around the school’s administrative capabilities, concern around a schools’ financial responsibility and possibly severe findings uncovered during a program review. Some schools are on this list because of preliminary findings made during a program review that is still open. (Was:Heightened Cash Monitoring is a step that the Department can take with institutions to provide additional oversight for a number of financial or federal compliance issues, including but not limited to, concern around the school’s administrative capabilities, concern around a schools’ financial responsibility and possibly severe findings uncovered during a program review.  Some schools are on this list due to preliminary findings made during a program review that is still open.)
* Race/Ethnicity: The specific race/ethnicity categories (including those for foreign students pursuing postsecondary education at an institution within the U.S.) are mandated by Departmental regulation (2007) as required and/or approved by the Office of Management and Budget (1997). (Was: The share of students enrolled for credit who identified themselves in each race/ethnicity.)
* Students Receiving Federal Aid: The share of undergraduate students who received Pell grants or federal loans. (Was: The share of undergraduate students who borrowed federal loans.)
* Retention Rate: Students Who Return After Their First Year (Was: Students Who Return After the First Year)
* Threshold Earnings: Threshold Earnings (Was:Former Students Earning More Than $25K)
* Was: The five largest programs of study, as measured as the share of students enrolled. New: The five largest programs of study, as measured as the share of degrees awarded

**Comment by meiqimichelle** [comment]
Ready for review on dev

**Comment by ErieMeyer** [comment]
Threshold earnings looks different, but I think this is intentional: 
![screen shot 2015-09-08 at 12 01 03 am](https://cloud.githubusercontent.com/assets/1626026/9726131/c937e098-55bc-11e5-8716-1c7dcd86101e.png)

Pinging @LisaGee for final review

**Comment by LisaGee** [comment]
This screenshot is an accurate reflection of what we desire.

**Comment by LisaGee** [comment]
Got them all in!
