### ISSUE TITLE
Copy changes to School Page

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1137]
* Was: X% of students who attend this school will earn more than those with only a high school diploma. New: X% of students who attend this school earned, on average, more than those with only a high school diploma.
* Was: Admissions header. New: SAT/ACT Scores
* Was: X% of students have a family income less than $40k and receive a grant to pay for college. New: X% of students have a family income less than $40k and receive an income-based federal Pell Grant to help pay for college.
* Paying For College - right sidebar

**Comment by meiqimichelle** [comment]
Ready for review on dev

**Comment by ErieMeyer** [comment]
Looks great on prod!
