### ISSUE TITLE
COPY: Changing for-profit etc.

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#1147]
Three copy changes from Ed I'm working on:

![screen shot 2015-09-07 at 9 57 00 am](https://cloud.githubusercontent.com/assets/1626026/9718108/d7dd5bbc-5546-11e5-90d6-9de815e685e0.png)

**Comment by ErieMeyer** [comment]
Erie submitting pull request

**Comment by meiqimichelle** [comment]
Ready for review on dev

**Comment by ErieMeyer** [comment]
Looks good on dev!!

**Comment by ErieMeyer** [comment]
Good on prod!
