### ISSUE TITLE
Update test plan to not include schools with NULL size

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1150]
1. Search by col should return 1788 schools, but only finds 1780 - https://federalist.18f.gov/preview/18F/college-choice/staging/search/?online=1&name=col&sort=advantage:desc
2. Search for all Small schools should return 2027, but finds 2029 - https://federalist.18f.gov/preview/18F/college-choice/staging/search/?online=1&size=small&sort=advantage:desc
3. Bachelors Only should return 2101, but finds 2099 - https://federalist.18f.gov/preview/18F/college-choice/staging/search/?degree=b&online=1&sort=advantage:desc
4. All Private Non profit should return 1404, but finds 1402 - https://federalist.18f.gov/preview/18F/college-choice/staging/search/?online=1&control=private&sort=advantage:desc

**Comment by ultrasaurus** [comment]
1. https://college-choice.18f.gov/search/?online=1&name=col&sort=advantage:desc shows 1780 schools

**Comment by ultrasaurus** [comment]
2. https://college-choice.18f.gov/search/?online=1&size=small&sort=advantage:desc hsows 2029 schools

**Comment by ultrasaurus** [comment]
* 3. https://college-choice.18f.gov/search/?degree=b&online=1&sort=advantage:desc shows 2099 schools

**Comment by hollyallen** [comment]
Related: #1064

**Comment by ultrasaurus** [comment]
* preddeg 2..3 AND operating=1 AND 2013.student.size=0.. = 3589 results
https://ccapi-production.18f.gov/v1/schools?sort=2013.student.size:asc&school.degrees_awarded.predominant__range=2..3&fields=id,school.name,2013.student.size&school.operating=1

* preddeg 2..3 AND operating=1 AND 2013.student.size=0.. = 3587 results
https://ccapi-production.18f.gov/v1/schools?sort=2013.student.size:asc&school.degrees_awarded.predominant__range=2..3&2013.student.size__range=0..&fields=id,school.name,2013.student.size&school.operating=1

**Comment by hollyallen** [comment]
1. we verified that the 'col' search isn't working the same as Lisa thought because she was including schools with 'col' anywhere (like in the word "Lincoln"), whereas the consumer tool search only searches for words that start with 'col'.
