### ISSUE TITLE
Browser Tab for College Scorecard Data should read as such and have an appropriate favicon

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1151]
Currently the tab reads Data and the favicon appears to be a Federalist one.
![image](https://cloud.githubusercontent.com/assets/12847090/9719134/c134fbbe-554f-11e5-90f1-23894f3c5db6.png)

It should read College Scorecard Data and have a US Dept of Ed favicon.

**Comment by meiqimichelle** [comment]
I can't recreate the favicon issue on my end, although favicons tend to stick around in cache for a long time -- you might be seeing an old one. I am moving this to in progress for the tab words, fixing that now.

**Comment by meiqimichelle** [comment]
Tab words ready for review on dev

**Comment by ErieMeyer** [comment]
looks good on dev

**Comment by LisaGee** [comment]
And on Staging.
