### ISSUE TITLE
Front page background image showing up in strange way at certain screen width

### ISSUE THREAD

**Issue by hollyallen** [18F/college-choice#1160]
https://college-choice.18f.gov/ on a desktop (not a mobile device).
Starting with the browser window very wide, make the page narrower until it change to a single column mobile-type view. Note that a small bar of the background image (with graduating students) appears below the blue horizontal bar, above the "By The Numbers" text. It should not.

<img width="468" alt="screen shot 2015-09-07 at 10 10 54 am" src="https://cloud.githubusercontent.com/assets/3476681/9721044/a7fdf14c-5549-11e5-9701-ff7eabb36441.png">

**Comment by meiqimichelle** [comment]
Ready for review on dev

**Comment by hollyallen** [comment]
Looks great.

**Comment by ErieMeyer** [comment]
This is good for now, Holly! We'll close it once it's on staging.

**Comment by ErieMeyer** [comment]
:us:
