### ISSUE TITLE
"Add state" button when "Any" selected produces confusing result

### ISSUE THREAD

**Issue by alex** [18F/college-choice#1161]
in the "Location" search functionality:

![screen shot 2015-09-07 at 1 34 33 pm](https://cloud.githubusercontent.com/assets/772/9721235/33873b72-5565-11e5-91ea-c7337fbe8eb5.png)

if you press the "ADD STATE" button while "Any" is selected, then a 2nd dropdown momentarily flashes, before disappearing

**Comment by barkimedes** [comment]
Same with "Add region"
