### ISSUE TITLE
As a Developer for Veterans' College Choice tool, I'd like to identify for my users, for every school, if they will be able to leave a school and earn enough money to incur the debt they racked up at that school, and if not, tell them to stay away. 

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#117]

**Comment by LisaGee** [comment]
Are people borrowing more than they can afford to repay?

**Comment by LisaGee** [comment]
Will be used to calculate loans as a % of salary

**Comment by LisaGee** [comment]
@ErieMeyer Can you reach out and see if this API gives them what they need?

**Comment by saintsoup52** [comment]
Are you guys asking about the GI Bill Comparison Tool here?

If so the API is missing the following data points used by the VA on their comparison tool:
1) Key Cost of Attendance Information - IPEDS
> Housing Costs (on and off campus)
> Other expenses (on and off campus and with family)
> Books expenses
> In-district tuition costs (how much does a community college cost locals) - IPEDS

2) Percentage of classes taught online (not just exclusively online) - IPEDS
3) Accreditation status (is the school on probation) - OPE
4) 8 Keys to Veteran Success School - ED

**Comment by ErieMeyer** [comment]
Yes!

1) that's fine -- ok to still use IPEDS.
2) Same
3) Link to where this is from today?
4) Link to where this is from today?

@greggersh -- thoughts on this issue?

**Comment by saintsoup52** [comment]
Any chance 1 and 2 can be added to API? :-)

Here are links to the other ones:
Accreditation - http://ope.ed.gov/accreditation/
8 Keys - http://www.ed.gov/veterans-and-military-families/8-keys-success-sites

**Comment by ErieMeyer** [comment]
This has been addressed via the beta period -- the things they're missing are from IPEDs and won't be ready for launch. 

(I'm sorry @saintsoup52!)

**Comment by saintsoup52** [comment]
Kein problem (no problem). 

I am looking for to those fast follows. :-)
