### ISSUE TITLE
[Mobile] cannot scroll when finger starts on map image on school details page

### ISSUE THREAD

**Issue by jjtswan** [18F/college-choice#1176]
Repros on android chrome.

1. Search for any school
2. Click through to details of any school with a physical location.
3. Scroll down until you see the map image.
4.with your finger starting somewhere in the map, try scrolling up or down.

Actual result: nothing happens
Expected: screen moves up or down, or the map scrolls.

**Comment by BrianLefler** [comment]
Dupe of #1075

**Comment by barkimedes** [comment]
Closing in favor of #1075
