### ISSUE TITLE
Data Tool HP Copy Changes

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1189]
* Remove quotation marks from Data Insights as they are not direct quotes.
* Replace "From the Technical Paper" to "Learn more in the Technical Paper" under each Data Insight.
* Remove Data Insights: 1, 2, 4, 6, 8, 10 
* Add SAM Data Insight
* Update Intro copy
* Update Data Downloads copy
* Update Data Documentation copy

**Comment by meiqimichelle** [comment]
Ready for review on dev

**Comment by ErieMeyer** [comment]
looks good on dev!

**Comment by ErieMeyer** [comment]
:us:
