### ISSUE TITLE
BUG: HCM2 flag bleeds on single column or mobile 

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#1190]
chrome, mac

To recreate:

- Search for any school in DC region
- click on school "Under Ed Monitoring"
- Make screen thin enough to be one column or on mobile

![screen shot 2015-09-07 at 11 55 44 pm](https://cloud.githubusercontent.com/assets/1626026/9726103/58966c2e-55bc-11e5-88e5-7f30f56fd4d4.png)
![screen shot 2015-09-07 at 11 55 25 pm](https://cloud.githubusercontent.com/assets/1626026/9726106/5dbb4ab2-55bc-11e5-9304-20d27b58d464.png)

**Comment by meiqimichelle** [comment]
@ErieMeyer Good catch! Fixed locally, will be sending to dev momentarily. Looks like

![screenshot 2015-09-08 08 07 51](https://cloud.githubusercontent.com/assets/4827522/9738524/c59cfe7a-5600-11e5-9126-6cdd94a74725.png)

**Comment by ErieMeyer** [comment]
Looks good on dev!

**Comment by ErieMeyer** [comment]
:us:
