### ISSUE TITLE
Data Dictionary should be available for download as a .csv rather than a .pdf

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1192]
Diego has created a cleaned up version of the Data Dictionary, as has Clare.
Should make sure to take the best of both.

**Comment by diego-** [comment]
file pending merge in github; assigning to @meiqimichelle to add link in frontend.

**Comment by meiqimichelle** [comment]
Ready for review on dev

**Comment by ErieMeyer** [comment]
Works great!

**Comment by ErieMeyer** [comment]
Looks great on staging!
