### ISSUE TITLE
Data Tool Documentation Page Copy Edits

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1193]
* Capitalize Accuracy and Privacy
* Completion by Race/Ethnicity
* Rework text in Overview section and include links to documentation downloads.
* Slight text modifications to Accuracy and Privacy section.
* Clean up of Category text.

**Comment by meiqimichelle** [comment]
Ready for review on dev

**Comment by ErieMeyer** [comment]
Looks good on dev!

**Comment by ErieMeyer** [comment]
:us:
