### ISSUE TITLE
Tooltip text changes

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#1217]
Lisa suggested I start a thread for text changes that will ideally be made before launch, recognizing some might not make it.

For race/ethnicity tooltip on IHE page -- what's there now isn't quite right (it wasn't through regulation). Ideally we'd add this link but if that's not possible, just exclude the second sentence. TEXT: The specific race/ethnicity categories (including those for foreign students pursuing postsecondary education at an institution within the U.S.) are either required (1997) and/or approved (2007) by the Office of Management and Budget (2007). More information can be found at: http://nces.ed.gov/IPEDS/reic/resource.asp.

**Comment by claremccann** [comment]
On HCM2 tooltip, add the number "2" after "Heightened Cash Monitoring" in the explanation.

**Comment by LisaGee** [comment]
@claremccann - Sorry, Clare, can you actually start a new ticket for these now? We did get the first one in, so we're going to close this ticket.

**Comment by LisaGee** [comment]
@jjoteal Can you confirm and close? Thanks.

**Comment by barkimedes** [comment]
Verified that the tooltip for race/ethnicity had the correct text at https://collegescorecard.ed.gov/school/?117803-Los-Angeles-County-College-of-Nursing-and-Allied-Health (just picked a random school and looked).
