### ISSUE TITLE
One word change on a Data Tool Insight

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1243]
5th Data Insight.

Directly after the highlight, "one leading effort", we have to remove the word leading.

**Comment by LisaGee** [comment]
@meiqimichelle Pull request ready for review.

**Comment by meiqimichelle** [comment]
Ready for review on dev

**Comment by LisaGee** [comment]
Looks awesome on dev! thanks! And OGC thanks you too!

**Comment by barkimedes** [comment]
Verified that change is live at https://collegescorecard.ed.gov/data/
