### ISSUE TITLE
Revized 'Paying for College' implementation

### ISSUE THREAD

**Issue by meiqimichelle** [18F/college-choice#125]
From #67:

"here is a clipped screenshot of revised mobile and desktop homepage with the new "Paying for College" single promo for CFPB. Please note that in order to keep the columns even on the desktop version, I needed to add 1 additional listing in the "Check Out These Schools" section -- so there are now 4 "listings" vs. just 3."

![1](https://cloud.githubusercontent.com/assets/4827522/8641919/4f7cefc2-28d1-11e5-8516-dd5d8a630db5.png)

![2](https://cloud.githubusercontent.com/assets/4827522/8641923/5e5477b8-28d1-11e5-96d3-4098b48a1f9e.png)

**Comment by meiqimichelle** [comment]
Now: 
![screenshot 2015-07-15 13 20 59](https://cloud.githubusercontent.com/assets/4827522/8709082/d82b7d46-2af4-11e5-816d-5a963beb3093.png)

**Comment by LisaGee** [comment]
Who should accept this story? Not sure what should be tested here?

**Comment by ErieMeyer** [comment]
:us:
