### ISSUE TITLE
we need access to logs on all our environments

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#1255]
URLs changed recently, we need to either fix the docs or fix the URLs:  https://github.com/18F/college-choice-data/blob/master/doc/LIVE.md

**Comment by ultrasaurus** [comment]
-> @ozzyjohnson to fix URLs or tell us what they are, @hollyallen should review when this is figured out

**Comment by ozzyjohnson** [comment]
All set, links checked / fixed. The old reference to the service proxy scripts could explain a load of problems.

**Comment by hollyallen** [comment]
@ozzyjohnson I'm not sure what you mean when you say the links are fixed. When I go to https://github.com/18F/college-choice-data/blob/master/doc/LIVE.md and click on the Production Logs link near the top, I get this message: "404 Not Found: Requested route ('ed-production-elk-kibana.18f.gov') does not exist."

**Comment by hollyallen** [comment]
Thank you Ozzy, I see the new links in that file.
