### ISSUE TITLE
BUG: In Location search by State, alphabetize by full state name rather than state abbreviation

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1283]

**Comment by justinleveck** [comment]
Can you include a screenshot of what you are seeing.. looks OK to me .. perhaps this dropdown was recently updated to list states by full-name VS abbreviation so it is no longer an issue:

![screen shot 2015-09-16 at 5 45 41 pm](https://cloud.githubusercontent.com/assets/2327754/9922249/093ba85c-5c9b-11e5-9620-6a4837f5e9d4.png)

**Comment by barkimedes** [comment]
Moving to accept--it is fixed when I run it locally, but not in production. So no code change is required, it just needs to be deployed and verified.

**Comment by barkimedes** [comment]
Done! Working on staging.
