### ISSUE TITLE
Rounding down instead of up

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#1285]
https://collegescorecard.ed.gov/school/?173258-Carleton-College

1. Percentage Earning Above High School Grad  67% of students

API: 
•	greater_than_25000: 0.67729085683822

**Comment by justinleveck** [comment]
:hammer:

**Comment by justinleveck** [comment]
@claremccann  I was **NOT** able to replicate this by adding the following to `picc.js`. Also I do not believe the API is still returning back this value `0.67729085683822` for `fields.EARNINGS_GT_25K` but rather `.67181468009948` which would account for why this shows up as `67%` vs `68%`

![screen shot 2015-09-16 at 5 15 19 pm](https://cloud.githubusercontent.com/assets/2327754/9921796/92f27512-5c96-11e5-89b9-075958d15bbd.png)

![screen shot 2015-09-16 at 5 16 00 pm](https://cloud.githubusercontent.com/assets/2327754/9921811/a5ec8888-5c96-11e5-8593-efd6fb9636d1.png)

**Comment by justinleveck** [comment]
@shawnbot Looks like this can be closed
