### ISSUE TITLE
Is average salary adjusted by cost of living? 

### ISSUE THREAD

**Issue by jackiekazil** [18F/college-choice#1286]
For example, if one school has an average salary of 50k and the majority of the graduates live in a major city, another another school has the same average, but the majority of the graduates live mid-sized cities (ie 100k people), then $50k != $50k, because in the city you are more likely to get a higher salary, because of high cost of living. So, the first $50k might be more like $40k when adjusted.

**Comment by barkimedes** [comment]
@LisaGee, do you know the answer to this question (or can you point us in the direction of someone else who may)? Thanks!!

**Comment by saintsoup52** [comment]
There is no regional or annual adjusting of the salary.

ED gives Treasury a list of names and information for each school and Treasury spits back an average salary.

While most schools only have one location, the larger for profit chains have campuses across the country that get rolled up into a single average.

**Comment by barkimedes** [comment]
@jackiekazil Hopefully this answers your question. If you would like more information or have more feedback, please feel free to reopen this issue or create a new one. Thanks!

**Comment by jackiekazil** [comment]
@barkimedes, et al... thank you for the feedback. Sad to hear that it can't be broken down this way. Hopefully the data is improved in the future to compare apples to apples.
