### ISSUE TITLE
College lists hard to read on FB mobile

### ISSUE THREAD

**Issue by ondrae** [18F/college-choice#1287]
#### Description 
Found this on Facebook today. Well done. The college lists are kind of hard to read on Facebook mobile though. It's hard to tell what data are with what college. 

#### Screenshot 
![image](https://cloud.githubusercontent.com/assets/595778/9833638/24b5eba6-5953-11e5-97b9-8b0ac885a2df.jpg)

#### Suggestion
To make each row more separated you could:
* Add a horizontal rule
* Alternate shaded backgrounds
* Increase spacing between rows

**Comment by wslack** [comment]
It looks like this issue is referencing this blog post linked from the scorecard homepage: http://www.ed.gov/blog/2015/09/schools-with-high-graduation-rates-low-costs/

**Comment by ondrae** [comment]
Oh whoops. So many tabs open about the project I thought I this was still your new tool. My apologies.
