### ISSUE TITLE
If I go to ed.gov and search for scorecard, the top results should be collegescorecard.ed.gov

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1297]
http://findit.ed.gov/search?utf8=%E2%9C%93&affiliate=ed.gov&query=scorecard

at the moment the previous version of the scorecard ranks among the top results
College Scorecard
www.collegecost.ed.gov/scorecard/
College Scorecards in the U.S. Department of Education’s College Affordability and Transparency Center make it easier for you to search for a college ...

**Comment by barkimedes** [comment]
@LisaGee Just tried it out. Totally is :) Closing this issue :us:
