### ISSUE TITLE
BUG: Desktop and Mobile Home: The "more" in the By the Numbers section should be regular, not bold

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#130]
Compare staging site:

![image](https://cloud.githubusercontent.com/assets/12192706/8657741/62375d72-296d-11e5-9eec-1d205b462238.png)

To design comp:

![image](https://cloud.githubusercontent.com/assets/12192706/8657752/6a312080-296d-11e5-8264-be4aed9fae5c.png)

The "more" should be 28px regular.

**Comment by meiqimichelle** [comment]
This should be fixed when #148 merges.

![screenshot 2015-07-15 22 12 46](https://cloud.githubusercontent.com/assets/4827522/8715961/d181f2a0-2b3e-11e5-9e0f-cc656e7ab7d6.png)

**Comment by LisaGee** [comment]
Sure looks like it's fixed to me. 
@jjoteal Can you confirm and close?
