### ISSUE TITLE
BUG: Form label text above major should just reference majors and NOT degrees

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#131]
![image](https://cloud.githubusercontent.com/assets/12192706/8657784/b91313ac-296d-11e5-8cb8-43d06b6494ce.png)

Since the first field in this section is ONLY related to majors/programs (e.g. biology, nursing, physics, etc.) and NOT degrees (bachelors, associates, certificate), the form label text should just say "Specify a major" (or other equivalent text) to make it clear that this is where they search for programs of study and NOT degrees.

**Comment by LisaGee** [comment]
I'm not exactly sure where this ticket was originally referencing. If it is the Search on the HP and on the Search Results Page, this is complete from a visual design perspective. There is still an implementation issue open, #401
