### ISSUE TITLE
not seeing stack traces in New Relic

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#1316]
here's an example (which of course, you need to be logged in to see):  https://rpm.newrelic.com/accounts/1065766/applications/8349766/traced_errors/82d841-f88327c8-5af5-11e5-8d1d-b82a72d2466d?original_error_id=82d841-8d172023-5af5-11e5-8d1d-b82a72d2466d

**Comment by barkimedes** [comment]
@hollyallen How does one such as myself get access to new relic? :smile:

**Comment by hollyallen** [comment]
@ozzyjohnson can get you an account.

**Comment by ozzyjohnson** [comment]
@hollyallen @barkimedes - This is true, just need an email to invite.

**Comment by hollyallen** [comment]
Taking it to email with you two.

**Comment by yozlet** [comment]
Here's a stack trace: https://rpm.newrelic.com/accounts/1065766/applications/8349766/filterable_errors#/show/bb3200-71be2c76-b051-11e5-9286-b82a72d2466d/stack_trace?top_facet=transactionUiName&primary_facet=error.class&_k=ua6bcs

OK to close?

**Comment by ultrasaurus** [comment]
confirmed that we're seeing stack traces now.  Will move to accept in case @barkimedes or @LisaGee want to see for yourselves.

**Comment by barkimedes** [comment]
Sweet! I clicked around and some some stack traces too, so LGTM :us:
