### ISSUE TITLE
API_KEY_UNAUTHORIZED

### ISSUE THREAD

**Issue by justinleveck** [18F/college-choice#1319]
I am receiving the following error message when attempting to access the TEST api to work on one of the open issues. Please advice on how I can get my api_key to be authorized.

![screen_shot_2015-09-14_at_11_52_48_am](https://cloud.githubusercontent.com/assets/2327754/9858771/68d578da-5ad7-11e5-9a2e-c06c35cd5955.jpg)

**Comment by dnesting** [comment]
Hi Justin, we don't have a public test API endpoint.  What kind of testing would you like to do against it?  Can you use the regular production endpoint?

**Comment by justinleveck** [comment]
That worked. I ended up adding the following lines to my `zshrc` file and running `source ~/.zshrc`

```
export API_KEY="xxxxxxxx"
export API_BASE_URL="https://api.data.gov/ed/collegescorecard/v1/"
```
