### ISSUE TITLE
As a user of CollegeScorecard.ed.gov within the ed internal network or vpn, I would like to resolve collegescorecard.ed.gov

### ISSUE THREAD

**Issue by hollyallen** [18F/college-choice#1337]
Per @LisaGee :
* If any user is on the ED internal network, either by being plugged in at the office or using Aventail VPN, they cannot access collegescorecard.ed.gov.
* They get this error:  This webpage is not available. ERR_NAME_NOT_RESOLVED. The server at collegescorecard.ed.gov can't be found, because the DNS lookup failed.
* This happens regardless of the browser the user is on.
* If the user, on the same computer and browser, uses a different network (even Ed_Guest, ED’s wifi), the site works fine.
* When I try to ping collegescorecard.ed.gov from the internal ED network, I get the error: Ping request could not find host collegescorecard.ed.gov. Please check the name and try again.
* I am successfully able to ping google.com and 208.67.222.222 and, generally am able to browse the web.

@NoahKunin

**Comment by LisaGee** [comment]
Fixed.
