### ISSUE TITLE
Using Open Data Stack Exchange....

### ISSUE THREAD

**Issue by jalbertbowden** [18F/college-choice#1343]
pretty cool you are driving people to od se, was very pleased to see that. on that note, here's a few thoughts/ideas/issues:

the encouragement assumes that users are familiar with se and this has not been the case for much of the activity. i'm not sure what the right approach here is, perhaps explaining more/directing them to wiki, etc. people having their questions/answers closed/downvoted for not following rules is primary here. they're going to have a bad experience and most likely not come back. secondary is the annoyance within the community of having to clean it all up. se provides a strong platform to crowd source answers, but it shouldn't be the primary source, especially for a government entity. own your data. own your content.

creating a tag (collegescorecard) that doesn't exist is bad practice. whose to say it will be relevant in the future? this particular tag is branding, which isn't necessarily bad, but in this case it is. what happens when college scorecard renames itself? or ceases to exist? college/higher ed/university/etc are much more appropriate. simply using the education tag is ideal to me. also, the new users have no idea what that tag means, or how to tag in general (again, this should be explained to them). back to the non-existent tag creation: when i clicked from the data page to od se, there was nothing there, because no one had ever used that tag before. not helpful at all to a non-user.

tag creation should be followed by tag wiki creation. after coming to the empty questions page, i clicked through to the wiki to see the definition and it was blank. again, to non-users this is a sub-optimal ux.

on branding, the site is open data stack exchange, not stack exchange, and open data se has its beta logo, differentiating it from other se sites.
i cloned the repo to make the easy fix only to see your using font awesome, which doesn't have any se logos except for se. adding the correct logo img and markup is easy, but since it won't be applying the same techniques implemented, i'm not sure the pull request will be accepted.

on that note, font icons are the flavor of the month for sure, but they do have accessibility issues. there is no fall back font in the @font-face declaration, nor is there an aria-required="true" attribute/value implemented on the i element. very simple fixes...i didn't implement them because i'm hoping you'll use the correct logo and title, which will make this paragraph m00t. for this case. ya'll should totally be doing this across the board though. accessibility is critical on the web, but especially for gov sites because in many cases there is nowhere else for the user to go, but the gov site.

lastly, it would be greatly beneficial for the gov department that is going to be monitoring od se to be briefed about using se, much like the new users intro, only a little more in-depth. 

all in all, great job. seriously. 
lets just nail down some guidelines for the next time this happens to make it much smoother for everyone involved.

**Comment by LisaGee** [comment]
@ErieMeyer Can you take a look at the feedback above?

**Comment by ErieMeyer** [comment]
@jalbertbowden Thank you for your feedback, and sorry for my delay! Lots of great points and ideas -- we'll take a look at your PR as well.

Our priority is definitely getting questions answered as quickly as possible by an expert on the data, and we're super pleased that Brian (from Ed) has been able to answer all of them, and on a platform where lots of folks are already looking for help on open data.

Thanks again!
