### ISSUE TITLE
As a consumer, I would like to compare the key metrics of my top schools side by side so that I can easily see which school is the better fit for me

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1352]

**Comment by LisaGee** [comment]
@jjoteal Can you formulate this as a Story? Trying to make sure we're accounting for context or background of why this may be a request at the moment. Did you hear a request for this from students?

**Comment by jjoteal** [comment]
Done. Yes, this specific request came up during our in-person usability test sessions with high school students in October. They would like the ability to "save" schools and then compare them side-by-side -- especially the key metrics.

**Comment by LisaGee** [comment]
Duplicate of #285?
