### ISSUE TITLE
As a consumer, I would like to select and copy the text contained in the tooltips so that I can paste it in a document or email for my own purposes

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#1354]

**Comment by LisaGee** [comment]
@jjoteal - What's the use case here? Can you formulate this as a Story? As a xxx, I would like to copy text from a tooltip, so that I can yyy

**Comment by jjoteal** [comment]
Done. This request came in via email. Added to the queue so we wouldn't lose track of it. IMHO I don't feel as though this is a priority as this has not been a common user request AND it would likely only be used on desktop.
