### ISSUE TITLE
Map markers block location name

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#1358]
https://collegescorecard.ed.gov/school/?178411-Missouri-University-of-Science-and-Technology
Chrome

Can't see Rolla; can only see much smaller town, Saint James.

![image](https://cloud.githubusercontent.com/assets/13874735/10644482/ee872f50-77f6-11e5-83c0-f309aee6647d.png)

**Comment by LisaGee** [comment]
This could be fixed in one of 2 ways:
#97 which would hopefully enable the tip to point to the location and not smack dab be on top of the location/name.
#231 In the infrequent situation where the name is blocked, if the user could pan the map, that would help.

**Comment by LisaGee** [comment]
Closing in favor of #97
