### ISSUE TITLE
as a beta tester, if I attempt to access the site with http, I should be re-directed to https

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#136]

**Comment by LisaGee** [comment]
Acceptance Criteria: make sure that when hit the http version of the URL, I end up at at https

**Comment by LisaGee** [comment]
Not sure if this should apply just to production or to all environments, like Staging.
Staging doesn't seem to redirect to https and I don't have the password required to test Production.

**Comment by LisaGee** [comment]
Doesn't work on Federalist. Moving back to be worked on. Is required for release.

**Comment by diego-** [comment]
(for beta)

**Comment by ultrasaurus** [comment]
@lisag test with https://college-choice.18f.gov/
if you need the name/password, text me (same as it used to be)

**Comment by ErieMeyer** [comment]
Pinged for password and then will accept.

**Comment by LisaGee** [comment]
Worked for me. Accepting.
