### ISSUE TITLE
As a student, I would like to know that not all schools are represented in the tool, so that I understand the current limitations of the tool and that there are additional schools that I could consider.

### ISSUE THREAD

**Issue by barkimedes** [18F/college-choice#1374]
For example, we don't currently show predominantly certificate schools (which is something that students should definitely be looking at!), so it would be good to have some way of letting students know that this isn't a complete set of schools.
- [ ] What would the words read? (@ErieMeyer)
- [ ] Need visual design of where this message could be? (@jjoteal)

**Comment by barkimedes** [comment]
If #951 is completed, we may not have to do this one, right?

**Comment by claremccann** [comment]
Yes, we're looking for an interim solution to #951 with this one.

**Comment by LisaGee** [comment]
Working on #951
