### ISSUE TITLE
Error with localdev set up with Open Data Maker instructions

### ISSUE THREAD

**Issue by onceuponatimeforever** [18F/college-choice#1399]
With elastic search running, `padrino start` produced the following error:

https://gist.github.com/5e84fbd67440b34b4106

**Comment by onceuponatimeforever** [comment]
Closing this issue because I figured out how to get localdev to work by following https://github.com/18F/open-data-maker/blob/dev/INSTALL.md. I can modify this repo's `README.md` to be clearer in terms of setting up a separate local Open Data Maker github repo.

**Comment by afeld** [comment]
Documentation improvements would be more than welcome, thanks!

**Comment by onceuponatimeforever** [comment]
https://github.com/18F/college-choice/pull/1398
