### ISSUE TITLE
404 earlier today, now it's fine...

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#1409]
reported at 7:55AM PT, failed with Safari iPhone browser, later in the day it worked fine, same phone, same browser

![image](https://cloud.githubusercontent.com/assets/41906/12076551/49569950-b165-11e5-9f0a-5f254f6fcd29.png)

**Comment by dnesting** [comment]
This URL gives different results between reloads:
https://ccapi-production.18f.gov/v1/schools/?sort=2011.earnings.6_yrs_after_entry.percent_greater_than_25000%3Adesc&school.operating=1&2013.student.size__range=0..&school.name=Booyah&school.degrees_awarded.predominant__range=2..3&fields=id%2Cschool.name%2Cschool.city%2Cschool.state%2C2013.student.size%2Cschool.ownership%2Cschool.degrees_awarded.predominant%2C2013.cost.avg_net_price.overall%2C2013.completion.rate_suppressed.overall%2C2011.earnings.10_yrs_after_entry.median%2C2011.earnings.6_yrs_after_entry.percent_greater_than_25000%2Cschool.under_investigation

Probably a subset of the instances is delivering bad results while another subset is giving good results.  A `cf app` shows some instances not like the others:

```
#0   running   2015-12-22 11:26:39 AM   0.2%   2.2G of 2.5G     138.2M of 1G
#1   running   2016-01-04 07:25:40 PM   0.1%   463.7M of 2.5G   138.2M of 1G
#2   running   2016-01-05 01:17:51 PM   0.1%   382.9M of 2.5G   138.2M of 1G
#3   running   2016-01-01 12:08:12 AM   0.1%   476.2M of 2.5G   138.2M of 1G
#4   running   2015-12-22 11:36:49 AM   0.3%   2.4G of 2.5G     138.2M of 1G
```

Instances 1 2 3 show a far lower memory usage profile than instances 0 4 and they were started somewhat recently.  Probably those are the culprits and taking them out of load might be a reasonable experiment.

**Comment by dlapiduz** [comment]
One thing that might be interesting in this discussion is that app instances seem to be running out of ram, crashing and restarting:

```
✗ cf events ccapi-production
Getting events for app ccapi-production in org ed / space production as diego.lapiduz@gsa.gov...

time                          event       actor              description   
2016-01-05T13:22:17.00-0600   app.crash   ccapi-production   index: 4, reason: CRASHED, exit_description: out of memory, exit_status: 0   
2016-01-05T12:17:28.00-0600   app.crash   ccapi-production   index: 2, reason: CRASHED, exit_description: out of memory, exit_status: 0   
2016-01-04T18:25:18.00-0600   app.crash   ccapi-production   index: 1, reason: CRASHED, exit_description: out of memory, exit_status: 0   
2015-12-31T23:07:52.00-0600   app.crash   ccapi-production   index: 3, reason: CRASHED, exit_description: out of memory, exit_status: 0   
```

That is why you see different start times on each app.

That said, at the end of the day each app instance should return the same result regardless of the RAM. Could it be that there is some state being stored locally that can affect the output?

**Comment by yozlet** [comment]
@ultrasaurus and I dived into the app initialisation code and think we've found it: when the app starts up, it tries to pull its `data.yaml` config from S3. But if that fails for some reason, the app carries on regardless:

```ruby
      if file.nil? and not ENV['ALLOW_MISSING_YML']
        logger.warn "No data.y?ml found; using default options"
      end
```

Sure enough...

```
December 31st 2015, 21:08:11.638	message:188 <14>1 2016-01-01T05:08:11.63802+00:00 loggregator a6b2b60a-9dec-44c0-a274-222731c285ae [App/3] - - W, [2016-01-01T05:08:11.637962 #29] WARN -- : No data.y?ml found; using default options @version:1 @timestamp:December 31st 2015, 21:08:11.638 host:10.10.2.110 type:syslog tags:_grokparsefailure syslog_severity_code:5 syslog_facility_code:1 syslog_facility:user-level syslog_severity:notice _id:AVH7lgU0mUrT2Me9khwo _type:syslog _index:logstash-2016.01.01
```

This is this instance:

```
#3   running   2015-12-31 09:08:12 PM   0.1%   476.3M of 2.5G   138.2M of 1G
```

... which Sarah is now restarting.

**Comment by yozlet** [comment]
... so I suspect this was a (probably intermittent) failure to load the config from S3, and the app should be terminating in such circumstances.

**Comment by dnesting** [comment]
Nice catch.  Yeah, the ALLOW_MISSING_YML implies it will be disallowed if this is false, when in fact it just emits a warning.  A few retries might be reasonable here before aborting, provided all of this initialization happens before the instance starts accepting connections.

**Comment by yozlet** [comment]
Also, in this case, it's the one app in the set **not** apparently having RAM usage growing with age - because it's not serving proper queries. We clearly have a memory leak, but it's a separate issue.

**Comment by yozlet** [comment]
Uh oh. Looks like this is less intermittent than I hoped - it's happening for all new instances? https://ed-production-elk-kibana-proxy.18f.gov/#/discover?_g=(refreshInterval:(display:Off,pause:!f,section:0,value:0),time:(from:now-90d,mode:quick,to:now))&_a=(columns:!(_source),index:'logstash-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'message:%20%22no%20data.y%3Fml%20found%22')),sort:!('@timestamp',desc))

**Comment by yozlet** [comment]
Ah - I think this is a manifestation of https://github.com/18F/open-data-maker/issues/250 . So we're deleting a load of snapshot files from the `ed-college-choice-production` bucket before we restart the app.

**Comment by yozlet** [comment]
OK, we believe this is sorted now. Deleted the `backups/indices/` folder from the S3 bucket, which had 10,000 files in it. After restarting the apps, they seem to be running fine. @ultrasaurus is working on a fix for https://github.com/18F/open-data-maker/issues/250 .
