### ISSUE TITLE
Investigate why we didn't get automated alerts for #1409

### ISSUE THREAD

**Issue by yozlet** [18F/college-choice#1410]
In theory, Pingdom and/or New Relic should have alerted us (via Slack and possibly email) about #1409. But they didn't. Why not? And how can we fix that? 

- [x] NewRelic
- [ ] Pingdom

**Comment by ultrasaurus** [comment]
@yozlet is this a dup now?

**Comment by yozlet** [comment]
I haven't yet got access to Pingdom, mainly because there is no official 18F setup for it. I think basic Pingdom coverage is something that Ozzy set up but didn't have alerting anyone else, or alerting anywhere visible. That's my best guess as to why we didn't see alerts from it.

For the foreseeable future we're going to use New Relic for both availability monitoring and error tracking, rendering Pingdom redundant. So I'm going to close this.
