### ISSUE TITLE
searchData test fails locally (excluded from ci)

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#1415]
I think this is a known issue but I couldn't find a bug on it 
```
Agriculture, Agriculture Operations, and Related Sciences result count is incorrect. Expected: 492 Actual: 539
running chrome
AssertionError: Agriculture, Agriculture Operations, and Related Sciences result count is incorrect. Expected: 492 Actual: 539
    at Context.<anonymous> (test/spec/searchData.js:82:14)
    at next (native)
    at onFulfilled (node_modules/webdriverio/node_modules/co/index.js:65:19)
```

**Comment by LisaGee** [comment]
When we search for schools with the program Agriculture...., the test thought there should be 492, The code returned 539. this is before making any code changes to include certificate schools.

**Comment by barkimedes** [comment]
This is fixed now. The test data has been updated with new numbers with the addition of predominantly certificate schools. This was resolved as part of that effort. :us:
