### ISSUE TITLE
As a journalist, I want to gain some context as to what this data website is about so that I know if I should spend time exploring the site

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#143]
Reference comps:

Desktop

![image](https://cloud.githubusercontent.com/assets/12192706/8702093/a6f179f8-2ae3-11e5-92f5-8c90f4601944.png)

Mobile:
![image](https://cloud.githubusercontent.com/assets/12192706/8702098/af7b7006-2ae3-11e5-8df2-f739198e95ce.png)

**Comment by meiqimichelle** [comment]
Desktop is done. Mobile is no longer part of the MVP.

**Comment by LisaGee** [comment]
I see the text Clare gave us. Accepting.
