### ISSUE TITLE
Turn off beta server

### ISSUE THREAD

**Issue by abisker** [18F/college-choice#1442]

**Comment by sharms** [comment]
The following files need to be updated:
- [ ] make_sitemap.rb:8 references ccapi-prod
- [ ] README.md:41 references ccapi-prod

**Comment by yozlet** [comment]
See linked PR above for fixing the docs.

@sharms can you clear up the remaining resources linked from the `beta` services?
 - [ ] `ed-college-choice-prod` S3 bucket
 - [ ] ES on `10.10.3.101:32784` (is that provisioned solely for `beta`, or used by others?

Once that's done, it's just a matter of deleting the apps and the space, right?

**Comment by abisker** [comment]
@barkimedes We mentioned de-prioritizing this one for now as it's a "do before transition, but not critical at this very moment" item; Are you okay to move this to backlog (and place in proper priority order)?

**Comment by abisker** [comment]
@barkimedes circling back to this one, you okay for me to move this to the backlog?

**Comment by LisaGee** [comment]
@Eriemeyer - can you be sure to note in this ticket, if you haven't already, that you've reached out to the Beta Developers to let them know that we turning off the beta servers? Thanks.

**Comment by ErieMeyer** [comment]
Oh hi! I have reached out to the beta developers about turning this off, and everyone is good to go.

**Comment by abisker** [comment]
@sharms, per direction from @barkimedes let's go ahead and turn this off (assuming it's under 1 hour of work). Is this something you can get to today?

**Comment by sharms** [comment]
Beta space and services have been removed
