### ISSUE TITLE
P0 - Site search not functioning 

### ISSUE THREAD

**Issue by abisker** [18F/college-choice#1473]
Site is live, but search is returning an Internal Server Error.

Errors began at 1 PM EST

@yozlet and @sharms troubleshooting.

**Comment by abisker** [comment]
Following escalation path procedures, tagging @devops-staff here (@sharms currently troubleshooting though) @dlapiduz @NoahKunin @jezhumble

**Comment by sharms** [comment]
@yozlet identified the eservice was not correctly bound on 2/3 instances which had multiple root causes, including ELS server resources and previous troubleshooting moving eservice to eservice.current

@sharms migrated 3x ELS instance to 6x ELS instance taking the place of the original eservice, which after restaging resolved the binding issue and performance issues

**Comment by LisaGee** [comment]
Thanks, @yozlet and @sharms
