### ISSUE TITLE
As a site operator, I would like to stop getting unimportant NewRelic notifications

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#1485]
We're getting notifications almost every day that are for minor, and we think easy-to-fix issues:  https://github.com/18F/open-data-maker/issues?q=is%3Aissue+is%3Aopen+label%3A%22from+New+Relic%22

**Comment by ultrasaurus** [comment]
https://github.com/18F/open-data-maker/pull/286

**Comment by yozlet** [comment]
@ultrasaurus Is this on staging now? Move to Accept?

**Comment by ultrasaurus** [comment]
This has been deployed & there were no alerts over the long weekend, so am closing!
