### ISSUE TITLE
Share file upload link and update the data on the site.

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#1492]
As noted to @LisaGee and @ErieMeyer the other day, we'll be sending over the latest files soon to update the site before the next annual upload. Can 18F send us an upload link to use?

**Comment by abisker** [comment]
@barkimedes, per our discussion with @ultrasaurus today at standup, #1489 (getting the S3 bucket sorted out) will need to be part of this process.

**Comment by LisaGee** [comment]
Sorry I had to miss standup.

Looks like ED plans to have the data file ready to transfer to us on Friday. Can we use the same methodology we have used previously? Thanks.

**Comment by barkimedes** [comment]
Oh! I didn't realize it would be so soon. 

@abisker In that case, let's just go ahead and have someone at 18f update the data this round and we'll figure out the permission issues and transition stuff later.

I think we still need #1359 and #1360 done to go with this though.

@LisaGee for context, in standup yesterday we talked about having me update the data (as a non-18f person just to see if I could make it through the process clearly based on documentation as a transition item. But when talking about it, we found that we have to work out some permission issues, so that's why #1489 was linked).

**Comment by abisker** [comment]
@ultrasaurus does it make sense for you to upload this new data on Friday, or is a Friday afternoon update of this nature not preferable?

**Comment by LisaGee** [comment]
Thanks @barkimedes for the context.

Alex - ED wants to upload the data to 18F - basically just transfer the data to us as it's big and we need a mechanism. I don't think we should update the data on production until the following week.

**Comment by abisker** [comment]
Ah got it, thanks @LisaGee. Will plan to update to production next week then.

**Comment by brian9** [comment]
Updated data files are ready, can transfer as soon as upload link is ready

**Comment by abisker** [comment]
Thanks @brian9 - @ultrasaurus can you prepare the upload link?

**Comment by brian9** [comment]
The updated files include an new data element (column BNN) for accreditation status, should the uploaded files exclude this new data element? We are expecting this data element to be used in the future and helpful in the API, but wanted to make sure it wasn't problematic to change the structure of the underlying files now. Please advise if this new column should be removed prior to uploading.

**Comment by brian9** [comment]
Actually, never mind. Please ignore the prior post, moving forward with data files consistent with the format of the very first version. Sorry for any confusion this may have caused. Files are ready to go without any new columns.

**Comment by ultrasaurus** [comment]
@brian9 so what is new about the data?  we'll need to spot check it once it has arrived and been re-indexed.

**Comment by claremccann** [comment]
Just emailed Sabrina about this, will loop you in, thanks!

**Comment by ultrasaurus** [comment]
ran into encoding issues, waiting on new data drop

**Comment by abisker** [comment]
@ultrasaurus moving this to in-progress now that we're indexing.
