### ISSUE TITLE
As a developer, I would like to see API docs

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#15]
API Doc options
* swagger - Shawn & Sarah have experience with this but mixed feelings
* https://apiblueprint.org/
* https://github.com/danielgtaylor/aglio
* see [this post](http://apievangelist.com/2014/03/08/hello-world-product-api-with-blueprint-raml-and-swagger/) for a comparison between API Blueprint, Swagger and RAML

**Comment by jjoteal** [comment]
Please use http://cfpb.github.io/api/hmda/ as the reference site for the page layout for the various sections of the API documentation.

**Comment by LisaGee** [comment]
Think we need to determine best way to MVP this.
@ErieMeyer can you take a crack?

**Comment by LisaGee** [comment]
Example API calls from ticket #170 
examples (as live links, and the resulting json response), maybe we some more narrative.

one school, one year:
http://ccapi-prod.18f.gov/school?ope_id=00143400&year=2012

same school showing just three fields for all years
http://ccapi-prod.18f.gov/school?ope_id=00143400&fields=year,admission_rate,name

list the names & sizes of all historically black schools (in 2013)
http://ccapi-prod.18f.gov/school?minority_serving.historically_black=1&fields=name,size&year=2013

you can get the value of a specific nested field like this:
http://ccapi-prod.18f.gov/school?name=American&fields=name,size,minority_serving.historically_black&year=2013

**Comment by ErieMeyer** [comment]
Draft is up here in staging: https://federalist.18f.gov/preview/18F/college-choice/staging/data/documentation/
