### ISSUE TITLE
BUG:Most Popular Programs used to display as %s

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#1516]
Mac, Chrome

Steps to Repro:
1. Navigate to: https://federalist.18f.gov/preview/18F/college-choice/staging/school/?131520-Howard-University
2. Expand the Academic Programs section and see numbers like 0.1705 and 0.1542. See attached screenshot.

Expected behavior:
These should be shown as percentages, as they previously were.

![screen shot 2016-03-09 at 12 22 32 pm](https://cloud.githubusercontent.com/assets/12847090/13644083/ea73e11a-e5f1-11e5-82c2-3bb92c9470da.png)

**Comment by barkimedes** [comment]
Fixed on staging :usa:
