### ISSUE TITLE
As a journalist, I want to get high-level insights about the data so that I can decide if I want to explore it further

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#157]
Desktop comp reference:
![image](https://cloud.githubusercontent.com/assets/12192706/8752031/64abfac6-2c7f-11e5-855a-0aa54cca9679.png)

Mobile comp reference:
![image](https://cloud.githubusercontent.com/assets/12192706/8752036/6c6d6998-2c7f-11e5-8d16-e493ebd4ad4d.png)

**Comment by meiqimichelle** [comment]
This is live on `dev` for desktop.

**Comment by LisaGee** [comment]
Works for me! Accepted.
