### ISSUE TITLE
Erie translating institution page data into English

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#16]
The fields are in this doc!
https://docs.google.com/document/d/1o2sI2psyRxkSt3griDj6BoOQ08R0bkfBRQ_fAhhaPOU/edit

Please have by EOD Monday 6/22.

@ErieMeyer

**Comment by ErieMeyer** [comment]
@jjoteal -- was this the page that we did together in Lisa's office? Is this still outstanding?

**Comment by jjoteal** [comment]
@ErieMeyer I'm sure there will be more content tweaking work once we finalize some decisions, etc. Closing this issue for now though so we can create separate issues once those new requests come up.
