### ISSUE TITLE
As a developer, I'd like to get immediate access to the API documentation via the homepage, so I can begin to understand how the API works.

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#161]
Desktop reference comp:
![image](https://cloud.githubusercontent.com/assets/12192706/8752301/3414c3be-2c81-11e5-878b-9b9b8c919f7b.png)

Mobile reference comp:
![image](https://cloud.githubusercontent.com/assets/12192706/8752307/3c32d4fa-2c81-11e5-81db-c098a5f32b01.png)

**Comment by LisaGee** [comment]
@diego- and @jjoteal Let's figure out the MVP for launch.

**Comment by LisaGee** [comment]
I think this is done, so moved to accept. @diego- please pull back, if it's not ready for acceptance.

**Comment by LisaGee** [comment]
Tested link from HP in right column and top nav. Accepting.
