### ISSUE TITLE
As a journalist, I want to obtain a full list of insights about the data so that I can get a full picture of what Ed thinks is important about the data

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#162]
Desktop reference comp:
![image](https://cloud.githubusercontent.com/assets/12192706/8752394/b446a8ae-2c81-11e5-9164-554fc9a160ce.png)

Mobile reference comp:

![image](https://cloud.githubusercontent.com/assets/12192706/8752398/b8bc4e34-2c81-11e5-86f9-b817768cedcb.png)

**Comment by LisaGee** [comment]
Post-launch, as folks can read the policy paper to extract.

**Comment by barkimedes** [comment]
@jjoteal  https://collegescorecard.ed.gov/data/ already has a...dare I call it a carousel??...for Data Insights. Does that mean this story is done? Can we close it?!
