### ISSUE TITLE
As a journalist, from the Data Insights page, I want quick access to FAQs about the data as well as links to download the full Technical Paper and Policy Paper so that I can easily obtain the detailed information whenever I'm done reading the highlights

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#163]
Desktop reference comp:

![image](https://cloud.githubusercontent.com/assets/12192706/8752462/34f2b86c-2c82-11e5-809a-bc35173a4598.png)

Mobile reference comp:
![image](https://cloud.githubusercontent.com/assets/12192706/8752470/3a54e5f0-2c82-11e5-99f0-8d0625382b9e.png)

**Comment by LisaGee** [comment]
Here is the text for the blurbs on the 2 papers from Clare's email 7/28/15:

Policy Paper: This report shares an overview of the Administration’s College Scorecard project; highlights institutional examples for each of the metrics included on the site; and explores the data technicalities and other ongoing challenges associated with the project. 
 
Technical Paper: This paper, written by the Council of Economic Advisers, explores theories of action considered throughout the college ratings project, provides a technical understanding of the data produced and analyzed for its purposes, and offers detailed analysis of the new data published on the [technical page] of this site.

**Comment by LisaGee** [comment]
I don't think we'll have a Data Insights page for launch.
