### ISSUE TITLE
As a developer, from the "Explore the Data" page, I want to get a snapshot view of what is included in the data set so that I can know what I'm getting before I attempt to download the data. I would also like quick access to download all of the data immediately if I want to so I can have instant access.

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#164]
Desktop reference comp:
![image](https://cloud.githubusercontent.com/assets/12192706/8752519/83b75020-2c82-11e5-9f75-50027eb63c10.png)

Mobile reference comp:
![image](https://cloud.githubusercontent.com/assets/12192706/8752535/9d0faf72-2c82-11e5-8eed-22a455a6fec4.png)

**Comment by LisaGee** [comment]
@diego- Can you help figure out the MVP for Launch?

**Comment by LisaGee** [comment]
MVP is done.
