### ISSUE TITLE
As a developer or journalist, from the Explore the Data and Data Details pages, I want quick access to FAQs about the data, links to download the full Technical Paper and Policy Paper, and high level insights about the data so that I can easily obtain detailed information about the data I'm downloading to understand it better

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#168]
Desktop reference comp:
![image](https://cloud.githubusercontent.com/assets/12192706/8752722/30e7853e-2c84-11e5-864f-8834e601d060.png)
(Note: Yellow highlights in the Data Insights section are missing from the desktop version, so please follow the mobile version styles for this) 

Mobile reference comp:
![image](https://cloud.githubusercontent.com/assets/12192706/8752726/385744d0-2c84-11e5-843a-948068740ab6.png)

**Comment by LisaGee** [comment]
I think this page may need to be re-evaluated based on timing and functionality we have available.
