### ISSUE TITLE
As a Researcher, I'd like to pull both Repayment Rate and Default Rate from the data so that I can compare and contrast different measures in similar veins.

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#176]
We don't have the Default Rate data available at the moment.

**Comment by hollyallen** [comment]
This is currently in Blocked, would it make more sense to put it into the Icebox? @lisagee and @barkimedes

**Comment by claremccann** [comment]
We now have default rates in the data file.

**Comment by hollyallen** [comment]
Fantastic! So this can be prioritized in the general backlog it sounds like.

**Comment by LisaGee** [comment]
Thanks, @claremccann - In the data set that is live and publicly available today? If so, we can actually, close the ticket, cause then it's done. yay, yippee.

**Comment by claremccann** [comment]
Yes we added before launch, it's live

**Comment by LisaGee** [comment]
Great. Thanks. Closing.
