### ISSUE TITLE
As a Developer, I'd like to be able to get RepaymentRatesSuppressedForSize() data but constricted based on potential volatility, so that it is more resilient to changes at small schools that are not an accurate reflection.

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#184]
I'd like to make a function call:
RepaymentRatesSuppressedForSize()

Inputs:
* School: All or IndividualSchool (referred to in any way specified in issue #221)
* Student Characteristic: All, Completers, NonCompleters, LowIncome, MedIncome, HighIncome, Dependent, Independent, Pell, NoPell, Female, Male, FirstGen, NotFirstGen
* Timeframe: 3yr

Outputs:
* RepaymentRate
* NumInCohort

**Comment by ultrasaurus** [comment]
Need column name(s) or row ranges for Student Characteristic, timeframes, repayment rate and numInCohort

**Comment by ultrasaurus** [comment]
RepaymentRatesSuppressedForSize?unitid=12345&student_type= low_income&timeframe=3yr

**Comment by LisaGee** [comment]
Return value is a json blob

**Comment by ultrasaurus** [comment]
example API:  http://ccapi-open-staging.cf.18f.us/school?name=note

**Comment by LisaGee** [comment]
This data can be found in columns 1902-1915 in the Data Dictionary doc.

Sarah -- Can you confirm that this is enough detail for you to understand to which data I'm referring? Thanks.

**Comment by ultrasaurus** [comment]
That looks lke the 3 year repayment rates. Need similar ranges for 1yr, 5yr, 7yr

**Comment by LisaGee** [comment]
Yes. Sorry. I cloned a previous issue and didn't remove some of the data points. RepaymentRateSuppressedForSize() is only available at 3 years, not at any other timeframe.

**Comment by diego-** [comment]
added variable names for columns 1902-1915:

6_yrs_after_entry.independent_students
6_yrs_after_entry.female_students
6_yrs_after_entry.male_students
6_yrs_after_entry.greater_than_25000
6_yrs_after_entry.mean_earnings.lowest_tercile
6_yrs_after_entry.mean_earnings.middle_tercile
6_yrs_after_entry.mean_earnings.highest_tercile
6_yrs_after_entry.mean_earnings.dependent_students.lowest_tercile
6_yrs_after_entry.mean_earnings.dependent_students
6_yrs_after_entry.mean_earnings.independent_students
6_yrs_after_entry.mean_earnings.female_students
6_yrs_after_entry.mean_earnings.male_students
7_yrs_after_entry.not_working_not_enrolled
7_yrs_after_entry.working_not_enrolled

Not sure these are the same as above though. Will keep looking.

**Comment by ultrasaurus** [comment]
@LisaGee need to resolve this -- is this story description correct or should we look at different columns?

**Comment by diego-** [comment]
see 1937-1950

**Comment by ultrasaurus** [comment]
3year repayment rate column names are:
```
RPY_3YR_RT_SUPP
LO_INC_RPY_3YR_RT_SUPP
MD_INC_RPY_3YR_RT_SUPP
HI_INC_RPY_3YR_RT_SUPP
COMPL_RPY_3YR_RT_SUPP
NONCOM_RPY_3YR_RT_SUPP
DEP_RPY_3YR_RT_SUPP
IND_RPY_3YR_RT_SUPP
PELL_RPY_3YR_RT_SUPP
NOPELL_RPY_3YR_RT_SUPP
FEMALE_RPY_3YR_RT_SUPP
MALE_RPY_3YR_RT_SUPP
FIRSTGEN_RPY_3YR_RT_SUPP
NOTFIRSTGEN_RPY_3YR_RT_SUPP
```

**Comment by LisaGee** [comment]
What row number in dictionary is the num in cohort?

**Comment by ultrasaurus** [comment]
number of students is in:
```
RPY_3YR_N
COMPL_RPY_3YR_N
NONCOM_RPY_3YR_N
LO_INC_RPY_3YR_N
MD_INC_RPY_3YR_N
HI_INC_RPY_3YR_N
DEP_RPY_3YR_N
IND_RPY_3YR_N
PELL_RPY_3YR_N
NOPELL_RPY_3YR_N
FEMALE_RPY_3YR_N
MALE_RPY_3YR_N
FIRSTGEN_RPY_3YR_N
NOTFIRSTGEN_RPY_3YR_N
```

**Comment by LisaGee** [comment]
Would this be called for one year or all years?

**Comment by ultrasaurus** [comment]
I will write the query

**Comment by ultrasaurus** [comment]
Single School, All Students, all years:
https://ccapi-prod.18f.gov/school?id=162061&fields=RPY_3YR_RT_SUPP,RPY_3YR_N,year

All Schools, All Students, 2013
https://ccapi-prod.18f.gov/school?year=2013&fields=name,RPY_3YR_RT_SUPP,RPY_3YR_N

**Comment by LisaGee** [comment]
@diego- Can you confirm? If good, please close. Thanks.
