### ISSUE TITLE
As a Developer, I'd like to make an API call to find out the CompletionRate() at any given school or all schools, so that I don't have to understand the difference between what metric I need for a 4 year school vs for a 2 year school

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#185]
CompletionRate()

Inputs:
* School: All or ID
* Year: 1996-current

Outputs:
* CompletionRate
* NumInCohort

**Comment by ultrasaurus** [comment]
Questions:
* do we want to expose all three IDs in the API?
* what columns do we use to figure this out?

**Comment by LisaGee** [comment]
I think we likely want to expose all 3 IDs. In fact, I think we probably need to create a function that given one of Name, OPEID6, OPEID, or UNITID, returns the other 3.

**Comment by LisaGee** [comment]
I do know the column IDs. Will add to the story.

**Comment by LisaGee** [comment]
If PREDEG==3 (aka 4 year school), completion rate is in C150_4.
If PREDDEG==2 (aka 2 year school), completion rate is in C200_L4
Will file another ticket for:
1. schools of other PREDDEG values
2. metrics used in Consumer Tool - C150_4_POOLED_SUPP and C200_L4_POOLED_SUPP

**Comment by LisaGee** [comment]
@ultrasaurus Feels like may be another dupe. Can you confirm to make sure not missing any subtleties? Thanks.

**Comment by ultrasaurus** [comment]
@LisaGee looks like a dup to me too, will close
