### ISSUE TITLE
As a Developer, I'd like to be able to get Outcome() data so that I can integrate it into my app, for example to create a chart that shows trends over time

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#186]
Outcome()

Inputs:
* School: All or ID
* Year: 1996-current
* Student Characteristic: All, Completers, NonCompleters, LowIncome, MedIncome, HighIncome, Dependent, Independent, Pell, NoPell, Female, Male, FirstGen, NotFirstGen
* Timeframe (aka YearsFromEntry): 2yrs, 3yrs, 4yrs, 6yrs, 8yrs
* Outcome: All, Died, Completed, Withdrawn, Enrolled, Unknown
* TransferStatus: OriginalInst, TransferedTo2yr, TransferedTo4yr

Outputs:
* Quantity
* NumInCohort

**Comment by ultrasaurus** [comment]
need column names and/or row numbers for inputs and outputs

**Comment by LisaGee** [comment]
From Data Dictionary, row #s:
471-1380

**Comment by ultrasaurus** [comment]
completion rate by year: https://ccapi-prod.18f.gov/school?id=155937&fields=id,name,C150_4,year

**Comment by LisaGee** [comment]
@diego- Can you confirm? If good, please Close. Thanks.
