### ISSUE TITLE
Different visual options for tuition vs. net price

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#19]
Would be helpful to have a few options on how we might display visually the pricing data.

Meaning -- how can we show tuition and explain that it's a sticker price vs. net price average to explain that that's what people usually actually pay.

A few super sketchy directions would be really helpful!

**Comment by jjoteal** [comment]
@ErieMeyer just going through my assigned tickets and want to see if the most recent design of the Institution page addressed this: https://github.com/18F/college-choice/issues/95

If so, we can close this ticket I think.

**Comment by ErieMeyer** [comment]
Yes! Addressed. Thanks!
