### ISSUE TITLE
As a school, I want to post a response to the data to add context to any anomalies 

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#200]
@LisaGee -- adding this here to track what the eventual URL extension (/DataResponse etc.) will be for schools.

This is a related story to this one: https://github.com/18F/college-choice/issues/199

**Comment by LisaGee** [comment]
Perfect. Thanks.

**Comment by ErieMeyer** [comment]
Based on this: https://github.com/18F/college-choice/issues/118#issuecomment-130802448

I think this should be school.edu/CollegeScorecard

Sound good?

**Comment by ErieMeyer** [comment]
Assigning this to Lisa since I submitted it :)

**Comment by LisaGee** [comment]
Correct.
