### ISSUE TITLE
As a Consumer, I want to be able to share an individual institution page via email with my friends, family, and advisors so I can get their feedback and reactions.

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#201]
As a Consumer, I want to be able to share an individual institution page via social media and email with my friends, family, and advisors so I can get their feedback and reactions.

**Comment by jjoteal** [comment]
For the MVP, this should simply be a mailto: link

**Comment by meiqimichelle** [comment]
- [ ] HTML/CSS
- [ ] implement - @meiqimichelle to chat with @shawnbot

**Comment by meiqimichelle** [comment]
On results page:
Put the share button in the upper right in a row above the "51 results" + sort. So in other words, it would push the "51 results" + sort down a bit.

On indiv schools page:
See mock. Share button lives on upper right above the map.

**Comment by ErieMeyer** [comment]
Subject: Check this out

Body:

I found this on scorecard.ed.gov -- check it out: [link URL]

**Comment by meiqimichelle** [comment]
@shawnbot This does not seem to be working on the individual school pages. Seems good on the results page though!
