### ISSUE TITLE
As a Consumer, I want to be able to share my search results via social media and email with my friends, family, and advisors so I can get their feedback and reactions.

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#202]
As a Consumer, I want to be able to share my search results via social media and email with my friends, family, and advisors so I can get their feedback and reactions.

**Comment by diego-** [comment]
duplicate of 201

**Comment by jjoteal** [comment]
For the MVP, this should simply be a mailto: link

**Comment by LisaGee** [comment]
as @diego- said. dupe of 201. Closing
