### ISSUE TITLE
As the department of education, I want analytics in order to know how well the consumer tools are working to meet our goals

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#204]
[Placeholder for more detail around analytics for the consumer tool]

**Comment by jackiekazil** [comment]
:+1: <-- so I can watch this issue. :-D

**Comment by LisaGee** [comment]
We should determine what additional analytics we would like to see.

**Comment by LisaGee** [comment]
I think we're all set at the moment.
