### ISSUE TITLE
Content style guide

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#22]
So! I did some digging and no one has a public, central content style guide.

But! Data.gov had one (that's built on top of GDS's one), so I did a PR on the central style guide work (which is mostly visual right now) to include a portion on content, using the basis of the data.gov style guide. I think they're into it!

We should know more tomorrow. Here is the PR, and the specific text: https://github.com/18F/govt-wide-patternlibrary/pull/66/files

**Comment by barkimedes** [comment]
@ErieMeyer Assigning this to you. So do I understand this correctly that since https://pages.18f.gov/content-guide exists, we should be able to close this issue? :us:

**Comment by ErieMeyer** [comment]
Yes! I love it.
