### ISSUE TITLE
As a Developer, I'd like to be able to find out all the ways to reference a school, so that I can marry schools across different data sets that may use different kinds of IDs to reference schools

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#221]
Given one of Name, OPEID6, OPEID, or UNITID, this function should return the other 3.

**Comment by ultrasaurus** [comment]
the API is working:  http://ccapi-prod.18f.gov/school?ope_id=00143400&fields=unit_id,ope6_id

however, there's an issue with unit_id not getting indexed -- probably BOM (Byte Order Mark) at beginning of file (@shownbot worked around issue with some of the data earlier)

**Comment by ultrasaurus** [comment]
It was faster to just write a bash script to modify the files, rather than create a general purpose thing on the server, so this bug is still outstanding:  https://github.com/18F/open-data-maker/issues/81
 I tested staging with new data files and it worked fine.  Just need to re-index all of the files to see it on production.  

Here's the API to test:
http://ccapi-staging.18f.gov/school?unit_id=118693&year=2013&fields=ope_id,ope6_id

**Comment by ultrasaurus** [comment]
Now on production:  https://ccapi-prod.18f.gov/school?unit_id=118693&year=2013&fields=ope_id,ope6_id

**Comment by saintsoup52** [comment]
Random question about this... are you guys also including schools with 8-digit unitIDs (IPEDS)?

For example Ivy Tech Community College-Bloomington (unitid=15098713) is a sub-campus of Ivy Tech Community College (unitid=150987).

**Comment by LisaGee** [comment]
I believe that the data se we received has the OPEID-8 identifiers in the column labeled OPEID.
My understanding is that is what those numbers are. Please shout if you think they might not be.

**Comment by ultrasaurus** [comment]
@LisaGee right now we're not filtering the data at all, so we include ALL the schools on this list.  My understanding is that we want to show 2 & 4 year schools, but I don't think there's a story for that.  Not sure how we find the "main" campus if we don't want to show all of them.

FYI: working on a change which uses Diego's work proposing developer friendly names and it does appear to be the 8-digit OPE ID.  
![image](https://cloud.githubusercontent.com/assets/41906/9028196/fac38860-3924-11e5-84da-5680ab82d905.png)

**Comment by saintsoup52** [comment]
I would be very surprised if the 8-digit OPE ID is the main identifier a user utilizes to find a campus in a search. There way too many campuses with 8-digit OPE IDs to be manageable (~50,000).

Usually, students think of unitIDs (or IPEDS codes) as a campus.... however, now that there are 6 digit and 8-digit IPEDS IDs that becomes a little more complicated.

How many schools are are on your list right now? If...
~5,000 = 6-digit OPE ID
~7,500 = IPEDS ID
~50,000 = 8-digit OPE ID

**Comment by LisaGee** [comment]
@diego- Can you help confirm this story? If it's good to go, please Close. Thanks.
