### ISSUE TITLE
On some desktop widths, search result sidebar has bits that get cropped and others float outside its bounds

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#226]
![image](https://cloud.githubusercontent.com/assets/41906/8883982/e3e6e028-324a-11e5-9d7d-c2c2b1bb9a43.png)

**Comment by meiqimichelle** [comment]
Related to #340, but we should test specifically for this bug so I'm not closing.

**Comment by LisaGee** [comment]
There is still a teeny bit of funkiness when the window is super, super narrow. but I'm going to accept it. Only way to solve, I think would be to set a minimum window size.

![image](https://cloud.githubusercontent.com/assets/12847090/9699896/462d7f7c-53bf-11e5-99f7-77561dc6a995.png)
