### ISSUE TITLE
avg. cost/yr & avg. net size are same data

### ISSUE THREAD

**Issue by diego-** [18F/college-choice#232]
Represents the same data. These should have the same label (avg. cost per year)

**Comment by diego-** [comment]
per sprint demo walk-through, july 24, 2015

**Comment by LisaGee** [comment]
@diego- Not sure I'm following. Could you point me to where you are seeing the 2 labels?
on its face cost and size seem like diff metrics, but may not be looking in the right place. Thanks.

**Comment by barkimedes** [comment]
@diego- I can't find what you might have been referring to. Can you provide more information? Since this is a fairly old issue, is this something that is no longer an issue and we can close it?

**Comment by diego-** [comment]
this is an old issue and can be closed!

**Comment by barkimedes** [comment]
:us:
