### ISSUE TITLE
The Paying For College box on the School Detail page should be at the bottom of the Financial Aid and Debt section, even on Mobile

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#242]
We should provide the data we want the student to see above sending them to external links.

**Comment by LisaGee** [comment]
Related to #104

**Comment by meiqimichelle** [comment]
I'm not sure what this means. It is in 4-develop right now.

**Comment by ErieMeyer** [comment]
this has been addressed elsewhere!
