### ISSUE TITLE
as a consumer, when I visit the production website with HTTP, I am automatically redirected to HTTPS

### ISSUE THREAD

**Issue by diego-** [18F/college-choice#245]
this cover the production implementation, including generating of CSR's once final domain is chosen.

**Comment by ultrasaurus** [comment]
In order to do this we need:
- a domain
- domain delegation
- SSL cert

**Comment by LisaGee** [comment]
Update:
1. We have a domain. check.
2. Confirmed Domain Delegation on track. David and Adrian from OCIO will re-confirm have everything that is needed by tomorrow. CAB meeting to approve occurs Thursday 10:30am ET. We have to tell them   what time and date we want this switch to be made. Let's confer on this offline.
3. Re: SSL Cert - OCIO said it would be easiest if 18F buys the Cert and they, as hostmaster, will confirm. @ozzyjohnson is that doable? What are the next steps for us here?
