### ISSUE TITLE
As a PICC team member, I want to know the MVP for the beta testers

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#247]
For me:

- Data dictionary draft
- CSV draft

**Comment by LisaGee** [comment]
For beta, developer needs:
1. Signed an NDA
2. overview of the project and the data types (data dictionary)
3. API key
4. Taking a look at the data and seeing if there is something they want to build on top of.
5. Functional API

**Comment by LisaGee** [comment]
I feel like this is done. Closing.
