### ISSUE TITLE
As a developer, I'd like to see human-readable names for data columns in CSV or API formats

### ISSUE THREAD

**Issue by diego-** [18F/college-choice#250]
c

**Comment by diego-** [comment]
is this a blocker for the beta test? how much documentation do we need to develop for the beta?

**Comment by LisaGee** [comment]
@diego- Doesn't seem like a blocker since the Beta is well underway. What's the status of this ticket?

**Comment by LisaGee** [comment]
Assigning to @diego- for Acceptance. If it's all good, please close the ticket.
