### ISSUE TITLE
As a picc product team member, I should be able to look at  new changes on a staging server

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#257]
need to set up staging environment

**Comment by ultrasaurus** [comment]
I set up a staging environment on http://ccapi-staging.18f.gov/
I'm just keeping 3 years of data there now 2011-13, so it is quick to re-index.  Right now I'm really using this as a dev environment... once we have real users, we'll need to set that up.

**Comment by ErieMeyer** [comment]
Hi Sarah! Remind me the username again? I remember the password :)

**Comment by LisaGee** [comment]
I see changes in Staging. Accepted.
