### ISSUE TITLE
As a developer or journalist, I want to be able to navigate the website by a menu bar so that I can easily find my way around the site.

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#263]
Desktop comp reference:
![image](https://cloud.githubusercontent.com/assets/12192706/8983734/a68cafe2-369a-11e5-8076-1c9532786446.png)

Mobile comp reference:
![image](https://cloud.githubusercontent.com/assets/12192706/8983742/b5894ee2-369a-11e5-8a6d-10b38ca454cd.png)

![image](https://cloud.githubusercontent.com/assets/12192706/8983748/c20b8216-369a-11e5-9a46-12fe29d6d228.png)

**Comment by meiqimichelle** [comment]
Desktop is done. Mobile no longer part of MVP.

**Comment by jjoteal** [comment]
Looks good, closing!
