### ISSUE TITLE
As a developer or journalist I want a way to engage with other developers and journalists so that I can ask questions, get input, etc.

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#264]
Desktop reference comp:
![image](https://cloud.githubusercontent.com/assets/12192706/8983870/a6dbce00-369b-11e5-9989-8715b5f706b2.png)

**Comment by jjoteal** [comment]
TO-DOS from spreadsheet:
Implement StackExchange
a. incorporate link into website (https://opendata.stackexchange.com/questions/tagged/xxxx)
b. choose tag we want them to use. (#NSLDS, #CollegeChoice, #CollegeScorecard)
c. Have an owner assigned (Clare)

**Comment by LisaGee** [comment]
@jjoteal - Does this need a design without the Twitter handle? If not, can you move into Backlog and re-assign to Michelle? Thanks

**Comment by meiqimichelle** [comment]
Twitter will be gone when #942 merges. It looks like:
![screen shot 2015-08-31 at 12 54 06 pm](https://cloud.githubusercontent.com/assets/4827522/9588915/d80becd2-4fdf-11e5-8a80-c69aa66aefe6.png)

**Comment by jjoteal** [comment]
Looking good - closing!
