### ISSUE TITLE
BUG: Consumer Tool: In search results, simply display the name of the school, city and state, and X,XXX students

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#270]
Old display:
![image](https://cloud.githubusercontent.com/assets/12192706/9016819/044fc558-37a2-11e5-9adf-09092306e4fa.png)

Should be updated to:

![image](https://cloud.githubusercontent.com/assets/12192706/9016780/a20cc828-37a1-11e5-973d-8d8148edcada.png)

**Comment by LisaGee** [comment]
@jjoteal I believe this has been implemented. I think that's what I'm seeing on Staging. Can you confirm and if so, close the ticket?

**Comment by ErieMeyer** [comment]
Just to confirm, we are including the word "undergraduate" (lisa just confirmed IRL), and it looks great on staging. Ex:
![screen shot 2015-08-24 at 3 26 40 pm](https://cloud.githubusercontent.com/assets/1626026/9450108/a9509ae8-4a74-11e5-967e-7556803fad7b.png)
