### ISSUE TITLE
As a beta developer, I have rudimentary access to API examples/documentation

### ISSUE THREAD

**Issue by diego-** [18F/college-choice#276]
For the beta, it is sufficient to give the following examples (as live links, and the resulting json response), maybe we some more narrative.

one school, one year:
http://ccapi-prod.18f.gov/school?ope_id=00143400&year=2012

same school showing just three fields for all years
http://ccapi-prod.18f.gov/school?ope_id=00143400&fields=year,admission_rate,name

list the names & sizes of all historically black schools (in 2013)
http://ccapi-prod.18f.gov/school?minority_serving.historically_black=1&fields=name,size&year=2013

you can get the value of a specific nested field like this:
http://ccapi-prod.18f.gov/school?name=American&fields=name,size,minority_serving.historically_black&year=2013

**Comment by diego-** [comment]
on nonpublic (not on website) form, like a google doc or word doc.

**Comment by diego-** [comment]
implement an example function call for ticket #183:

one school, get 3 year repayment rate (suppressed) for low income cohort, and 3 year repayment rate overall (in 2012)

http://ccapi-prod.18f.gov/school?ope_id=00143400&year=2012&fields=3_yr_repayment_suppressed.income.low_income,3_yr_repayment.overall

**Comment by LisaGee** [comment]
@diego- Is this done?

**Comment by diego-** [comment]
Closing, this was done.
