### ISSUE TITLE
On the Consumer Tool simple search, change "Major/Degree" to "Programs" and just have a single dropdown menu for "Select Program" that contains the full list of programs

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#281]

**Comment by jjoteal** [comment]
@LisaGee wondering if the wording here should be "Area of Study" rather than "Programs"? I'm wondering if "Programs" would have too much 'baggage' -- i.e. Would some users connote "programs" with "degree type" (Bachelors, Associates, etc.)? Just a suggestion...

**Comment by LisaGee** [comment]
I like it. Sold. Areas of Study it is! Thanks!

**Comment by LisaGee** [comment]
Accepted the Visual Design change that this story represents. There is another ticket open, b/c what is in the drop down is incorrect. SEe #401
