### ISSUE TITLE
BUG: Individual School Page > Student Body: Possible to have Gender still display as a pie chart since there are only 2 criteria (male, female)

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#291]

**Comment by jjoteal** [comment]
Also, would it still be possible to use pink (#fbaff3) for female and blue (#88b6fa) for male? The green and purple in the graphs already have very specific meanings on the site (green = costs, purple = graduation rate)

**Comment by LisaGee** [comment]
may not have the data for this and may remove altogether

**Comment by barkimedes** [comment]
@jjoteal or @LisaGee I don't see gender on individual school pages. That still a thing or was it removed?

**Comment by LisaGee** [comment]
We didn't have the data to implement this. Closing.
