### ISSUE TITLE
BUG: Individual School page > Costs Section. Change labels above Family Income/Average Price labels to be all-caps so that they are distinguishable from the data 

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#296]
![image](https://cloud.githubusercontent.com/assets/12192706/9046429/8f784b5c-39f8-11e5-9b65-9d07a007c23e.png)

Put "Family Income" and "Average Price" in all-caps. Please note that you may have to reduce the font size so that it fits.

**Comment by meiqimichelle** [comment]
Looks like:

![screen shot 2015-09-05 at 4 09 48 pm](https://cloud.githubusercontent.com/assets/4827522/9701667/9e3f5e78-53e8-11e5-81b9-44ad87ad09e5.png)

**Comment by jjoteal** [comment]
Sorry, could you also put them in bold? Might mean you have to reduce the size as well to fit that then.

**Comment by ErieMeyer** [comment]
Looks good on dev!

**Comment by ErieMeyer** [comment]
:us:
