### ISSUE TITLE
BUG: Individual School Page > Earnings Section. Change label "Average Salary After Leaving School" to "Salary 10 Years After Leaving School" 

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#297]
![image](https://cloud.githubusercontent.com/assets/12192706/9046472/db1a588e-39f8-11e5-9696-c13ea345258b.png)

Change label "Average Salary After Leaving School" to "Salary 10 Years After Leaving School"

**Comment by LisaGee** [comment]
This is subsumed by #423
