### ISSUE TITLE
BUG: Individual School Page > Earnings section. Change label "Former Students Earning Less than $25K" to "Former Students Earning More than $25K 6 Years After Leaving School"

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#299]
![image](https://cloud.githubusercontent.com/assets/12192706/9046513/1daaab86-39f9-11e5-98ff-93920e31d76f.png)

Change label "Former Students Earning Less than $25K" to "Former Students Earning More than $25K 6 Years After Leaving School"

**Comment by ErieMeyer** [comment]
This may fix this: https://github.com/18F/college-choice/pull/302

**Comment by LisaGee** [comment]
this was subsume by #423
