### ISSUE TITLE
BUG: Individual School Page > Costs section. Change label "Average Net Price" to "Average Actual Cost"

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#300]
![image](https://cloud.githubusercontent.com/assets/12192706/9046580/9157fd22-39f9-11e5-936d-b22a6dc614c6.png)

Change label "Average Net Price" to "Average Actual Cost"

**Comment by ErieMeyer** [comment]
I think I fixed this (need a pull request review) https://github.com/18F/college-choice/issues/300

**Comment by LisaGee** [comment]
At the moment, it actually says Average Cost Per Year, which seems right. Closing.
