### ISSUE TITLE
BUG: Value Snapshot (on Search Results + Individual School page). Change labels "Average Cost Per Year" to "Average Actual Cost" and change "Average Salary" to "Salary 10 Years After Leaving School"

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#301]
![image](https://cloud.githubusercontent.com/assets/12192706/9046618/dccc6b1c-39f9-11e5-8afe-2310f254fa27.png)

Change labels "Average Cost Per Year" to "Average Actual Cost" and change "Average Salary" to "Salary 10 Years After Leaving School"

**Comment by LisaGee** [comment]
@jjoteal Let's do some usability testing with students to see what words resonate the best with them.

**Comment by jjoteal** [comment]
@lisa -- these labels have since been updated to reflect Dana's language changes. I'm going to close this issue in lieu of Ed's review of the content so we can start tracking all new language tickets so things don't get confused.
