### ISSUE TITLE
BUG: Individual School Page > Value Snapshot section. On mobile view, the value snapshot graphics should display side-by-side (not stacked)

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#303]
CORRECT DISPLAY:
![image](https://cloud.githubusercontent.com/assets/12192706/9046706/a47fe68e-39fa-11e5-9567-6d7a11d9d9bd.png)

**Comment by meiqimichelle** [comment]
Note: there is also now some weirdness happening with the meter sizes at certain screen widths. Observe:
![screen shot 2015-09-01 at 8 44 51 pm](https://cloud.githubusercontent.com/assets/4827522/9622623/53db4bae-50ea-11e5-809e-67df7cb617e0.png)

**Comment by barkimedes** [comment]
@jjoteal It looks like it is supposed to on my Nexus 6. Is it still looking not good on other devices? If so, which device(s) is this reproducible on?

**Comment by jjoteal** [comment]
@barkimedes this is displaying correctly on my iphone 5 now (which is a small screen). I think we can close this one out. Doing so!
