### ISSUE TITLE
As a Consumer, I want to view "key facts" on the homepage so that I can more informed about the factors I should be considering when examining schools

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#315]
Mobile reference comp:
![image](https://cloud.githubusercontent.com/assets/12192706/9063794/4d987456-3a97-11e5-83fa-3019465ea5d8.png)

Desktop reference comp:
![image](https://cloud.githubusercontent.com/assets/12192706/9063799/54b5f650-3a97-11e5-96fd-084e9d41fc14.png)

**Comment by LisaGee** [comment]
@meiqimichelle We should discuss best way forward (or not) on this.

**Comment by meiqimichelle** [comment]
@LisaGee Do we have data for this? Or, say, at least a few facts to put on the homepage?

**Comment by LisaGee** [comment]
@jjoteal has them in her hands and @ErieMeyer was reviewing, so we definitely have some to put on the HP. The question for me is how to/if we can tackle the Listing page that shows them all together.

**Comment by meiqimichelle** [comment]
Great! HP should not be a problem. As for the listing page, definitely not for beta, but we can see about launch. I should tag up with @ErieMeyer and see what the factoids ended up looking like, and how varied the content turned out to be. That will inform how complicated making the listing page will be.

**Comment by LisaGee** [comment]
@meiqimichelle Let's all discuss, b/c perhaps we can just defer this whole page. Let's easy for the Lists of Schools, but could try instead to tweak it so link refers them to a search query instead of a listing page. Actually... Kind of like that idea and seems emminently doable. Hmmmm. Adding to the other story.

**Comment by meiqimichelle** [comment]
This is what it looks like with content
![screen shot 2015-08-26 at 12 53 09 pm](https://cloud.githubusercontent.com/assets/4827522/9504471/a2bfd15c-4bf1-11e5-934c-387eccfc69d8.png)

@jjoteal

**Comment by meiqimichelle** [comment]
@jjoteal Here are words from @ErieMeyer:

- College graduates, on average, earn $1 million more over their lifetimes than high school graduates.
- You could be eligible to get up to $5,775 in federal grants—no repayment needed—to help pay for college
- 60 percent of college graduates started college at age 24 or older.

You might want to adjust the design now that we know what those look like.

**Comment by jjoteal** [comment]
@meiqimichelle here's a design comp of the adjusted design:

![image](https://cloud.githubusercontent.com/assets/12192706/9527999/6157f990-4cc0-11e5-811c-fcb73f5dfce3.png)

Please ping me on slack if you want specific font sizes.

Please note that I'll need Angel to create a different illustration for the first fact. Now that I know the content, we can create a graphic that better speaks to that data point. I will place the raw artwork for the other 2 icons in the PICC folder. 

Also, per your output above, can you double check the font? The dollar symbol in your output is not the same dollar symbol as Montserrat Bold in Photoshop. Could you double check this?

**Comment by jjoteal** [comment]
@meiqimichelle -- updated the design mock-up with some wording changes on the "infographics" per Lisa's request. Please use this wording!

![image](https://cloud.githubusercontent.com/assets/12192706/9532426/a40ee8f2-4cd9-11e5-8574-d0e2695ceb98.png)

**Comment by meiqimichelle** [comment]
Here's the latest:

![screen shot 2015-08-27 at 5 35 37 pm](https://cloud.githubusercontent.com/assets/4827522/9536552/0df73faa-4ce2-11e5-9f7b-3d2ae8055231.png)

As for the dollar sign, web font versions of typefaces often don't include nice versions of special characters. I tried to see if the one you're seeing is an available alternate and didn't come up with anything. For now, I suggest we bug-issue it and come back to it later. It is displaying as expected as per [Google fonts](https://www.google.com/fonts/specimen/Montserrat).

**Comment by LisaGee** [comment]
@jjoteal @meiqimichelle is this ticket for the Key Facts/By The Numbers on the HP? Or is it for the More Key Facts Listing page? The description puts it at the later, but the discussion makes me think it is for the former. Are there 2 different tickets? The former is a p1, the latter is a p3. Just want to make sure there is no confusion especially during testing. Thanks.

**Comment by meiqimichelle** [comment]
We've been using it to track the homepage lately, tho maybe originally it was supposed to track both. We should make a different ticket for the 'more key facts' listing page and continue to use this for the homepage, which is complete except for the last illustration, on dev.

**Comment by jjoteal** [comment]
I'll change the wording of this ticket to just say show 3 By the Numbers items on the homepage and then I'll create a new ticket for the "more by the numbers" page that is the p3.

**Comment by jjoteal** [comment]
FYI: More "By the Numbers" content issue is https://github.com/18F/college-choice/issues/746.

**Comment by jjoteal** [comment]
@meiqimichelle we have the remaining icon for the first "by the numbers" fact ($1 million). You can find the .svg and .png files in the PICC folder. File name is "money".

Reassigning to you for implementation!

**Comment by meiqimichelle** [comment]
This will be done with #939 merges. Looks like:
![screen shot 2015-08-31 at 11 33 33 am](https://cloud.githubusercontent.com/assets/4827522/9586928/9f20fddc-4fd4-11e5-8fb2-0476f2ed0d2b.png)

**Comment by jjoteal** [comment]
Looks great! I know we have a DISPLAY item for the centering of these graphics on mobile, but closing this ticket since the infographics are in place.
