### ISSUE TITLE
ENHANCEMENT: Use average cumulative federal debt at graduation, removing the data for those who dropped out.

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#318]
from: http://ticas.org/blog/what-should-new-college-comparison-tool-look
Currently, the Administration’s College Scorecard shows the median debt of all former students entering repayment, regardless of whether they graduated or dropped out. This makes colleges with high drop-out rates look like a good deal, because students who left the school after borrowing for only a semester or two bring the median debt level down. For instance, the College Scorecards for the University of Phoenix Online (Phoenix) and University of California at Berkeley (Berkeley) show similar median federal debt for borrowers entering repayment ($17,476 at Phoenix vs. $16,436 at Berkeley). However, only 7% of first-time students seeking a bachelor’s degree at Phoenix graduate in six years, compared to 91% at Berkeley. In fact, undergraduates at Phoenix are more than twice as likely to borrow federal loans as students at Berkeley, and they borrow significantly more on average each year.
Instead of providing debt when entering repayment, we recommend using currently available data for average cumulative federal debt at graduation until more comprehensive data are available. Average debt at graduation should be accompanied by the school’s borrowing rate, so students know how common it is for graduates to have any debt.

**Comment by LisaGee** [comment]
Actually -- I think PICC 1.0 will do this! yay. Closing.

**Comment by saintsoup52** [comment]
Plus one.

They are separate data points... The graduate rate being more helpful for consumers... The other is helpful for researchers.
