### ISSUE TITLE
BUG: Ensure that "Check Out These Schools" and "Paying for College" boxes are equal heights on desktop

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#319]
![image](https://cloud.githubusercontent.com/assets/12192706/9088307/586be400-3b5d-11e5-8816-16b1cfdf05bb.png)

Should be equal heights.

**Comment by LisaGee** [comment]
may be replacing the CFPB box. Don't do any work until that is decided.

**Comment by ErieMeyer** [comment]
Issue is subsumed by https://github.com/18F/college-choice/issues/458
