### ISSUE TITLE
BUG: Spacing incorrect in "Check Out These Schools" box on Desktop

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#320]
Site view:

![image](https://cloud.githubusercontent.com/assets/12192706/9088376/b1cad66e-3b5d-11e5-8a93-8866e9888e24.png)

Design comp: 
![image](https://cloud.githubusercontent.com/assets/12192706/9088387/bc990f02-3b5d-11e5-89ce-182aa5c6493b.png)

Suggested Fixes:
- There should be ~20px inner side margins on the box. The content within the box should spread to fill that space.
- There should be ~30px space below the "Check Out These Schools" title and the top of the horizontal rule of the first item
- There should be ~20px space between the crest icon and the beginning of the text for each line item.
- There should be ~40px top inner margin
- Each of the line items should be links 
- Also confirming that font size for the individual items is 16px

**Comment by Pfhreak** [comment]
Sorry about the churn, should have read more closely that I needed to issue a pull request against the dev branch. #1302 should address your first bullet point, bringing the horizontal padding to ~20px. (21px by my ruler.)

* There should be ~20px inner side margins on the box. The content within the box should spread to fill that space.
 * Addressed by #1302 
* There should be ~30px space below the "Check Out These Schools" title and the top of the horizontal rule of the first item
 * Unaddressed, currently this is ~40px, and the element shares a style with other h1s on the page.
* There should be ~20px space between the crest icon and the beginning of the text for each line item.
 * This seems to have been resolved already, as this is how the page renders for me.
* There should be ~40px top inner margin
 *  This seems to have been resolved already, as this is how the page renders for me.
* Each of the line items should be links
 * This seems to have been resolved already, as this is how the page renders for me.
* Also confirming that font size for the individual items is 16px
 * The text is rendered at font-size:100%, which will use the browser's default (which is 16px, I believe.)
