### ISSUE TITLE
Bug: Spacing issues on "Paying for College" box on Desktop

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#321]
Site view:
![image](https://cloud.githubusercontent.com/assets/12192706/9088593/d16af46c-3b5e-11e5-83a2-b59500e9ee37.png)

Design comp:
![image](https://cloud.githubusercontent.com/assets/12192706/9088608/e525fc86-3b5e-11e5-99d6-1cd0fe2a5dd5.png)

Suggested Fixes:
- There should be ~30px space between bottom of "Paying for College" text and top of CFPB graphic
- There should be ~30px space between the bottom of the description body text and the "Go to the CFPB" link
- There should be ~40px inner top margin on the box

**Comment by LisaGee** [comment]
We may be replacing this box altogether.

**Comment by LisaGee** [comment]
@ErieMeyer Can you review the links that ED wants to put here instead of the CFPB box. If you're ok with them, create that replacement story and kill this one? Thanks.

**Comment by ErieMeyer** [comment]
Will do!

**Comment by ErieMeyer** [comment]
Issue is subsumed by this one: https://github.com/18F/college-choice/issues/458
