### ISSUE TITLE
BUG: + icons on homepage search still not centered on Mac Chrome on Desktop

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#323]
Site:
![image](https://cloud.githubusercontent.com/assets/12192706/9088725/93b21596-3b5f-11e5-9f0e-441ddfd7e198.png)

Design comp:
![image](https://cloud.githubusercontent.com/assets/12192706/9088736/a0d9e0a0-3b5f-11e5-930a-ce1d83611cba.png)

**Comment by LisaGee** [comment]
@jjoteal Do you mean vertically or horizontally centered?
