### ISSUE TITLE
BUG: Unbold information listed under Name of School and kill the 2-year/4-year designation from the display

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#334]
In other words on:

![image](https://cloud.githubusercontent.com/assets/12192706/9098213/678ad444-3b96-11e5-972d-000074b0ff08.png)

- Unbold "Stillwater, OK" and "71,272 undergraduate students"
- I am recommending that we remove the 2-year and 4-year designation from the display as well since we now have an "icon" for those designations and it would be odd for it to display as text on the search results page but then as an "icon" on the individual school page. Recommend keeping the display consistent and therefore would simply remove it from the search results view as it would also keep the cards shorter. @LisaGee let me know if you disagree on this.

**Comment by LisaGee** [comment]
@jjoteal - I think this is done. Can you confirm and close? Thanks.

**Comment by ErieMeyer** [comment]
:+1:
