### ISSUE TITLE
BUG: On Desktop, make sure all the search results "cards" are the same height in the same row

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#335]
Site screenshot:

![image](https://cloud.githubusercontent.com/assets/12192706/9098342/3fcd3900-3b97-11e5-8420-64fa395e1162.png)

All cards should be the same height. That means there would be extra space below "view more details" on the 3rd card in this instance once you make all the cards the same height as the tallest card in this row.

**Comment by LisaGee** [comment]
This is a For Beta feature (needed to be considered Functionally Complete), b/c with the layout as it is now, it is very hard for a consumer to compare schools against each other, which is one of the key goals of this page.

**Comment by meiqimichelle** [comment]
@jjoteal It sounds like @LisaGee would like the meters to always fall in the same place so one can compare across, which is different than the solution that we talked about (filling the 'missing' area at the bottom with white so that the cards are the same height).

@LisaGee is this what you meant?

**Comment by meiqimichelle** [comment]
We talked about this at standup, and we decided to try making the design work for anything with a title that falls on three lines or fewer. However, this is what it looks like In Real Life:

<img width="931" alt="screen shot 2015-08-24 at 8 52 17 pm" src="https://cloud.githubusercontent.com/assets/4827522/9458359/3f329c6e-4aa2-11e5-8739-6f714ca9197c.png">
<img width="931" alt="screen shot 2015-08-24 at 8 52 35 pm" src="https://cloud.githubusercontent.com/assets/4827522/9458362/4194859e-4aa2-11e5-855e-eb5669d614fc.png">

## Mobile
<img width="412" alt="screen shot 2015-08-24 at 8 58 47 pm" src="https://cloud.githubusercontent.com/assets/4827522/9458427/f437ae06-4aa2-11e5-8da4-c0eeb5b2657a.png">

I'm not sure this is a net win for the page. Can we think of any other implementation that could meet our goal of 'easily comparable' ?

**Comment by meiqimichelle** [comment]
Also, if we don't hate the desktop view, I can make the extra space go away for small views since those won't be comparing across rows anyways. So, this issue is mostly about those desktop screenshots I posted.

**Comment by jjoteal** [comment]
@meiqimichelle rather than inserting the space where you did, could you insert space below and above the thin horizontal rules (i.e. the rules that contain the bar graphs) so that the bar charts across the row are always in alignment? Feel free to ping me on slack this AM and we can chat about it if that direction is not clear.

**Comment by meiqimichelle** [comment]
After talking with @jjoteal , we've got a solution ready in #558. Yay.

**Comment by ErieMeyer** [comment]
Looks awesome!

**Comment by ErieMeyer** [comment]
Don't seem to be lining up on staging.

To recreate: Chrome on a mac desktop, search "ohio" in school name, default sort, top three schools.

![screen shot 2015-08-25 at 3 42 58 pm](https://cloud.githubusercontent.com/assets/1626026/9477389/0efe1a52-4b40-11e5-85d9-9a0295fc5c84.png)

**Comment by meiqimichelle** [comment]
@ErieMeyer I don't think that change has merged to staging yet.

**Comment by LisaGee** [comment]
Looking good!
I see these working: 
Pennsylvania State University-Penn State Fayette- Eberly
George C Wallace State Community College-Hanceville

This one wraps to 4 lines still Elizabethtown College School of Continuing and Professional Studies
But I think those are edge cases we can defer. Thanks!
