### ISSUE TITLE
BUG: On Desktop, space between rows of cards should be ~20px (same as spacing between columns of cards)

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#336]
Site screenshot:

![image](https://cloud.githubusercontent.com/assets/12192706/9098396/a8d514cc-3b97-11e5-8ba0-062608e4fdc8.png)

- Should only be ~20px

**Comment by meiqimichelle** [comment]
Live on dev for review via #1335 and thanks to @jfredrickson :smile:

**Comment by barkimedes** [comment]
Removing the accept label because the spacing between rows and columns are not close to equal on the site.

**Comment by meiqimichelle** [comment]
This is ready for acceptance on `dev` , not on the live site. That's why the `accept` label is there -- it needs review before it is pushed live.

**Comment by barkimedes** [comment]
Ooopsie. My mistake. Thanks for correcting!

**Comment by LisaGee** [comment]
My bad. I asked Sabrina to determine the state of all things in Accept.

@holly - We should review how we’re using the Accept label (and others) once we kick off again. I thought we were only putting Accept on, if it was available on Staging for testing, although I think that may have changed in the end game and especially right around launch, whernwe were super cautious about merging anything in case we needed to do any hotfixes….

**Comment by LisaGee** [comment]
Agreed. I think in the end game things got a bit loose, and we should
re-commit as a team to a certain workflow.

On Thu, Oct 22, 2015 at 7:04 AM, Gelobter, Lisa <Lisa.Gelobter@ed.gov>
wrote:

> My bad. I asked Sabrina to determine the state of all things in Accept.
>
>
>
> @holly - We should review how we’re using the Accept label (and others)
> once we kick off again. I thought we were only putting Accept on, if it was
> available on Staging for testing, although I think that may have changed in
> the end game and especially right around launch, whernwe were super
> cautious about merging anything in case we needed to do any hotfixes….
>
>
>
>
>



-- 
Holly Allen
Product Lead | 18F
holly.allen@gsa.gov | 415-917-8421

**Comment by barkimedes** [comment]
:us: works on staging.
