### ISSUE TITLE
ENHANCEMENT: On Desktop, incorporate a subtle shadow around the search box so that as it grows, it is distinguishable from the white background

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#338]
Design comp:

![image](https://cloud.githubusercontent.com/assets/12192706/9113813/8bdf859a-3c24-11e5-9890-46f1c9436105.png)

Photoshop settings if it's helpful:
Outer glow, multiply #666666, 10% opacity, 20px size

**Comment by meiqimichelle** [comment]
This is fixed with #585

**Comment by ErieMeyer** [comment]
Beautiful!
