### ISSUE TITLE
BUG: On desktop view of search results, alter the grid so that we have more room for the filter column

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#339]
Per our phone conversation @meiqimichelle, perhaps we could try:

- Reducing the space between the school cards to ~12px
- Pushing the card row to the far right edge to make the most of the pixels
- Using all those extra pixels to add to the left filter column

Let's see what that does and then I'll take a look!

**Comment by LisaGee** [comment]
not sure if we have time for this before Launch.

**Comment by meiqimichelle** [comment]
This is OBE. We implemented a drawer for the filters instead.
