### ISSUE TITLE
On mobile, allow users to Filter and Modify/Start New Search on Search Results page

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#340]
Mobile comp:
![image](https://cloud.githubusercontent.com/assets/12192706/9116374/1838fa46-3c32-11e5-9cee-84a55f56eea1.png)

Desktop reference:
![image](https://cloud.githubusercontent.com/assets/12192706/9116388/270e1b50-3c32-11e5-8269-3094b000d160.png)

**Comment by LisaGee** [comment]
Jess - I made this a p2. I think this is not an insignificant amount of work and while I agree that it's a Very Nice to Have, I don't think it's a Must Have for Launch. Ok by you or are there other considerations I should be factoring in?

**Comment by LisaGee** [comment]
@jjoteal or maybe I misunderstood. Is this the implementation of filters on mobile. Then, it's a p1.

**Comment by jjoteal** [comment]
@LisaGee this is the desired implementation of the filters on mobile, but in the interest of time, we might not be able to pull it off unless this is prioritized.

This is the "temporary solution" mock that @meiqimichelle and I discussed, if we aren't able to pull off the filter "drawer" for mobile in time:
![image](https://cloud.githubusercontent.com/assets/12192706/9442851/f5d8ce0e-4a4b-11e5-9893-e5c04b0259ee.png)

Perhaps @meiqimichelle could give us a sense if she thinks the desired drawer UI could happen in time for Beta Launch so we can prioritize accordingly?

**Comment by meiqimichelle** [comment]
Let me take a look the the drawer functionality. Assigning to me to investigate.

**Comment by meiqimichelle** [comment]
I'm going to re-name this issue because I'm using it to pull together all the filter/search-on-the-results page issues we've been filing. It is no longer 'enhancement'.

**Comment by meiqimichelle** [comment]
Tasks

- [ ] Fix page width problems (The initial mock was too wide so everything is squished in the live version. I am going to trim padding and change margins to get us in a better place in general)
- [ ] Fix filter display problems (This section was never styled according to mocks. Needs some polish so it is readable)
- [ ] Fix search display problems (Again, this section was never styled for the results page, but rather inherited styles from the homepage. Needs some polish so it is readable.)
- [ ] Solve for two sections, as shown in mock. This should fix the accordion-collapse for our short-term filter solution on mobile.
- [ ] Depending on how ^^ goes, implement drawer. It might end up being the only way to make the search usable on small screen sizes so I'm not sure yet if this is an enhancement that can be delayed, or an essential feature that needs to be implemented.

**Comment by meiqimichelle** [comment]
This should be fixed on `dev` with #712

**Comment by jjoteal** [comment]
Looking good on iphone.
