### ISSUE TITLE
BUG: On Desktop and Mobile on Search Results page change the header text above the Filters and Modify/Start New Search to be "Filter Your Results" and "Modify or Start a New Search"

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#341]
Desktop reference:
![image](https://cloud.githubusercontent.com/assets/12192706/9116828/7309726e-3c34-11e5-8945-177278398125.png)

Mobile reference:
![image](https://cloud.githubusercontent.com/assets/12192706/9116811/55824644-3c34-11e5-8fd6-db2cc49a143c.png)

**Comment by jjoteal** [comment]
Also, please note that the above mobile expand/collapse solution for the Filter and Modify/Start New Search is only temporary. Per my conversation with @meiqimichelle, we eventually would like to implement the drawer solution mentioned here: https://github.com/18F/college-choice/issues/340

**Comment by meiqimichelle** [comment]
I looked into this and would like to wait until Shawn is back. We have to change a few things in our implementation that might affect his filters to do this.

**Comment by LisaGee** [comment]
I think the text can read "Modify Search". Don't think we need the extra "or Start a New".

**Comment by meiqimichelle** [comment]
This should be fixed on dev with #712

**Comment by ErieMeyer** [comment]
Looks great!
