### ISSUE TITLE
BUG: Consumer Tool mobile interface: Lack of side margins on search results

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#342]
Mobile site screenshot from iphone:
![image](https://cloud.githubusercontent.com/assets/12192706/9117092/0f717d26-3c36-11e5-9c3b-016b3258f8da.png)

Should have 20px left and right margins.

**Comment by meiqimichelle** [comment]
@jjoteal Can you check this one again? That part of the site has changed quite a bit since this was filed, and I don't see it on my end right now.

**Comment by jjoteal** [comment]
@meiqimichelle the top part is looking good on iphone, but the "cards" (white rounded corner containers) for the individual schools are still going to the edge:

![image](https://cloud.githubusercontent.com/assets/12192706/9631482/1d4b664a-514f-11e5-81b6-acbd976bc8e0.png)

This is obviously not a major issue and shouldn't delay launch.

Here's a quick screenshot of the original design so you can see how the schools still appear to display in the "cards" on mobile:

![image](https://cloud.githubusercontent.com/assets/12192706/9631496/4b83c976-514f-11e5-8db0-2d275ed11fa7.png)

**Comment by meiqimichelle** [comment]
Ah! I see. I was focusing on the top headers and not the cards themselves. Yes, we'll wait on that one. I would also advocate for reconsidering -- the space for the card edges takes up a lot of mobile screen real estate and would make the meters even smaller than they already are. Perhaps there's an alternate approach that keeps separation without so much edging?

**Comment by meiqimichelle** [comment]
@jjoteal What do you think about this one? Personally, I'd think about tweaking the design, but either way perhaps not urgent for launch anymore?

**Comment by jjoteal** [comment]
I don't think this is urgent for launch. 

Later on down the road, I'd still like to keep things in cards, but perhaps we just reduce the left and right margins a bit (so maybe 10px rather than 20px for example).

**Comment by meiqimichelle** [comment]
Sure! That sounds good.

**Comment by jjoteal** [comment]
Just marking this as DISPLAY just in case we're able to get to this for launch...

**Comment by meiqimichelle** [comment]
Looks like:

![screen shot 2015-09-05 at 3 11 42 pm](https://cloud.githubusercontent.com/assets/4827522/9701491/7a072868-53e0-11e5-9161-baac8f2ead85.png)

**Comment by ErieMeyer** [comment]
Looks great on dev!

**Comment by ErieMeyer** [comment]
:heart_eyes: :us:
