### ISSUE TITLE
Why bar graphs vs. dials? 

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#345]
Per Lisa's request to explain why bar graphs were chosen vs. dials, here is a list of the various reasons:

- In the usability testing we conducted so far, bar graphs beat out dials by a small margin. Users cited that they were easier to read, bolder, and clearer.
- When we eventually build the compare tool, and are able to show let's say the Graduation Rate graphs side-by-side, it will be much easier to tell at a glance what school performs the best in a bar graph vs. a dial -- For example, if School #1 has a graduation rate of 72% and School #2 has a graduation rate of 76% it would be easier to see which one is the better performer at a glance by the height of the bar color vs. fractions of a tilt of a dial pointer.
- With bar graphs, there is a more obvious visual when a school is drastically underperforming. For example, if a school has a very low Graduation Rate, let's say 20%, it will be VERY obvious to the user because there will be a lot of gray on that area of the page (and the user is naturally drawn to areas of color).  That will give them an immediate sense of "Hey, what's wrong here? Did the page not load?" and will cause their eye to immediately be drawn to that 'blank spot' on the page to take a closer look -- which is exactly what we want to happen. We want to give them pause when something looks "wrong". This would not be possible with the dials, as the color remains in tact at all times. 

@saintsoup52

**Comment by saintsoup52** [comment]
I think there is in important shift here in how we are showing what we are showing.

The dials were meant to show relative position of a school's outcome measure (e.g. High or low) versus the bar graphs are better at showing the actual performance (e.g. 85%).

While I concede the bar graphs are probably easier to read... I think there is a lot more value showing how a school sits in the pack then the outcome itself.

For example... A high graduation rate for a two year school is 20-25%... So it would be hard for a user to understand that relatively speaking a 20% grad rate is good.

I think we stick with bar graphs but make sure we do as much as we can to show a school's relative place in the pack.

**Comment by jjoteal** [comment]
Just an update that as we continue to conduct usability tests, the bar graphs are pulling out further and further ahead of the dials. Here's a quote from a recent test:

"It is really easy to read bar graphs…I like bar graphs because they give you the fastest interpretation. They are easier and quicker to read than the dials. The dials remind me of the motor vehicle department. It’s not that I *don’t* like t he dials, I just find the bar graphs easier to read."

**Comment by jjoteal** [comment]
Our bar charts have been designed with the thirds data, so it is clear when a particular metric is below, about, or above average. In addition to the bar charts there are also below, about, and above average indicators below the bar charts on the individual school page.

**Comment by barkimedes** [comment]
@jjoteal I feel like we can close this issue. Can we? :us: :bar_chart:

**Comment by jjoteal** [comment]
Yep, closing out.
