### ISSUE TITLE
As a Consumer or Developer, I'd like to know the URL for the Consumer and Data Tools, so I can access them

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#359]
- [x] Finalize URL(s) for the tool(s)
- [x] If in the format of *.ed.gov, connect Noah with whoever at ED runs DNS for ed.gov
- [x] Slack @ Noah to let him know the email was sent
- [x] @noahkunin creates 18F Route 53 AWS DNS records for *.ed.gov
- [x] ED must create nameserver (NS) records delegating to 18F Route 53 AWS
- [x] 18F will test to confirm correct setup on ED's side.

**Comment by NoahKunin** [comment]
I also need this ASAP to remove launch risk.

**Comment by NoahKunin** [comment]
Updated punch list.

**Comment by LisaGee** [comment]
Final URL decided. See Lisa's email.
Noah has been connected with ED DNS owner and is in the process of making it all so....

**Comment by NoahKunin** [comment]
Woot!

On Tue, Aug 18, 2015 at 9:53 AM, Lisa G. <notifications@github.com> wrote:

> Assigned #359 <https://github.com/18F/college-choice/issues/359> to
> @NoahKunin <https://github.com/NoahKunin>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/18F/college-choice/issues/359#event-385576765>.
>



-- 
Noah Kunin
18F Infrastructure Director | @18F

**Comment by NoahKunin** [comment]
Hm, looking for an email, but can't seem to find it. What's the URL?

**Comment by NoahKunin** [comment]
Resolved!

**Comment by NoahKunin** [comment]
Incremented checklist - now back with ED.

**Comment by LisaGee** [comment]
Have pinged. ED is confirming.

**Comment by hollyallen** [comment]
Status @NoahKunin @LisaGee ?

**Comment by hollyallen** [comment]
We forgot to tell @NoahKunin that the url for his nameservers should be https://collegescorecard.ed.gov (no longer https://collegechoice.ed.gov). He is fixing this on his time now.

**Comment by hollyallen** [comment]
There was a URL miscommunication, Noah is working to get it fixed.

**Comment by NoahKunin** [comment]
Done!
