### ISSUE TITLE
As a consumer, I want to see an individual institution's response to the data that is presented on their institution page so that I can see if the institution wants to provide an explanation to accompany their data

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#361]
Links should look like:
![image](https://cloud.githubusercontent.com/assets/12192706/9175221/7b91f732-3f52-11e5-9445-168f0b703bc7.png)

and be located in the top basic information area, under the special designations

**Comment by LisaGee** [comment]
Dupe of #199
