### ISSUE TITLE
Track and debug Elasticsearch failure

### ISSUE THREAD

**Issue by yozlet** [18F/college-choice#364]
From @ultrasaurus:

> App failed last night without a code change while indexing new data. The app was running fine, but all ES requests were failing.  To resolve, Ozzy restarted ES and restarted the app.  It appears that the indexing process failed about 1/3 thru the data.   I was lacking either tools, authorization or knowledge to debug and resolve the issue myself.  I'd like to figure out ways that the dev team can investigate and resolve this kind of issue without devops intervention in the future.

**Comment by yozlet** [comment]
According to @ozzyjohnson, the ES instance hit its JVM heap limit (1GB) while indexing. That instance has had its heap raised to 3GB, and it should be possible to fix the others very quickly.

**Comment by yozlet** [comment]
Ozzy is fixing the other instances. Closing.

**Comment by ozzyjohnson** [comment]
I've updated the other instances. In order to get the change, we'll need to.

1) Restart the ES containers.
2) Rebind the ES instances.
3) Restage the apps.

The first two take seconds. The third depends on the app, but it's faster than pushing updated code.

**Comment by LisaGee** [comment]
Assigned to @ultrasaurus to accept.

**Comment by ErieMeyer** [comment]
@ultrasaurus -- this is for you, my dear (unless you want to teach me how to review this!)

**Comment by ultrasaurus** [comment]
this has been resolved.  I believe CloudFoundry team is working on processes to make this not happen in the future.
