### ISSUE TITLE
Create infographics/illustrations for key facts

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#365]

**Comment by jjoteal** [comment]
Just a note that we are waiting for the final fact content from Ed/WH. Angel will be assisting with any custom illustrations.

**Comment by jjoteal** [comment]
FYI -- here is the general style. We created "generic" themed icons that hopefully can be repurposed to whatever the final content is, but are prepared to create custom graphics in this style if needed once the final content arrives.

![image](https://cloud.githubusercontent.com/assets/12192706/9274413/9cb9497e-4263-11e5-8859-a431ce4c6593.png)

**Comment by LisaGee** [comment]
These look great. Thanks!

**Comment by jjoteal** [comment]
@LisaGee @ErieMeyer -- in researching some 'key facts', what about these (I aimed to find facts that would go with the illustrations that have already been developed):

- More than 47% of undergraduates have a family income less than $40K
- Nearly 2/3 of full-time students receive financial aid
- College graduates earn on average 85% more than those with just a high school diploma

Thoughts? Should I have Clare fact-check these before we include them on the site?

**Comment by jjoteal** [comment]
Reassigning to @LisaGee just to make sure she knows that this is in her court at the moment.

**Comment by LisaGee** [comment]
@jjoteal Was hoping to make these super positive. Here's all the good stuff that will happen to you if you go to college, yes, you can afford to go to school, etc....

**Comment by LisaGee** [comment]
I'm pretty sure this is done. Assigning to @jjoteal to Accept.

**Comment by jjoteal** [comment]
Yep! Per https://github.com/18F/college-choice/issues/315, accepting and closing.
