### ISSUE TITLE
As a Consumer, if I visit a page where Scorecard 1.0 is available, I should be able to access 2.0, when it's released, so that I can still find the tool and the existing referring websites don't have broken or outdated links.

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#396]
1. The White House site: https://www.whitehouse.gov/issues/education/higher-education/college-score-card, references: https://surveys.ope.ed.gov/scorecard/
2. NCES site: http://collegecost.ed.gov/ references: http://collegecost.ed.gov/scorecard/index.aspx

Both of these sites should point to PICC's final URL.

**Comment by LisaGee** [comment]
Need to start working with OCIO on how this will work.
@ErieMeyer - Can you take a first crack at this?

**Comment by ErieMeyer** [comment]
In touch with WH digital strategy office about updating the link.

Do you mean you want me to coordinate with Danny et all about switching the links? Happy to!

**Comment by LisaGee** [comment]
That would be awesome. Thanks, Erie!

**Comment by ErieMeyer** [comment]
@nacin is on this one!

**Comment by LisaGee** [comment]
@nacin is handling 1.
@lisagee is in coordination with nces folks on target to launch time redirection.

**Comment by barkimedes** [comment]
Links appear to go to the right places now. I think this is done.
