### ISSUE TITLE
As a Consumer, I want to be able to identify the name of the tool and who is responsible for it so I know how to refer to it later.

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#4]

**Comment by jjoteal** [comment]
@meiqimichelle 

On the mobile version of the header, the total height of the header shrinks from 100px (desktop) to 84px (mobile)

On the footer, the "U.S. Department of Education" should be bold 14px (desktop) 12px (mobile) with 100px letter spacing. Also can you ensure that the background color is #eeeeee? Also the height of the footer should be 100px on desktop and 60px on mobile.

I'll check it out again once those tweaks are made!

**Comment by meiqimichelle** [comment]
@jjoteal more for you!

- I'm not seeing the total height of the header change on my end. Which browser are you using? (Assume Chrome based on our previous interactions, but best to check!)

- I adjusted the footer letter spacing to match spacing in the header -- see what you think, should be close to how Photoshop interprets 100px of letter spacing, but we can click up or down if you see the need!

- I adjusted the background color on the footer. It was #e1e1e1 as per the lighter gray in the styleguide. Is the #eeeeee another gray that carries through elsewhere? I may have missed it in other places too!

- I made the footer height and font size change based on screen width. See if that's working for you now.

- Also, is that where you want the desktop/mobile styles to break in this case? It seems like it will be too small for all the desktop-mobile transitions, but it might be the one you want for the header/footer.

**Comment by jjoteal** [comment]
Design review for header and footer ONLY completed. Pushing to "accept"

**Comment by ultrasaurus** [comment]
For review: https://pages-staging.18f.gov/college-choice/

**Comment by LisaGee** [comment]
It is unclear to me what I'm looking for in thsi story, other than there is a header and a footer. Which there are (even though, they will likely need some additions before release to add appropriate links), so I'm accepting.

**Comment by meiqimichelle** [comment]
That was it, header and footer :)
