### ISSUE TITLE
BUG: In "Sort by" dropdown, change "Earnings" to "% Better than No College"

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#400]

**Comment by ultrasaurus** [comment]
need confirmation from @LisaGee about what you want here.  See all the related issues in #253

**Comment by LisaGee** [comment]
This is literally a word change, not a sort change. The request from the Dept of ED is that the Default sort continue to be Threshold earnings, which really means: % of students who are making more money than if they had just gotten a HS diploma and done no college.

**Comment by LisaGee** [comment]
We need to work out words that are better than this.
@ErieMeyer could you have a chat with Dana? Help...

**Comment by LisaGee** [comment]
Let's make the wording change in the meanwhile and I'm opening another ticket to come up with better words. See #491

**Comment by ultrasaurus** [comment]
What about as a placeholder "Better than High School?"

**Comment by ErieMeyer** [comment]
@ultrasaurus that idea is a top one. I'll coordinate with @jjoteal for testing options

**Comment by ultrasaurus** [comment]
That was too long... I created "Advantage Factor" which says as much or as little as anything else.  I don't think any label will really work without the value displayed as part of the search results.

**Comment by ErieMeyer** [comment]
Looks awesome! Will re-open an issue for naming conventions.
