### ISSUE TITLE
BUG: Area of Study "Programs" dropdown should show the list of "majors" and degrees (Bachelors, Associate, Certificate)

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#401]

**Comment by ultrasaurus** [comment]
So, then how is someone supposed to search by 2- or 4- year schools?  (sorry I'm new to the user expereince!)

**Comment by LisaGee** [comment]
Only under Advanced search.

Part of ED's gentle nudge for students to pick the best school and not immediately jump to assumptions about what that might look like.

Lisa

Sent from my Windows Phone
________________________________

**Comment by LisaGee** [comment]
I lied here.
A user should in fact be able to select both the "Type of Degree": Associates or Bachelors and the "Program of Study" under Major/Degree label, as was shown in Jess's original wireframe.

The search results should then reflect the users' selection.

**Comment by LisaGee** [comment]
Just for clarification - 2 different fields needed.

**Comment by jjoteal** [comment]
Ok, sounds like we'll need to change the header back to "Programs/Degree" then (Rather than "Area of Study") so we can include 2 sections:
1) Select Program dropdown
2) Select Degree dropdown

Is that correct?

If so, this should be assigned to @meiqimichelle for implementation as the design elements for headers, dropdowns, and labels have already been designed.

**Comment by jjoteal** [comment]
@LisaGee, let me know if 1) and 2) in the previous comment are correct, and then I can reassign to @meiqimichelle

**Comment by jjoteal** [comment]
Just reassigning to @LisaGee for now, so it is clear we need her decision here before we move forward.

**Comment by jjoteal** [comment]
Please add multi-select to the Programs dropdown.

**Comment by meiqimichelle** [comment]
- [ ] HTML/CSS
- [ ] data

**Comment by ErieMeyer** [comment]
Looks awesome but is missing "certificate" as an option.

**Comment by LisaGee** [comment]
Should not have certificate for 1.0

Sent from my Windows Phone
________________________________

**Comment by ErieMeyer** [comment]
Apologies -- looks great! :+1:
