### ISSUE TITLE
FYI: College comparison tools and code in the public domain!

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#406]
VA - GI bill comparison tool
+ https://github.com/department-of-veterans-affairs/gi-bill-comparison-tool
+ http://department-of-veterans-affairs.github.io/gi-bill-comparison-tool/

(Digging on the CFPB code here: https://github.com/cfpb/cfgov-refresh/issues/897 )

**Comment by LisaGee** [comment]
@ErieMeyer - what is the work item here?

**Comment by ErieMeyer** [comment]
Just FYI -- closing!
