### ISSUE TITLE
As a consumer, when I search for a school by name, I should get matches closer to what I expect, so I can more easily find the results I'm actually looking for.

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#41]
As a consumer, when I search for multiple terms, it should AND them (currently looks like it matches any term, should match all terms)

**Comment by ultrasaurus** [comment]
this is true.  If you search for small schools in Rhode Island, it does an AND.  I think there is a separate issue with specific behavior for the name field.

**Comment by LisaGee** [comment]
This bug was written specifically for the Name field. Sorry if there was confusion.

**Comment by LisaGee** [comment]
For example, when I type Brown University in the Name field, there should only be 1 result.

**Comment by ultrasaurus** [comment]
There was another issue about partial matches, but I can't find it now.  We have a lot of options here.  If we simply AND the words, then you could search for "York New" and find "New York"  -- that example is absurd, of course, but there may well be real cases where this could cause confusion.  We could also do a literal match, but it seems like you want to search for "Univ of Calif" and get all the "University of California" schools, but you would also get California University (if there is such a school).

What I think you may want is a [substring match](http://stackoverflow.com/questions/23243867/elasticsearch-find-substring-match)  which in elasticsearch terms would be to save the text as "not analyzed" then use a wildcard query for the ends of words.  My thinking is we would break on spaces, and do a search like:  "Univ* of* Calif*" which I think would have the behavior most folks would expect. (I think we would also want to do a case insensitive search.)

**Comment by saintsoup52** [comment]
I think this solution would be very helpful... is there a reason why we don't have an autocomplete in the name search box on the first page?

**Comment by LisaGee** [comment]
This is not Accepted. Case-sensitivity is still an open issue.
https://federalist.18f.gov/preview/18F/college-choice/staging/search/?name=harvard&& returns 0 results.
https://federalist.18f.gov/preview/18F/college-choice/staging/search/?name=Harvard&sort=advantage:desc returns 1 result.

**Comment by ultrasaurus** [comment]
I believe this is addressed with https://github.com/18F/open-data-maker/pull/172
up on the dev server for testing

**Comment by ultrasaurus** [comment]
@LisaGee @ErieMeyer Please test.  I believe this is working now.  When I tested last night it was not finished indexing.

**Comment by LisaGee** [comment]
I tested and in principle it  looks like its working, but it's hard to judge accurately b/c only online only schools are showing up and i can't figure out a way to test around that.

Sent from my Windows Phone
________________________________

**Comment by LisaGee** [comment]
It looks like it's working on Staging, but I'll test again once the other tickets are merged onto Staging.

**Comment by LisaGee** [comment]
Looking good! Accepting
