### ISSUE TITLE
Data problem with CDR - incorrect magnitude

### ISSUE THREAD

**Issue by diego-** [18F/college-choice#413]
Data problem with CDR – it shows up as a number rather than a decimal. Eg for ASU, it says 8.5 instead of .085 – inconsistent with other rates. Let me know how you’d like us to proceed—we can fix the files on our end, or you could probably just program it differently.

**Comment by LisaGee** [comment]
We think it would be better for Clare to have this fixed in the data.

**Comment by LisaGee** [comment]
Once we have them, we will need to re-import the data files.

**Comment by saintsoup52** [comment]
I think ED does the whole numbers for all their percentage stats in IPEDS at least (e.g. Completion rates).

**Comment by LisaGee** [comment]
From: McCann, Clare 
Sent: Monday, August 17, 2015 3:37 PM
To: Gelobter, Lisa
Subject: CDR data

RTI is fixing the files so that the CDR data are a decimal rather than a number. They should upload the files to us on Wednesday. Apologies for that error.

**Comment by LisaGee** [comment]
Clare has mailed saying she has the new files. Whenever @ultrasaurus is ready, she can upload.

**Comment by ultrasaurus** [comment]
@LisaGee are we going to get new files with gender and age fixed?

**Comment by LisaGee** [comment]
@ultrasaurus Not for this round. We removed Age and Gender from the UI.

**Comment by LisaGee** [comment]
I believe this was done Friday 8/28/15.
@diego- can you confirm and accept?

**Comment by diego-** [comment]
tested on dev; 2013.repayment.CDR3 is returning numbers as expected (example: 16.5)
