### ISSUE TITLE
Some data missing from API

### ISSUE THREAD

**Issue by diego-** [18F/college-choice#415]
It looks like a few things are missing:

[-]   C200_4 and C200_L4 are only there as pooled suppressed, not as single elements. Similarly, poolyrs200.

[-]   Missing Carnegie UG profile and size and setting

[-]   There are other elements missing, but I’m still struggling to figure out what they are (harder than I’d hoped to crosswalk between our files, our variables, and dev variables). I will continue to work on this and get back to you as soon as possible.

**Comment by LisaGee** [comment]
@diego- Are you saying that these are fields that are available in the data, but not in the json returned for a school? Can we ask Clare to cross-check one school against all 1900 columns in the CSV?

**Comment by ultrasaurus** [comment]
I believe this has been addressed
