### ISSUE TITLE
Create an automated build process for CollegeChoice CloudFoundry

### ISSUE THREAD

**Issue by diego-** [18F/college-choice#421]
- [x] check to make sure that pushing to master doesn't prematurely reveal data
- [x] fix build script https://github.com/18F/college-choice/issues/427
- [ ] auto run ./push.sh from travis when merge to master and tests pass

**Comment by yozlet** [comment]
Does this mean, for example, that all commits to the master branch should be automatically built and pushed? We can almost certainly get Travis to do that: https://docs.18f.gov/apps/continuous-deployment/ (note the section on Jekyll builds)

**Comment by ultrasaurus** [comment]
we'll not do this because we are only going to push weekly
