### ISSUE TITLE
BUG: Insert more space between the Gender graph and the Other Demographics information on the individual school page

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#424]
Current screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9309648/1bfae48c-44d9-11e5-9474-3718229a52a9.png)

Insert ~30-40px of space between the 2 sections

**Comment by meiqimichelle** [comment]
I don't think we're including gender for launch so this might to be relevant anymore.

**Comment by LisaGee** [comment]
correct. this has been removed. So Closing.
