### ISSUE TITLE
BUG: Insert more space between the "/" and the % of part-time students in the Other Demographics section

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#425]
Current screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9309729/89a90efa-44d9-11e5-85b5-45a1c0bbfa95.png)

Should be more space between the "/" and the "30% part-time"

**Comment by meiqimichelle** [comment]
Note to self: while I'm there, make sure that section does not split onto two lines at certain page widths.

**Comment by ErieMeyer** [comment]
Not sure that the % styles are consistent. Also, splitting on to two lines. Assigning @jjoteal to review

![screen shot 2015-09-07 at 11 48 07 pm](https://cloud.githubusercontent.com/assets/1626026/9726020/ec4cc776-55ba-11e5-962b-4975e42c8d16.png)

**Comment by jjoteal** [comment]
Closing!
