### ISSUE TITLE
BUG: There should only be an 'X' button or an 'ADD' button, never both

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#426]
Current display:

![image](https://cloud.githubusercontent.com/assets/12192706/9314870/a55789f4-44f9-11e5-9a9b-c4e58f47f312.png)

Change to:
![image](https://cloud.githubusercontent.com/assets/12192706/9315041/bd48fc2c-44fa-11e5-9230-7b5e9e648bbe.png)

Please note that the "x" and "add state" icons should never display together. Only once the user selects a state, should the "x" icon display.

**Comment by LisaGee** [comment]
The functionality works as it is currently implemented. And what if the user clicked Add State,b ut then whoops, decides she doesn't really want to add another state and wants the empty field to go away?

**Comment by jjoteal** [comment]
This is JUST referring to the style of the 'x' -- the circle should be smaller, the 'x' should be white, and the 'x' within the circle should be bigger.

**Comment by meiqimichelle** [comment]
#1031 covered the style of the X button issue. I updated the title of this issue to reflect the remaining bug.
