### ISSUE TITLE
As a website tester, we'd like to have an up-to-date beta site (as of 4/17) that works with live data.

### ISSUE THREAD

**Issue by diego-** [18F/college-choice#428]

**Comment by ultrasaurus** [comment]
please review:  https://college-choice.18f.gov

**Comment by saulshanabrook** [comment]
Can I look at it or is it restricted?

**Comment by ultrasaurus** [comment]
@saulshanabrook sorry, the data isn't public yet -- I should have made that more clear!

**Comment by ultrasaurus** [comment]
updated comment to make it clear that we're still testing the data integration, so this story is for folks who have access to test the website

**Comment by ErieMeyer** [comment]
Looks great!
