### ISSUE TITLE
Change Branding on PICC Website to reflect final name

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#432]

**Comment by jjoteal** [comment]
Reassigning to @meiqimichelle as I am not sure where to find this in the code (I looked in the header file and it appeared as though the site title was being pulled in dynamically from somewhere) -- sorry!

Site title should be "College Scorecard"

**Comment by meiqimichelle** [comment]
This change is live on `dev`

**Comment by LisaGee** [comment]
I see it. Accepted.
