### ISSUE TITLE
BUG: Ensure all "Higher than Average" "About Average" and "Lower than Average" text styles are all-caps and bold

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#433]
Should look like:
![image](https://cloud.githubusercontent.com/assets/12192706/9339697/7c7b0a0e-45b9-11e5-8c51-9a7ba464ff2c.png)

14px bold

"Higher Than Average" = #77b713
"Lower Than Average" = #d44116
"About Average" = #2b6091

**Comment by jjoteal** [comment]
@LisaGee want to weigh in and let us know if this reads better for you?

**Comment by jjoteal** [comment]
Going through display issues and am thinking there's a dupe of this somewhere with a more updated design. The new design should look like this:


![image](https://cloud.githubusercontent.com/assets/12192706/9691693/1b1860ac-5312-11e5-9f8f-1453928baa4f.png)

So, in other words, the arrow is next to the "HIGHER THAN AVERAGE" and number associated with the graph stands alone.

Assigning this to @meiqimichelle as this is one of the highest priority display items I'd like to resolve for launch. Also labeling it DISPLAY.

**Comment by meiqimichelle** [comment]
Looks like:

![screen shot 2015-09-05 at 9 17 04 am](https://cloud.githubusercontent.com/assets/4827522/9700294/893c4116-53b2-11e5-8f36-2647b409cdf6.png)

**Comment by ErieMeyer** [comment]
Looks good on dev!

**Comment by ErieMeyer** [comment]
:us:
