### ISSUE TITLE
Sort by Earnings on Results page doesn't jibe with Average Salary graphics

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#438]
Steps to repro:
1. Go to: https://college-choice.18f.gov/search/?name=columbia&&degree=2..3&sort=2011.earnings.gt_25k_p10%3Adesc
2. See that Earnings is selected as Sort By.
3. See that University of Missouri-Columbia is #2 in sort order with $46,000 as Average Salary, but University of Phoenix-Columbia Campus is #3 with $53,400.

Expected Results:
I would expect the Sort to match the Salary graphics.

**Comment by ultrasaurus** [comment]
My understanding is that the desired sort by earnings is supposed to be (which is a percentage):  2011.earnings.threshold_earnings_percent:desc
But Salary After Graduation is: 2011.earnings.6_yrs_after_entry.mean_earnings.lowest_tercile

I agree with the behavior you expect, but want to make sure we understand the direction we're going with the UI.  Do we want a different word to describe .threshold_earnings_percent?  or just skip that idea and go with the salary number?

**Comment by LisaGee** [comment]
I suspect the issue is actually a conflict is what data actually makes sense for the user. I will double-verify, but I’m guessing the bug is a usability one, not a technical one…

**Comment by ultrasaurus** [comment]
see https://github.com/18F/college-choice/issues/400 -- is one of these a dup?

**Comment by LisaGee** [comment]
Will be resolved by #400. Is a verbiage issue.
