### ISSUE TITLE
BUG: Some school's Graduation Rate is labeled 0%, but the chart shows more than that

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#443]
Steps to Repro:
1. Go to: https://college-choice.18f.gov/search/?name=brown&&degree=2..3&sort=2011.earnings.gt_25k_p10%3Adesc
2. See that for the following schools the Graduation Rate label says 0%, but the chart shows more than that:
Brown Mackie College-Albuquerque
Brown Mackie College-St Louis
Brown Mackie College-San Antonio
Brown Mackie College-Boise
Brown Mackie College-Tulsa
Brown Mackie College-Phoenix
Brown Mackie College-Greenville

Expected Results:
I'd expect that the label and the bar chart match each other.
![screen shot 2015-08-18 at 11 04 24 pm](https://cloud.githubusercontent.com/assets/12847090/9347901/d1570de0-45fd-11e5-9a48-b6b804fca640.png)

**Comment by LisaGee** [comment]
this is likely an issue due to data being either NULL or Privacy Suppressed.
Opened issue #453 to address the visual representation of this scenario.

**Comment by saintsoup52** [comment]
I found this same issue with ITT Technical Institute-Myrtle Beach... 

they don't have a graduation rate yet and it should appear as "Not Reported" (or whatever language you are using)

![image](https://cloud.githubusercontent.com/assets/4397508/9489847/f370fe86-4bb1-11e5-8003-cc804cb96a31.png)
