### ISSUE TITLE
Alphabetical Sort on the Search Results page should use the literal text for sorting

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#445]
I'm worried that Salary won't be the most useful to students and Alphabetical is certainly straightforward.

**Comment by ultrasaurus** [comment]
This is already a feature...

![image](https://cloud.githubusercontent.com/assets/41906/9382356/ff91d422-46f4-11e5-9479-4987698ffadf.png)

https://federalist.18f.gov/preview/18F/college-choice/dev/search/?degree=2..3&sort=school.name%3Aasc

However, the sort is incorrect with mutli-word names (which is all of them):  https://github.com/18F/open-data-maker/pull/133

**Comment by ultrasaurus** [comment]
this got fixed when I changed the search, you can test it on staging

**Comment by ErieMeyer** [comment]
Looks great!
