### ISSUE TITLE
BUG: At a 2-col width, the Search Results page doesn't show Filters or Search Again fields

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#446]
Chrome, Mac

Steps to Repro:
1. Go to: https://federalist.18f.gov/preview/18F/college-choice/dev/search/?name=columbia&&degree=2..3&sort=2011.earnings.threshold_earnings_percent%3Adesc on a computer.
2. Reduce the width of your browser window until you only see 2 school columns, not 3.
3. See that there is no way for you to alter the search terms and search again. and also Filters option is not available either.

Expected Results:
I should still see the Search Again fields and the Filters.

**Comment by meiqimichelle** [comment]
Closing in favor of #340.
