### ISSUE TITLE
BUG: Hover info on bar charts need to be better formatted

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#448]
Chrome, mac.

Steps to Repro:
1. Go to: https://college-choice.18f.gov/search/?name=baltimore&&degree=2..3&sort=2011.earnings.gt_25k_p10%3Adesc
2. Scroll down to: Baltimore City Community College
3. Place your mouse over the National Average line on the Graduation rate chart.
4. See that the #s if the overlay that pops up are not formatted as %s, plus one of them is very long:

Expected Results:
These numbers should be represented as %s, with no decimals.

![Uploading Screen Shot 2015-08-18 at 11.30.16 PM.png…]()

**Comment by barkimedes** [comment]
Related issues #690, #689 in favor of this issue. I think it is no longer an issue because I don't see any hovery stuff (chrome, mac). But whoever officially closes this issue, just verify that those issues should be closed as well. Thanks!
