### ISSUE TITLE
BUG:Closed schools should not appear in the Search Results

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#449]
I believe that Corinthian schools are closed: Everest, Heald and WyoTech.

However, if I search for any of those terms, I get results returned.
For example: https://college-choice.18f.gov/search/?name=everest&&degree=2..3&sort=2011.earnings.gt_25k_p10%3Adesc

**Comment by saintsoup52** [comment]
Heald and wyotech were bought by another corporation and still exist.

I don't think there should be any everest campuses left... Maybe one or two.

**Comment by LisaGee** [comment]
Clare has confirmed that the data are correct in the CSVs.

**Comment by LisaGee** [comment]
Here is some examples of schools that are closed:
WyoTech in Fremont CA
Everest Institute in Rochester, NY
Heald in SF

These should not show up in results.

**Comment by LisaGee** [comment]
Asking Clare for a reminder of which field we need to check.

**Comment by ultrasaurus** [comment]
I sent a possibly redundant note to Clare.  Putting this in "blocked" till we get the answer

**Comment by LisaGee** [comment]
The field we need to check is: CURROPER.

**Comment by LisaGee** [comment]
When I search the 2013 data for "Everest", 5 schools are returned, but only one has: CURROPEN==1: Everest University-South Orlando
Link for testing:
https://federalist.18f.gov/preview/18F/college-choice/staging/search/?name=everest&&degree=2..3&sort=2011.earnings.6_yrs_after_entry.mean_earnings.lowest_tercile

**Comment by saintsoup52** [comment]
If type in "Everest" into College Navigator and limit to only 2/4 year schools... I get 42 results:

http://nces.ed.gov/collegenavigator/?q=Everest&s=all&ic=1+2

I think there is something wrong here... because only "open" and "approved" programs appear on Navigator.
