### ISSUE TITLE
Set up New Relic alerts

### ISSUE THREAD

**Issue by yozlet** [18F/college-choice#450]
Certain members of the team should be pinged when certain error conditions arise on prod. (For yet-to-be-decided values of "certain")

**Comment by yozlet** [comment]
The most obvious things to alert on, which NR can do, are "standard" queries which should return a 200 (Success). I'm not sure if we can validate the returned results. I believe we can also set up alerts for processing times taking longer than X seconds.

**Comment by ultrasaurus** [comment]
We've got pingdom set up now, so I will close this issue
See:  https://github.com/18F/college-choice/issues/596
