### ISSUE TITLE
From the search results page, I should be able to conduct a new/modified search, by clicking a Find Schools button

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#451]
Steps to Repro:
1. Go to: https://college-choice.18f.gov/search/?name=heald&state=CA&&degree=2..3&sort=2011.earnings.gt_25k_p10%3Adesc
2. in the left column, change the state, using the dropdown to NY.
3. Scroll to the bottom of the page looking for the Find Schools button to re-initiate a search.
4. Find none.

Expected results:
I would be able to click a button, in the same way I can on the HP.

**Comment by meiqimichelle** [comment]
This was solved with #217

**Comment by ErieMeyer** [comment]
Working great!
