### ISSUE TITLE
Need a visual representation of a Not Available state for the bar charts

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#453]
there are cases where the data in the appropriate field is either NULL or Privacy Suppressed.
In both of these situations, the label under the chart should read some version of Not Available and the chart should be grayed out or hashed out or something visual to indicate Not In Use.

This should take care of the following issues:
#447 
#442 
#443 
#439

**Comment by jjoteal** [comment]
@LisaGee this is addressed in #273.

**Comment by LisaGee** [comment]
Closed as dupe of #273
