### ISSUE TITLE
Create revised Data Site > Data Details wireframes so that they better accommodate the amount of content contained on these pages.

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#454]
@ultrasaurus per my slack chat, please take a look at the revised wireframe in PICC > Wireframes > picc-data-modified-pages.pdf (pages 2-3).

Per our conversation earlier today, the concept is:
1) Allow users to browse the categories of data first, rather than dumping them on a page with thousands of listings
2) Create a page for each category of data that lists and defines the metrics associated with that category

Please note that I also included a keyword search on the index page, as a nice-to-have.

**Comment by LisaGee** [comment]
@jjoteal Let's review together.

**Comment by ErieMeyer** [comment]
Not sure that this is actually ready to accept -- @LisaGee?

**Comment by LisaGee** [comment]
Reviewed with @jjoteal - Lookin' good! Accepting.
