### ISSUE TITLE
BUG:  Add more space (~30px) above and below the horizontal rules on the right side of the Financial Aid & Debt metrics

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#456]
Current screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9369035/bfd5513e-4694-11e5-8f9f-e4ed88528003.png)

Design mock-up:
![image](https://cloud.githubusercontent.com/assets/12192706/9369068/f46192e6-4694-11e5-88b2-027440a1121e.png)

**Comment by ErieMeyer** [comment]
Looks great on dev!

**Comment by ErieMeyer** [comment]
:us:
