### ISSUE TITLE
BUG: The "/mo" in "$250/mo" should not be bold

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#457]
Current site screenshot:

![image](https://cloud.githubusercontent.com/assets/12192706/9369108/2ad0feb6-4695-11e5-8fc9-1ecdcff4780d.png)

Design mock-up:
![image](https://cloud.githubusercontent.com/assets/12192706/9369115/34b8aca8-4695-11e5-8725-6e1258c257a9.png)

**Comment by meiqimichelle** [comment]
Resolved in passing in another issue. Should be live.

**Comment by ErieMeyer** [comment]
Looks great on dev!

**Comment by jjoteal** [comment]
Looking good on staging! Accepting and closing!
