### ISSUE TITLE
BUG: Get the Best Deal section on homepage

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#458]
Mobile Screenshot:

![image](https://cloud.githubusercontent.com/assets/12192706/9369254/f557acd4-4695-11e5-87b0-93a932d06fe0.png)

Image should be contained within the white box.

**Comment by LisaGee** [comment]
graphic is getting replaced by links.

**Comment by LisaGee** [comment]
may be getting replaced with different links.

**Comment by ErieMeyer** [comment]
Only one of the links that Ed provided could possibly work here (update coming shortly). Would be this one: https://fafsa.ed.gov/FAFSA/app/f4cForm?execution=e1s1

Copy would be "Estimate your aid" which is what Ed uses elsewhere to point to this tool.

I'm fine switching the PFC link/button out for this one (checked with Dana and she said she wasn't overly concerned with the design issues), pending @jjoteal's capacity to design a new button to point to the other tool. Would recommend *not* using the new tool's branding on the button.

**Comment by saintsoup52** [comment]
Does github do sad emoticons? :-(  (j/k)

Will there only be one link to another tool in the sidebar? Maybe more links without the big box to other tools (e.g., Paying for College, GI Bill Comparison Tool).

**Comment by ErieMeyer** [comment]
Interesting! GI, PFC and FAFSA estimator might be a good combo (if the design doesn't break by adding three links instead of one button).

I will check with Dana about the UX implications of three links instead of one (my strong bias is for one).

Definitely all depends on @jjoteal's capacity during crunch week.

**Comment by jjoteal** [comment]
@ErieMeyer here's a mock-up of the new buttons you requested:

![image](https://cloud.githubusercontent.com/assets/12192706/9468487/f6bf0a08-4b0f-11e5-9be4-81b3393055f6.png)

Please note that if we go with this, we'll need a new title for this section as it used to be "Paying for College" and that is now a button name.

**Comment by ErieMeyer** [comment]
Rad -- thank you! Could you pop it into a larger screenshot so it's in context when I chat with stakeholders later today?

Maybe the section should be called "Get the Best Deal"

**Comment by ErieMeyer** [comment]
Also this is beautiful -- excellent work.

**Comment by saintsoup52** [comment]
I would suggest for the other two links.
"Evaluate Aid Offers"
"Calculate GI Bill Benefits"

**Comment by saintsoup52** [comment]
PS I love the graphics

**Comment by jjoteal** [comment]
@ErieMeyer here's the full page mock for context:

![image](https://cloud.githubusercontent.com/assets/12192706/9469652/394d289a-4b16-11e5-90fe-45cb22704c07.png)

**Comment by ErieMeyer** [comment]
I love the wording changes @saintsoup52  -- @jjoteal could you switch these? Thank you!

**Comment by ErieMeyer** [comment]
Section should be titled:

Get the Best Deal

Links should say:

1. Estimate Your Aid (linked here: https://fafsa.ed.gov/FAFSA/app/f4cForm)
2. Evaluate Aid Offers (linked here: http://www.consumerfinance.gov/paying-for-college/compare-financial-aid-and-college-cost/)
3. Calculate GI Bill Benefits (linked here: https://department-of-veterans-affairs.github.io/gi-bill-comparison-tool/)

**Comment by meiqimichelle** [comment]
@jjoteal Where is the GI tool icon from?

**Comment by jjoteal** [comment]
@meiqimichelle i believe @ErieMeyer prefers just to use text only and NO icons. @ErieMeyer can you confirm?

**Comment by meiqimichelle** [comment]
This is fixed on `dev` with #735

**Comment by ErieMeyer** [comment]
Yayaya looks great!

**Comment by ErieMeyer** [comment]
Looks great on staging!
