### ISSUE TITLE
As a consumer, I want to see a legend associated with each bar graph on the individual school page that explains what the lines on meters mean so I can understand them better

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#466]
i.e. this:

![image](https://cloud.githubusercontent.com/assets/12192706/9394050/e873be72-4753-11e5-81a0-acd5d92c0f7b.png)

should be associated with ALL bar graphs that display national average lines.

**Comment by meiqimichelle** [comment]
This will be done when #999 merges.

**Comment by meiqimichelle** [comment]
Should be live on `staging`

**Comment by ErieMeyer** [comment]
All set!
