### ISSUE TITLE
BUG: tooltip cut off in desktop search results page

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#475]
Chrome, desktop

To repeat:
1. Home page
2. Search anything (in this case, I searched Ohio)
3. Hover any tool tip (they all get cut off -- just could only grab a screenshot of this one)

![image](https://cloud.githubusercontent.com/assets/1626026/9413118/ec885a54-47fd-11e5-9878-4fb572739014.png)

**Comment by meiqimichelle** [comment]
Closing as duplicate to #463.
