### ISSUE TITLE
The browser tab of an individual school page should have the school name first, then the tool name

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#478]
It is currently School/{name} as implemented by #377 , which means that the {name} is mostly not visible in the tab and if you have 3 tabs open, they look almost identical. Putting {name} first would make it more legible and useful.

**Comment by meiqimichelle** [comment]
I think this is done. I see name first on my end.

**Comment by LisaGee** [comment]
Actually, it does show the name of the school, but not the name of the tool.Format should be: School Name - Site Title
