### ISSUE TITLE
As a site operator, I'd like to have access to environment logs to troubleshoot issues

### ISSUE THREAD

**Issue by diego-** [18F/college-choice#480]
We either need to have dev team access OR someone from devops needs to be added to our dev team.

**Comment by ultrasaurus** [comment]
@ozzyjohnson is investigating this

**Comment by LisaGee** [comment]
Re-assigning to @ultrasaurus for updates.
@dnesting to be also riding shotgun on this issue. Thanks.

**Comment by ultrasaurus** [comment]
Deep in the operational readiness notes that were mailed out Friday, is this update:  

Durable logging: Cloud Foundry throws away logs now, long term plan is a nice elk console for browsing logs. For now, each team is doing it on their own. For an interim solution for our launch, Ozzy is setting up an EC2 instance for a target for syslog for all the cloud foundry servers.

**Comment by hollyallen** [comment]
@ozzyjohnson  is there a corresponding devops github issue or trello card for this?

**Comment by ozzyjohnson** [comment]
@hollyallen - Yes, there's a consolidated card with most of the PICC engineering tasks.

https://trello.com/c/utrIWpVb/274-picc-launch-consulting

**Comment by ultrasaurus** [comment]
@ozzyjohnson do you have an ETA on the logging?  for some reason I thought you had set this up on Mon/Tues and I just needed to learn how to use it...

**Comment by ozzyjohnson** [comment]
Still banging on this as v2. The first shot proved more of a trade-off than
I anticipated. Hoping to give you something new by EoB.

**Comment by ultrasaurus** [comment]
thanks @ozzyjohnson !

**Comment by ultrasaurus** [comment]
Got this:  https://github.com/18F/college-choice-data/blob/master/doc/LIVE.md#app-logs

Would be great if @dnesting were to take a look at it too, maybe he could be the one to accept this story?

**Comment by hollyallen** [comment]
That's good, what about the other logs though?

**Comment by ultrasaurus** [comment]
All the other services are part of Cloud Foundry infrastructure... @ozzyjohnson what do you think?

**Comment by ozzyjohnson** [comment]
Yes, service instances are 'black boxes' in the Cloud Foundry scheme of things. You're not supposed to be able to see anything but an IP/port and user/pass and that's only from within your runtime application.

What I've done to provide access to the Marvel Monitor and Kibana for general application logging is something of a hack.

That said, I can get the backing Elasticsearch service instances shipping logs to the Kibana set up, but it will require some manual work from me until I can develop a further hack to automate it.

**Comment by yozlet** [comment]
Splitting this one out into remaining issues. See #1411 and https://github.com/18F/DevOps/issues/533

**Comment by ultrasaurus** [comment]
The docs about how to access the logs don't actually seem to work: https://github.com/18F/college-choice-data/blob/master/doc/LIVE.md

I followed the instructions to get the credentials and they weren't the correct ones to see the logs (tested production) 

I actually have the credentials, so this isn't a "stop ship" but we do need to fix

**Comment by yozlet** [comment]
I believe this is now fixed with the availability of https://logs.cloud.gov/

I can see all app and router logs in there for all spaces. However, no ES logs yet (see #1411).

**Comment by barkimedes** [comment]
@yozlet is access to logs.cloud.gov something that I/USDS would need access to? 

@ultrasaurus You mentioned that the docs for this were incorrect. Are they correct now?

If you both are comfortable closing the issue, then we can close it. But I haven't been able to see the things that evidence it's completeness, so I can't make that call.

**Comment by ultrasaurus** [comment]
will move back to in-progress till docs are updated

**Comment by yozlet** [comment]
@ultrasaurus: apart from https://github.com/18F/college-choice-data/pull/14 (now merged) what other docs need fixing?

**Comment by ultrasaurus** [comment]
@yozlet docs look good to me

**Comment by barkimedes** [comment]
:us:
