### ISSUE TITLE
BUG: Graduation Rate in the "value snapshot" does not appear to match the data

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#482]
Compare this:
https://federalist.18f.gov/preview/18F/college-choice/staging/search/?zip=02912&distance=10&degree=2..3&sort=2011.earnings.6_yrs_after_entry.mean_earnings.lowest_tercile

to the Data File in the PICC folder.

For example, look at: Community College of Rhode Island

**Comment by LisaGee** [comment]
The data filed for this institution should be C200_L4_POOLED_SUPP. It looks like the data is being pulled from C150_L4_POOLED_SUPP

**Comment by ErieMeyer** [comment]
Looks awesome!
