### ISSUE TITLE
EPIC: As a consumer, I should be able to sort my search results by: Alphabetically, Size, Cost Per Year, Graduation Rate, Salary, & Location

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#483]
Alphabetically -- A-Z only
Size - Smallest to Biggest
Cost Per Year -- Smallest to Biggest
Graduation Rate -- Biggest to Smallest
Salary -- Biggest to Smallest
Location -- Grouped by State Alphabetically (A-Z), or if they have searched by zip and mile radius, then by distance from the zip.

**Comment by ultrasaurus** [comment]
Location sorting seems low value and potentially confusing, since there isn't really a standard human thinking about what a location sort would be (wheras numbers and letters have an order that we learned in elementary school)

**Comment by LisaGee** [comment]
Closed as dupe of #189
