### ISSUE TITLE
Need to find better words for the Default search, aka Threshold Earnings

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#491]
What this metric really represents is:
the % of students who, 6 years from when they started college, are making more money than what someone who never went to college at all typically makes.
A person with only a high-school diploma (no college), 6 years after graduating from high-school, makes $25k/year on average.

**Comment by LisaGee** [comment]
@ErieMeyer Can you work with Dana to see what y'all can come up with?

**Comment by ErieMeyer** [comment]
On it!

**Comment by ErieMeyer** [comment]
So far, winners are "Salary higher than high school grads" and "Better than high school"

Possible to test both?

**Comment by ErieMeyer** [comment]
Closing this issue in favor of https://github.com/18F/college-choice/issues/534
