### ISSUE TITLE
As a consumer, I want to view the URL of the school on the Individual School page so that I can go to the school's website for more information.

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#492]
Please place in the top "basic information" area right under the # of students

**Comment by LisaGee** [comment]
Should open in a new tab.

**Comment by meiqimichelle** [comment]
- [x] HTML/CSS _Done with #517_
- [ ] data connection

**Comment by ErieMeyer** [comment]
Hmm -- looks like this isn't working quite yet. Link is not showing up.

To recreate: On staging, chrome, mac desktop, search "ohio" in school name, click on first school:

![screen shot 2015-08-25 at 3 47 02 pm](https://cloud.githubusercontent.com/assets/1626026/9477506/cd4372a0-4b40-11e5-8b8d-6605c75a3a0c.png)

**Comment by meiqimichelle** [comment]
@ErieMeyer This isn't live on staging yet.

**Comment by LisaGee** [comment]
I see it!
