### ISSUE TITLE
I should be able to get to the Data site from the Consumer Tool

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#497]
Best to put a link in the footer?

**Comment by LisaGee** [comment]
@jjoteal where would you suggest putting this?

**Comment by jjoteal** [comment]
@LisaGee I would recommend putting this link in the footer. Maybe a "Powered by College Scorecard Data" tagline right under "U.S. Department of Education". Sound good?

**Comment by LisaGee** [comment]
@jjoteal Sounds good, but I'd put it above the US Dept of Ed.

**Comment by jjoteal** [comment]
Sounds good. I'll do a mock!

**Comment by LisaGee** [comment]
And we also need a link to Contact Us, as referenced in #937 as long as you're mucking around in the footer.....

**Comment by jjoteal** [comment]
Nothing super exciting, but how about this @LisaGee:

![image](https://cloud.githubusercontent.com/assets/12192706/9610104/7c310c0a-50a5-11e5-84cd-9c5298b27f2e.png)

Assigning to you for design approval before implementation.

**Comment by LisaGee** [comment]
@jjoteal that's fine. Thanks.

**Comment by meiqimichelle** [comment]
What should be in the data footer? A link back to the consumer site? A link to the github repo?

**Comment by ErieMeyer** [comment]
Both those things sound great! And also the contact link.

**Comment by meiqimichelle** [comment]
So far:

## Consumer
<img width="1225" alt="screen shot 2015-09-01 at 11 12 36 am" src="https://cloud.githubusercontent.com/assets/4827522/9612423/7b5b2b9a-509a-11e5-9e52-70d52db77a79.png">

## Data
<img width="1219" alt="screen shot 2015-09-01 at 11 12 19 am" src="https://cloud.githubusercontent.com/assets/4827522/9612427/81a1476e-509a-11e5-9072-2e5f26028427.png">

**Comment by meiqimichelle** [comment]
Related: I don't have the GitHub link going anywhere now. Let me know where it should go after launch.

**Comment by meiqimichelle** [comment]
Should be live on `staging` although @ErieMeyer @diego- which GitHub repo should we link to from the data site footer?

**Comment by ErieMeyer** [comment]
:us:
