### ISSUE TITLE
As a picc developer, I can import the actual data, so that it is available for searches and display

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#5]
What encoding is used for 2012derived_opeid.csv?  

If I assume it is UTF-8, I get an invalid byte sequence in UTF-8 around row 2305.
If I open the file in Numbers line 2307 has: Globe UniversityñMadison West

- [x] confirm files delivered post Jul 1 can be imported (UTF8 encoding)  -- tested with 5 years of data (2009-2013) with same fields as consumer tool
- [x] index all fields (even if they aren't in data.yaml)
- [x] figure out syntax for querying nested fields

**Comment by ultrasaurus** [comment]
this is unblocked -- moving to backlog for Lisa to prioritize

**Comment by ultrasaurus** [comment]
update:  I've tested indexing 5 years of data.  Currently you can query all of the same data provided by consumer tool.  

http://ccapi-prod.18f.gov/school?name=American
http://ccapi-prod.18f.gov/school?ope_id=00143400&fields=year,admission_rate,name

**Comment by ultrasaurus** [comment]
all the fields are being imported now, as an example see:
http://ccapi-prod.18f.gov/school?ope_id=00143400&year=2010

still only 5 years -- indexing took 20 minutes (or about 4 mins per year).  This can be optimized :)

**Comment by ultrasaurus** [comment]
list the names & sizes of all historically black schools (as of 2013)
http://ccapi-prod.18f.gov/school?minority_serving.historically_black=1&fields=name,size&year=2013

**Comment by ultrasaurus** [comment]
you can get the value of a specific nested field like this:
http://ccapi-prod.18f.gov/school?name=American&fields=name,size,minority_serving.historically_black&year=2013

**Comment by ultrasaurus** [comment]
18 years of data -- took about an hour to index.  Here's a sample:

http://ccapi-prod.18f.gov/school?ope_id=00143400&fields=year,name,admission_rate

**Comment by ultrasaurus** [comment]
It was faster to just write a bash script to modify the files, rather than create a general purpose thing on the server, so this bug is still outstanding:  https://github.com/18F/open-data-maker/issues/81

but I tested staging with new data files and it worked fine.  Just need to re-index all of the files on production.  You should be able to see all/any of the data here:  http://ccapi-staging.18f.gov/school?unit_id=118693  -- i haven't looked at every fields, but I wrote code that pulls in all columns (even ones not in data.yaml) and it looks like it works to me

**Comment by LisaGee** [comment]
I'm seeing the real data appear in the Consumer Tool, so I'm Accepting.
