### ISSUE TITLE
As a Consumer, I'd like to be able to sort my search results by Completion Rate, so I can compare how good a school is at graduating its students.

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#504]
I think we only need to offer this sort from highest to lowest, as this is the way we think they should be evaluating -- best schools at the top.

**Comment by meiqimichelle** [comment]
To confirm: this is the same as what we're calling "graduation rate" on the search results cards?

**Comment by LisaGee** [comment]
It is. Thanks!

**Comment by LisaGee** [comment]
Working!
