### ISSUE TITLE
As a consumer, I want to identify top and low performing schools, so that I can make effectively choose my schools. 

### ISSUE THREAD

**Issue by saintsoup52** [18F/college-choice#515]
Consider using 5 buckets (not two or three).

The beauty of the bar graphs is that  users can identify the high and low performers quickly. Since the distance of an outcome from the national average may be very small in some circumstances. This would also mean this tool would be rating schools more then the current tool versus rating them less.

You should consider having five buckets of performance, not three.
o	Well Above Average (top 5% or top 20%)
o	Above Average           (6-33% or 20-40%)
o	About Average           (34-66% or 40-60%)
o	Below Average           (67-95% or 60-80%)
o	Well Below Average   (bottom 5% or 80-100%)

**Comment by LisaGee** [comment]
To be considered as part of #511
