### ISSUE TITLE
Data site analytics: All pageviews/impressions

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#521]
As a product team member, I would like to see analytics for all pageviews/impressions in DAP

**Comment by LisaGee** [comment]
@ErieMeyer - Can you pop in some questions you think this data will help you answer as a product team member or even a member of ED? Want to be sure that we're all talking the same language. thanks.

**Comment by ErieMeyer** [comment]
Heads up -- this is for the data tool not the consumer tool.

Examples:

+ How many people are looking at this?
+ How many visitors are new?
+ How many are returning?
+ How long is a person spending on the site?
+ What's the bounce rate?

**Comment by meiqimichelle** [comment]
I think @LisaGee you said this was covered and you were able to get what you needed from google analytics for now?

**Comment by ErieMeyer** [comment]
Confirmed on today's standup
