### ISSUE TITLE
Data site analytics: Searches completed

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#523]
As a product team member, I would like to see analytics for Searches completed

**Comment by LisaGee** [comment]
was "search" implemented?

**Comment by meiqimichelle** [comment]
I'm not sure. There was some talk around figuring out what analytics api.data.gov could provide but I don't remember who was meant to be looking into that. I have not been doing that. @diego- do you remember where we left that discussion?

**Comment by LisaGee** [comment]
I think this is for the Data Tool, not for the API. I believe this was for the Quick Query that got deferred.
@ErieMeyer to confirm.

**Comment by jjoteal** [comment]
Assigning to @ErieMeyer then per the note above.

**Comment by LisaGee** [comment]
Closing as analytics is implemented.
