### ISSUE TITLE
Data site analytics: Data from all search requests

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#525]
As a product team member, I would like to see analytics for data from all search requests (ie, I want to be able to answer "what's the most popular data summary/filter" etc)

**Comment by jjoteal** [comment]
Assigning @barkimedes to work in in coordination with the development team.

**Comment by LisaGee** [comment]
I think this is done.

**Comment by saintsoup52** [comment]
So... this can be extrapolated from the URLs but this is very hard without a separate software that can plug into google analytics API (e.g., Tableau). At VA we are implementing other methods (e.g., events, page titles, etc) to make this information accessible from a google analytics dashboard. I would encourage ED to adopt some GA techniques to make this more accessible (without downloading all the URL hits and breaking them with a data tool).
