### ISSUE TITLE
BUG: Ensure that the Filters are open and display on desktop and are separate from Start a New Search

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#533]
See design mockup for desktop:

![image](https://cloud.githubusercontent.com/assets/12192706/9449261/6f0f38a8-4a6f-11e5-9101-698ccb03ce11.png)

**Comment by meiqimichelle** [comment]
Related to #340.

**Comment by meiqimichelle** [comment]
This should be fixed on dev with #712

**Comment by ErieMeyer** [comment]
Looks great on dev

**Comment by ErieMeyer** [comment]
Looks great on staging!
