### ISSUE TITLE
As a consumer, I want a more clear name than "advantage factor" to understand threshhold earnings

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#534]
![screen shot 2015-08-24 at 3 13 19 pm](https://cloud.githubusercontent.com/assets/1626026/9449757/c11c64f6-4a72-11e5-81ff-66e5e8f4e56c.png)
![screen shot 2015-08-24 at 3 13 11 pm](https://cloud.githubusercontent.com/assets/1626026/9449758/c50f0a96-4a72-11e5-8b2e-e4afa3b6d79b.png)
![screen shot 2015-08-24 at 3 13 01 pm](https://cloud.githubusercontent.com/assets/1626026/9449763/c8689158-4a72-11e5-8991-bfd58c34d932.png)

This is a wording exploration, which I will own.

Building off of this issue: https://github.com/18F/college-choice/issues/400

**Comment by jjoteal** [comment]
@LisaGee was tackling this one, but it looks like "Advantage Factor" aka "Threshold Earnings" has been removed? Should I be replacing "Exceeds H.S. Only" with the new term Dana suggested -- "Increase in Earnings" ?

**Comment by ErieMeyer** [comment]
Yep -- that's the same.

Thank you!

**Comment by jjoteal** [comment]
Moving to accept then!

**Comment by ErieMeyer** [comment]
Looks good!

**Comment by ErieMeyer** [comment]
Looks good on staging!
