### ISSUE TITLE
BUG: Labels above filters should match labels above value snapshot graphics AND the labels above the graphics in the corresponding Individual School page sections

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#553]
In other words, the labels above these filters:

![image](https://cloud.githubusercontent.com/assets/12192706/9469020/c6658578-4b12-11e5-8491-57a0ee080362.png)

Should match the corresponding labels above the Value Snapshot graphics:
![image](https://cloud.githubusercontent.com/assets/12192706/9469035/d8597910-4b12-11e5-8b5e-129b20f3a618.png)

AND, those same labels should also be used on the Value Snapshot on the Individual School page:
![image](https://cloud.githubusercontent.com/assets/12192706/9469063/0602931a-4b13-11e5-8eb1-51af5fd3a351.png)

AND the same labels should be used when the individual metric is represented again in the corresponding expand/collapse section on the Individual School page, for example, Actual Cost:

![image](https://cloud.githubusercontent.com/assets/12192706/9469103/2f871b98-4b13-11e5-9581-99f191cd0982.png)

Assigning @ErieMeyer to make these FINAL consistent decisions.

**Comment by meiqimichelle** [comment]
@ErieMeyer @jjoteal I think this is easiest to resolve live -- going through the pages together and making sure things are the way they're supposed to be. Pick a time next week?

**Comment by ErieMeyer** [comment]
Will do -- also going to trick Dana into doing a review with me in advance.

**Comment by jjoteal** [comment]
Have taken a preliminary crack at fixing these so everything is consistent. @LisaGee @ErieMeyer I am noticing some layout issues with some of the longer phrasing. For example, see how the labels "Graduation Rate" and "Salary After Attending" are now running together in the value snapshot:

![image](https://cloud.githubusercontent.com/assets/12192706/9594689/644de582-502c-11e5-9b93-b62a5a89e5ab.png)

Do I have the license to come up with my own wording that might fit better? If so, I'll take a crack!

**Comment by jjoteal** [comment]
FYI -- this is also done. Unable to preview on Dev right now, but as soon as I can, will proof!

**Comment by jjoteal** [comment]
Looking good and moving to accept!

**Comment by jjoteal** [comment]
Still looks good!
