### ISSUE TITLE
BUG: When I click on Calculate Your Exact Net Price, it should open a New Tab, not replace the existing page I'm looking at.

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#568]
Win7, Chrome.

Steps to Repro:
1. Go to: https://federalist.18f.gov/preview/18F/college-choice/staging/school/?183123-Lakes-Region-Community-College
2. Under Costs See the Calculate Your Exact Net Price Button.
3. Click on it and see that the content of your current window is replaced.

Expected Results:
Should open in a new tab.

**Comment by meiqimichelle** [comment]
I pushed a quickfix to `dev` to resolve this. Should be live on dev, and will go to staging the next time we push.

**Comment by ErieMeyer** [comment]
Looks great!
