### ISSUE TITLE
BUG: Internal Server Error on ccapi-prod requests (from beta users)

### ISSUE THREAD

**Issue by diego-** [18F/college-choice#572]
However, I am returning nothing with most queries I have tried outside the school dev_category.  For example the following do not return results, many give "Internal Server Error" instead of empty result sets:

https://api.data.gov/TEST/ed/beta/school?fields=cost.avg_net_price.public&api_key= ... (dev_category = cost)
https://api.data.gov/TEST/ed/beta/school?fields=academics.program_percentage.agriculture&api_key= ... (dev_category = academics)
https://api.data.gov/TEST/ed/beta/school?fields=academics.PCIP01&api_key= ... (same as above query with variable name instead of developer_friendly_name)
https://api.data.gov/TEST/ed/beta/school?fields=student.admission_rate.overall&api_key= ... (dev_category = student)
https://api.data.gov/TEST/ed/beta/school?fields=enrollment.all&api_key= ... (developer_friendly_name where no dev_category is listed)

**Comment by diego-** [comment]
These work when nested under years. closing issue.

**Comment by diego-** [comment]
This one is still not working:

https://api.data.gov/TEST/ed/beta/school?fields=enrollment.all&api_key=

**Comment by ultrasaurus** [comment]
@diego- this is missing a "dev-category"

**Comment by ultrasaurus** [comment]
it needs to be specified as 'root' or 'school' or something

**Comment by ultrasaurus** [comment]
FYI: there is also no year specified, which led to my assumption that it is meant to be either 'root' or 'school'

**Comment by diego-** [comment]
added 'student' to data dictionary as enrollment.all dev-category. Acceptance test pending reindex.

**Comment by ultrasaurus** [comment]
confirmed that if dev-category is blank it is omitted.  I discoverd that Carnegie Classifications were also missing, and put them in "school" ... still in progress

**Comment by ultrasaurus** [comment]
this is on the dev server, pending code review by @yozlet

**Comment by ultrasaurus** [comment]
meaning we shouldn't move to staging & accept till after it's reviewed and merged, but @diego-  can take a look at it and see if it is as expected

**Comment by ultrasaurus** [comment]
just on dev, pls review!

**Comment by diego-** [comment]
tested using ope8_id without dev-category.
also tested negative case with 'name' without dev-category school. Returns real error message rather than internal server error.

works as expected!

Also, all fields in data dictionary now have a dev-category.
