### ISSUE TITLE
As a developer, I'd like to request a unique endpoint from the API to get all available query fields

### ISSUE THREAD

**Issue by diego-** [18F/college-choice#576]
Requested by beta user:

    Is the data dictionary spreadsheet the only source for looking field names, or is there any call to the    API itself which can return a list of possible field names with sources and notes / etc?

**Comment by ultrasaurus** [comment]
@diego- when you tell them about the new API, they can access /v1/data.json, but that doesn't show the nesting of the fields by year, so not marking this as resolved.
