### ISSUE TITLE
Remove Public/Private icon under Student Body section on School page

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#577]
Can't remember why we had this here?
@jjoteal @ErieMeyer can you remember why?
Doesn't feel like it jibes with Student Body.

**Comment by meiqimichelle** [comment]
This was a placeholder for the proper icon (size). It is ready fixed in the work on #293.

**Comment by jjoteal** [comment]
This icon should NOT be school type, it should be the SIZE icon. I believe Michelle was looking into this.



Sent with Good (www.good.com)


-----Original Message-----

**Comment by jjoteal** [comment]
reassigning to @meiqimichelle so she can close out when she also closes out the #293.

**Comment by LisaGee** [comment]
Fixed. closing.
