### ISSUE TITLE
As a site operator, I'd like to have automated testing to prevent regression bugs in future deployments

### ISSUE THREAD

**Issue by diego-** [18F/college-choice#595]

**Comment by ultrasaurus** [comment]
We have several issues around front end tests:
- https://github.com/18F/college-choice/issues/994
- https://github.com/18F/college-choice/issues/367
- https://github.com/18F/college-choice/issues/7

Open Data Maker has automated tests

For integrated API tests (Open Data Maker configured for College Choice), we have an open issue:  https://github.com/18F/college-choice/issues/938

**Comment by ultrasaurus** [comment]
closing as a duplicate.  

@diego- if you know of a gap for which there is no open issue, please write up something more specific -- thanks!
