### ISSUE TITLE
As a site operator, I'd like to use an uptime monitor like statuspage.io or pingdom to prevent downtime

### ISSUE THREAD

**Issue by diego-** [18F/college-choice#596]

**Comment by LisaGee** [comment]
@diego- @dnesting should ride shotgun.

**Comment by ultrasaurus** [comment]
I believe @ozzyjohnson is investigating what we can do here

**Comment by ozzyjohnson** [comment]
I got the OK to procure Pingdom on Friday. In the meantime we'll need to work with New Relic and/or the free version of Pindgom.

**Comment by dnesting** [comment]
Is there a reason we prefer to use a separate service when we're already planning on using New Relic?  It seems like there's a lot of overlap here.

**Comment by hollyallen** [comment]
@dnesting the meeting where this was discussed is written up here: https://docs.google.com/document/d/1IHs25wNe6OJJXhqR3MFXn-ZONPVJDiF8lAeCEIncGwE/edit 

Summary: New Relic has about a 3 minute latency on alerts. Ozzy says new relic isn’t good for downtime alerting. Something specific to alerting and synthetic transactions like pingdom is better and will alert a lot faster in the case of an issue.

**Comment by ozzyjohnson** [comment]
This is correct. Pingdom is a much more directed check and alerting tool to the application instrumentation, trending and dashboarding of New Relic. Though, for the time being New Relic and a trial period of their synthetic product is what we have to work with.

**Comment by hollyallen** [comment]
@ozzyjohnson  To clarify, do you think we'll have pingdom on production for Sept 11 or not?

**Comment by ozzyjohnson** [comment]
Yes, it's in place as of this evening. Still need to create alerts, but
it's bought.

**Comment by hollyallen** [comment]
Awesome!

**Comment by ozzyjohnson** [comment]
I created some basics, but I'll need address to send the alerts. A mail list is preferable, but I can deal with individual emails, twitter accounts (it will DM you), a webhook or a phone number (not ideal, SMS incurs a small fee).

Checking the frontend behind Federalist should be doable too assuming it just needs an auth header set and someone can tell me where it's getting auth list from (18F org?)

<img width="937" alt="screen shot 2015-09-05 at 9 38 24 am" src="https://cloud.githubusercontent.com/assets/3709182/9699481/db3cb02c-53b2-11e5-89c0-9bf17f0acc2f.png">

**Comment by ultrasaurus** [comment]
looks like this is all set -- @ozzyjohnson anything left to do here?

**Comment by ozzyjohnson** [comment]
Additional checks and escalations perhaps.

- The service is only doing uptime checks right now, it can do synthetics as well.
- Pingdom can do delayed notifications / escalations for different groups on a delay - to only notify after 30 minutes, 2 hours of downtime.
- Dashboarding?

I think we're covered on the intent of this issue though.

**Comment by ultrasaurus** [comment]
moving to accept
notifications currently go to slack, team has an account to view dashboard (sent via email)

note:  synthetics transactions -> https://github.com/18F/college-choice/issues/938

**Comment by barkimedes** [comment]
@hollyallen I feel like we can close this, but I don't want to pull the trigger in case I'm missing something. This OK to close?

**Comment by hollyallen** [comment]
Agreed, we can accept this and open new tickets to refine as desired.
