### ISSUE TITLE
BUG: Empty home page on Chrome on EOP Windows Citrix desktop

### ISSUE THREAD

**Issue by dnesting** [18F/college-choice#603]
Chrome 43.0.2357.132 m
Windows Server 2008 R2
Citrix VM

Loading https://college-choice.18f.gov gives me an empty page (zero-byte response).  Note that EOP MITMs this HTTPS connection and it's possible it's this process that's causing the problem.  IE 8 on the same system successfully retrieves a page.

**Comment by LisaGee** [comment]
ED has a similar problem and it ended up being the Group Policy Object on Chrome.. It's the specific configuration for a group of users or the entire enterprise for a tool. In this case, it's the GPO for the Chrome browser.
