### ISSUE TITLE
Importing new data

### ISSUE THREAD

**Issue by diego-** [18F/college-choice#604]

**Comment by LisaGee** [comment]
I think this was done on Friday 8/28/15. 
@diego- Can you confirm and Accept?

**Comment by diego-** [comment]
Latest data in S3 as of 8/27/15 per Clare. Not yet reingested as of 8/31/15 per @ultrasaurus.

**Comment by LisaGee** [comment]
@ultrasaurus Is there someone else on the team who can do this?

**Comment by ultrasaurus** [comment]
@LisaGee I'm testing it now.  How do I know it is good?  https://ccapi-ex.18f.gov/

**Comment by LisaGee** [comment]
I believe the only difference is:
RTI is fixing the files so that the CDR data are a decimal rather than a number.

To test, you should be able to use the Test Cases with Expected Results that @hollyallen has put together.
And maybe @hollyallen can do some spot checking too?

**Comment by ultrasaurus** [comment]
copied all the new data to dev, staging, production (plus ex and indexing enviornments) -- please verify dev, staging and production via api (ccapi-dev.18f.gov  ,  ccapi-staging.18f.gov, ccapi-production.18f.gov)

**Comment by ultrasaurus** [comment]
after this is verified on dev and staging, we should move to production and verify there

**Comment by hollyallen** [comment]
I am happy to do some testing, will wait until it is on prod.

**Comment by ultrasaurus** [comment]
I would like someone to spot check it on dev/staging, before moving to production

**Comment by LisaGee** [comment]
assigning @diego- to accept

**Comment by hollyallen** [comment]
Search on Dev looks good. (There is still the mystery of the 2 schools extra in a few categories, same as last week, possibly related to NULL attendance schools.)

Staging has 3580 schools (when no parameters passed in consumer tool), but the proper number is 3587.

**Comment by ultrasaurus** [comment]
I may have done something wrong when I indexed 18 years of data and transferred the index snapsot to staging... since I did that, we've automated more parts of the process.  I'm re-indexing tonight and will use the new snapshot / restore process tomorrow

**Comment by ultrasaurus** [comment]
pls test on staging which has all 18 years of data
