### ISSUE TITLE
BUG: Clicking share button does not trigger email program launch

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#605]
Mac Chrome (2:26pm)

![image](https://cloud.githubusercontent.com/assets/12192706/9502282/5be9f73c-4bfe-11e5-8be6-36e5b6882b74.png)

Steps to reproduce:
- Click on Share button on individual school page

**Comment by meiqimichelle** [comment]
Shawn pushed a fix for this to dev, but I don't think it's on staging yet.

**Comment by LisaGee** [comment]
@jjoteal which environment are you testing on? Staging or Production?

**Comment by LisaGee** [comment]
@jjoteal Can you confirm it works now?

**Comment by ErieMeyer** [comment]
Looks like this is addressed on staging and prod!
