### ISSUE TITLE
BUG: Long zip code results in error

### ISSUE THREAD

**Issue by liyanchang** [18F/college-choice#608]
Search for anything.
Use Zipcode: 999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
See error:
![screen shot 2015-08-26 at 2 31 41 pm](https://cloud.githubusercontent.com/assets/328073/9502398/0fd16e6a-4bff-11e5-8551-b503352bc2e0.png)

Firefox 39.0
1024x768
OSX 10.8.5

**Comment by LisaGee** [comment]
Should likely be solved the same was as #602 but both should be retested when fixed.

**Comment by ErieMeyer** [comment]
Is that somewhere in Virginia?

**Comment by yozlet** [comment]
Will handle as part of #529.

**Comment by LisaGee** [comment]
@yozlet Was this handled? Can it be closed?
