### ISSUE TITLE
BUG: Graphs are not working correctly, also why zero students?

### ISSUE THREAD

**Issue by m-hsiang** [18F/college-choice#609]
For the first two schools in the shot, the numbers are zero/NA, but the graphs show values

also, for the first school, there are no undergrads?

![image](https://cloud.githubusercontent.com/assets/7342162/9555811/de58088a-4d9d-11e5-979f-64fd2fa371eb.png)

**Comment by LisaGee** [comment]
Editing to be 2 stories:
1. 0 students (this one)
2. bar graph and label don't match: #589

**Comment by LisaGee** [comment]
Should be handled by #887
