### ISSUE TITLE
BUG: Chrome Android name search field has autofill for my name

### ISSUE THREAD

**Issue by dnesting** [18F/college-choice#610]
Chrome on Android.  At home page, under Name / School name, touch the text field to search for a school.  Chrome invokes its Autofill and prompts me to autofill with my own name.

Possibly the form field name is something generic like "name", which Chrome figures might mean my real name.  The presence of this autofill stuff is a little confusing and should be explicitly disabled if possible.

**Comment by ErieMeyer** [comment]
Screenshot pls?

**Comment by dnesting** [comment]
![image](https://cloud.githubusercontent.com/assets/7342162/9502654/a80d5fc6-4c00-11e5-93ad-ee17a36c914b.png)
