### ISSUE TITLE
BUG: Wording Suggestion

### ISSUE THREAD

**Issue by stephaniefaith** [18F/college-choice#613]
Recommend changing language from "Salary 10 years after" to "salary after 10 years"- otherwise we're ending the clause with a preposition.  This will improve the site- esp for an education website- grammar should be correct.

https://college-choice.18f.gov/school/?214591-Pennsylvania-State-University-Penn-State-Erie-Behrend-College

**Comment by LisaGee** [comment]
Thanks. This is actually supposed to read "Salary 10 Years After Entry".
Filed a ticket to make sure all copy is reviewed before Launch #888
