### ISSUE TITLE
BUG: Drop down box is super high on search results page

### ISSUE THREAD

**Issue by stephaniefaith** [18F/college-choice#619]
On 8/26/15 at 2:40 PM I searched for Erie college via IE on my PC and found two issues (in a 3 column spread) after "sort by", the drop down box is too high and should be right next to sort by (lower this).

(picture coming)

**Comment by liyanchang** [comment]
![snipimage](https://cloud.githubusercontent.com/assets/328073/9505290/9428abdc-4c0f-11e5-8868-adec2abc677e.JPG)

**Comment by LisaGee** [comment]
@stephaniefaith Which version of IE?

**Comment by stephaniefaith** [comment]
Vs 11

**Comment by barkimedes** [comment]
@stephaniefaith I believe that this is fixed now. Please feel free to reopen if you can reproduce the issue.  But I just tried it on IE11 on various widths and didn't see the problem. Thanks!
