### ISSUE TITLE
BUG: In a 2-col browser width, the Programs Drawer Label overlaps with + on search results page

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#622]
From @stephaniefaith:

On 8/26/15 at 2:40 PM I searched for Erie college via IE11 on my PC and found two issues (in a 3 column spread) and under "edit search criteria," the + sign is over the text called programs/d...... This looks like a bug!!

**Comment by liyanchang** [comment]
![2 bugs in 1 jpg](https://cloud.githubusercontent.com/assets/328073/9505228/281ea86a-4c0f-11e5-8264-52f829a600a8.jpeg)

**Comment by meiqimichelle** [comment]
Also note -- from that screen shot it looks like our font isn't pulling in on IE11, either.
