### ISSUE TITLE
BUG: Searching with a space gives bad results

### ISSUE THREAD

**Issue by liyanchang** [18F/college-choice#623]
If you search for "Anderson" you get 3 results that all make sense. If you try to be more specific and search for "Anderson University", you actually get more more results.

(Quick guess - your search is splitting the string and searching for them independently. For instance, searching for "University" gives you the same results as "Anderson University" or "University of California".)

![screen shot 2015-08-26 at 2 41 51 pm](https://cloud.githubusercontent.com/assets/328073/9502619/83e2f480-4c00-11e5-977e-27a97f8a9290.png)

![screen shot 2015-08-26 at 2 41 56 pm](https://cloud.githubusercontent.com/assets/328073/9502620/83e3452a-4c00-11e5-9811-8b8634b0d6d7.png)

![screen shot 2015-08-26 at 2 43 45 pm](https://cloud.githubusercontent.com/assets/328073/9502738/0981b464-4c01-11e5-9efd-8a05fb03ebc0.png)

![screen shot 2015-08-26 at 2 46 08 pm](https://cloud.githubusercontent.com/assets/328073/9502761/18d1d9da-4c01-11e5-8885-0c9c9e6ef360.png)

**Comment by sullivanse** [comment]
I had the same outcome searching Boston University in IE.  I received 1400 results, and none of the schools on the first few pages had "Boston" in their name.

**Comment by liyanchang** [comment]
Thinking about this more. The search currently seems to be a union of the individual words [0]. Especially strange with the word "of" #656. This would be ok, however, you then sort by "advantage factor", which then buries the result you are looking for in 1407 results.

Suggestion: If you are searching by name, you sort by relevance to the name. If no name is specified, then default to "advantage factor".

[0] This is true because searching for "university" gets 1407 results, "mckenna" brings up one result, "mckenna unversity" results in 1408 results.

**Comment by LisaGee** [comment]
Solved by #41
