### ISSUE TITLE
BUG: NO ARROW NEXT TO GO BACK TO SEARCH RESULTS

### ISSUE THREAD

**Issue by stephaniefaith** [18F/college-choice#628]
At 2:47 PM on 8/26/2015 on my PC using IE vs 11, I noticed the go back to search results does not include a pretty arrow before it HOWEVER that same pretty arrow was on my Samsung 6 mobile device via Firefox! When I first saw it on my PC, I actually thought "an arrow would be really nice here" but didnt issue a bug til I saw the mobile version has the arrow I dreamed of!!

**Comment by liyanchang** [comment]
![back to search results](https://cloud.githubusercontent.com/assets/328073/9505233/36878264-4c0f-11e5-9747-c651ebcdfaaf.PNG)
