### ISSUE TITLE
BUG: Family income averages don't convey information how we expect

### ISSUE THREAD

**Issue by m-hsiang** [18F/college-choice#630]
The data for the cost estimates by family income seems to report off of actual data- so when there are no students it doesn't calculate and show something that is useful.  See zeros in the screenshot
<img width="960" alt="screen shot 2015-08-26 at 2 47 05 pm" src="https://cloud.githubusercontent.com/assets/1036641/9502867/ba5b0ff6-4c01-11e5-84fb-e2f961ac4c15.png">

**Comment by LisaGee** [comment]
Should be taken care of by #887
