### ISSUE TITLE
BUG: Zip code search not working?

### ISSUE THREAD

**Issue by liyanchang** [18F/college-choice#632]
https://college-choice.18f.gov/search/?name=Harvard&zip=02139&distance=300&sort=advantage:desc

![screen shot 2015-08-26 at 2 52 42 pm](https://cloud.githubusercontent.com/assets/328073/9502911/f261a9b4-4c01-11e5-8218-9ec0739dab96.png)

**Comment by LisaGee** [comment]
Captured by bigger ticket #567
