### ISSUE TITLE
BUG: trucates zip codes

### ISSUE THREAD

**Issue by liyanchang** [18F/college-choice#637]
https://college-choice.18f.gov/search/?state=MA&zip=02139&sort=advantage:desc

02139 -> 2139 if you hit the url above. It works if you type in 02139 into the zipcode bar. It's probably being dropped on your url parameters to render functions.

![screen shot 2015-08-26 at 2 56 27 pm](https://cloud.githubusercontent.com/assets/328073/9502988/6ed54870-4c02-11e5-8bcb-5d14445cc8ad.png)

**Comment by LisaGee** [comment]
@liyanchang - Sorry, I'm not sure where I should be looking to see the issue. Can you augment ticket with Steps to Repro? Thanks.

**Comment by barkimedes** [comment]
@liyanchang Closing this issue as resolved. When I go to https://collegescorecard.ed.gov/search/?state=MA&zip=02139&sort=advantage:desc and then expand the "Edit Search" section, I see the correct 0-prefixed zip code in the zip code field. Feel free to reopen (and add more details) if I misinterpreted the bug. Thanks!
