### ISSUE TITLE
BUG:  After searching schools, no data showing for "average annual cost" and "graduation rate"; IE; 3:00PM

### ISSUE THREAD

**Issue by sullivanse** [18F/college-choice#643]
After searching for schools and the cards for various schools showed up, the info for "average annual cost" and "graduation rate" was blank.   For the first few schools, the info for "salary 10 years after" was also blank.

I was using IE around 3:00pm.

**Comment by liyanchang** [comment]
![image001](https://cloud.githubusercontent.com/assets/328073/9505209/12fdbae8-4c0f-11e5-89ef-4de6f3c2fd40.png)

**Comment by LisaGee** [comment]
Should be addressed by #273
