### ISSUE TITLE
BUG: Doesn't seem like all of the data is loading when I search for small schools

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#648]
Mac Chrome (3:05pm)

**Comment by LisaGee** [comment]
@jjoteal Is it better now that we have the Data Not Available state?

**Comment by ErieMeyer** [comment]
Looks like this has been addressed! Also, we may want to do a blog post about why some schools have "data not available" since folks will want to know more details. I'll follow up with Clare offline.
