### ISSUE TITLE
BUG:  Graphs are not filling in on the panels, even though data is pulling in

### ISSUE THREAD

**Issue by sullivanse** [18F/college-choice#653]
On IE, accessing this URL at 3:10pm: https://college-choice.18f.gov/search/?name=%22boston%20university%22&sort=name:asc

The graphs are not filling in for "average actual cost", "graduation rate", and "average salary after 10 years" even though data is pulling in for these fields.

**Comment by liyanchang** [comment]
![image001](https://cloud.githubusercontent.com/assets/328073/9505183/eae55b2e-4c0e-11e5-8c50-97d333fdade3.png)

**Comment by LisaGee** [comment]
Should be addressed by #273
