### ISSUE TITLE
Bug: White space when expanding

### ISSUE THREAD

**Issue by liyanchang** [18F/college-choice#654]
Go to:
https://college-choice.18f.gov/search/?state=DE&major=resources&size=small&sort=advantage:desc

White space shows up because the results div is shorter than the left bar.

![screen shot 2015-08-26 at 3 11 04 pm](https://cloud.githubusercontent.com/assets/328073/9503419/d8ec080a-4c04-11e5-928e-e4e917feb586.png)

![screen shot 2015-08-26 at 3 12 00 pm](https://cloud.githubusercontent.com/assets/328073/9503415/d120bbb6-4c04-11e5-9d01-36a2ff239983.png)

Firefox and Chrome on OSX. 1024x768

**Comment by meiqimichelle** [comment]
This was resolved a while back. Moving to accept, although we might just want to close since the drawer implementation changed this layout quite a bit. Might be less an 'accept' and more a 'no longer relevant'.

**Comment by ErieMeyer** [comment]
👌🏽
