### ISSUE TITLE
BUG: map for rural school is mostly blank and ugly

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#655]
iPad, Safari, https://college-choice.18f.gov/school/?173258-Carleton-College

Carleton is admittedly in a pretty rural area, but combined with the black and white gradient the map hardly looks like anything.
![image](https://cloud.githubusercontent.com/assets/8903924/9503467/159b3992-4c05-11e5-97a0-58413c0dabbc.jpg)

**Comment by LisaGee** [comment]
Should be addressed by #620
