### ISSUE TITLE
Bug: University of Wisconsin-Madison showing wrong schools when searching. 

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#656]
https://college-choice.18f.gov/search/?name=University%20of%20Wisconsin-Madison&sort=advantage:desc

On chrome on dell at 3:13 pm with screen size set to one column, when I search for "University of Wisconsin-Madison" there are 1,815 results but Wisconsin isn't even on the first page of results.

**Comment by liyanchang** [comment]
![search didn t work correctly for wisco](https://cloud.githubusercontent.com/assets/328073/9507140/2edf47ee-4c1a-11e5-93a2-24acf85a4930.png)

**Comment by LisaGee** [comment]
Should be solved by #41
