### ISSUE TITLE
As a student, I would like to be able to quickly expand all of the info sections on a school's page so that I can quickly and easily see all of the information

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#658]
I can open each info section by clicking a plus button, but I wish I could expand all at once with one click.

**Comment by LisaGee** [comment]
@kimballce Where you talking about exactly? Which page? Could you provide a URL? Thanks.

**Comment by barkimedes** [comment]
@kimballce Would the following be an accurate story description of what you're asking for?

As a student, I would like to be able to quickly expand all of the info sections on a school's page so that I can quickly and easily see all of the information.

**Comment by kimballce** [comment]
Yes, that looks great!
