### ISSUE TITLE
BUG: Selectivity info is 0 for "University of Phoenix-Western Washington Campus"

### ISSUE THREAD

**Issue by dnesting** [18F/college-choice#659]
On Chrome/Android, when pulling up details for this university, all of the test scores under Selectivity are zeros.

**Comment by dnesting** [comment]
![image](https://cloud.githubusercontent.com/assets/7342162/9503583/d5189896-4c05-11e5-80f7-7ee7e162ff52.png)

**Comment by LisaGee** [comment]
Should be addressed by #528
