### ISSUE TITLE
BUG: a house icon is used to symbolized "medium" and "large"

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#661]
iPad, Safari
I'm not sure what a house icon is supposed to convey to me about size in general. But also the same icon is use of to symbolize different things

https://college-choice.18f.gov/school/?173258-Carleton-College
![image](https://cloud.githubusercontent.com/assets/8903924/9503657/67093364-4c06-11e5-8365-064cbff2190a.jpg)

https://college-choice.18f.gov/school/?230038-Brigham-Young-University-Provo
![image](https://cloud.githubusercontent.com/assets/8903924/9503677/7c26cbd0-4c06-11e5-814d-1e21ee6354a6.jpg)

**Comment by LisaGee** [comment]
Should be solved by #293
