### ISSUE TITLE
BUG: SAT scores are illegible when they overlap with the end of the range 

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#666]
iPad, Safari
Also, when they're close to edge, the numbers also look confusing

https://college-choice.18f.gov/school/?173258-Carleton-College
![image](https://cloud.githubusercontent.com/assets/8903924/9504120/c0bda8ca-4c08-11e5-954f-bfb01e17ab45.jpg)

https://college-choice.18f.gov/school/?230038-Brigham-Young-University-Provo

![image](https://cloud.githubusercontent.com/assets/8903924/9504129/da3e1460-4c08-11e5-83ff-b2e73809ddfc.jpg)

**Comment by LisaGee** [comment]
Overlap should be handled by #102
