### ISSUE TITLE
Design review: mobile homepage

### ISSUE THREAD

**Issue by meiqimichelle** [18F/college-choice#67]
@jjoteal I updated the mobile homepage with many tweaks to get closer to your work. It is time for you to find everything I missed!

To kick things off, I have two obvious things to fix:

=============

**Methinks that you intended a smaller font size on mobile for the buttons. Right now we have:**
![screenshot 2015-07-01 19 30 01](https://cloud.githubusercontent.com/assets/4827522/8469092/dde8c1e2-2029-11e5-83e5-bd824aa9cb8a.png)

==============

**Likewise, you perhaps intended smaller buttons overall. Right now the buttons are a set width, but that causes problems at smaller screen sizes:**
![screenshot 2015-07-01 19 40 14](https://cloud.githubusercontent.com/assets/4827522/8469098/f71bc1dc-2029-11e5-8c82-846f909109f5.png)

**Comment by jjoteal** [comment]
@meiqimichelle to answer your immediate questions:

1) The font styles for the yellow buttons should be 16px bold #040404 with 200px letter spacing

2) In terms of the button width, this will vary depending on the button, so there is no hard-and-fast rule here unfortunately. We'll have to tackle these on a case-by-case basis. Let me know if this causes a lot of headache on your end.

Will do a more thorough design review of the full mobile page after this interview!

**Comment by jjoteal** [comment]
And here is the full design audit of the mobile homepage:

1) The height of the mobile header should only be ~84px. Right now it is over 100px. 
![image](https://cloud.githubusercontent.com/assets/12192706/8484104/ab6c1c1a-20c3-11e5-8b10-44eb6c0c6797.png)

2) The height of the search sections (i.e. the space between each of the horizontal rules) should only be ~52px. They look taller than that on staging.
![image](https://cloud.githubusercontent.com/assets/12192706/8484133/eb5ee0d2-20c3-11e5-811b-79b009ce4e07.png)

3) The plus and minus symbols are not centered in the circles for the expand/collapse icons:
![image](https://cloud.githubusercontent.com/assets/12192706/8484153/0426de6c-20c4-11e5-8042-a3f0acb350e0.png)

4) The Find Schools button height should be ~55px. Seems too short on staging:
![image](https://cloud.githubusercontent.com/assets/12192706/8484176/343a503e-20c4-11e5-938c-c56af78f8872.png)

5) The "Help Me Find Schools Best Suited to Me" button is still missing the text break on Mac Chrome. There should be a break between "Schools" and "Best"
![image](https://cloud.githubusercontent.com/assets/12192706/8484207/5e1b4962-20c4-11e5-92b5-44c5b6a33033.png)

6) The height of the "Help Me Find Schools Best Suited to Me" button should be ~76px. Seems shorter on staging:
![image](https://cloud.githubusercontent.com/assets/12192706/8484227/76b8ef6a-20c4-11e5-8150-89bcc2ba9897.png)

7) The "Did You Know" section has been renamed "By the Numbers" (see comp: https://drive.google.com/open?id=0B7PnaabiGCy5T0ZtbmNPTTk1czg). Also, looks like there is still text styling to be done here, so I won't give any feedback on that yet.
![image](https://cloud.githubusercontent.com/assets/12192706/8484281/bb4a290a-20c4-11e5-8dc1-c41c75c5dde5.png)

8) The "By the Numbers" section has been renamed "Check Out These Schools". There should be ~14px white space above the Noun Project icon and ~20px white space between the last row of text and the horizontal rule

9) The buttons in the Paying for College section should be 280px wide. Shoot, and I just double-checked the font size there and it is actually 12px bold #040404 with 200px letter spacing, so ignore my comment above!
![image](https://cloud.githubusercontent.com/assets/12192706/8484357/3fc28b82-20c5-11e5-80b6-c2c5dd10962f.png)

10) The "U.S. Department of Education" text in the footer, still seems a little off. Can you confirm that it is 12px bold #666 with 100px letter spacing? I think it's missing the bold?
![image](https://cloud.githubusercontent.com/assets/12192706/8484383/758069ba-20c5-11e5-86b8-1193dc463fde.png)

11) In the expanded search, I'm assuming the dropdown menus haven't been styled yet?

12) In the Name search, could we enter some default text in the field? Perhaps "e.g. USA University"? I know content folks will have opinions on this...

13) Mile radius should be a dropdown with options. Perhaps for now we have 25, 50, 100, 200, 300, 400, 500, 500+ ? Content folks will need to make that final determination.

14) In the Major search, I was hoping that the user could start typing a major and then it would be a "smart search" and autodetect what the user was typing with a list of suggested options. Also, could the label say "Specify a major"

15) In the Degree search, we should list Bachelors, Associates, and Certificate

16) Per the data folks, it doesn't sound like we have a metric for Student-to-Faculty ratio, so we should kill this.



I know that's a lot.... I'll take a look again once these adjustments have been made.

**Comment by meiqimichelle** [comment]
Tracking progress here:

1. Adjusted header to shrink at mobile sizes.

...more to come...

**Comment by meiqimichelle** [comment]
Answers to questions from above from conversation in another channel:

1. It is 20px between the bottom of every `li` and its respective horizontal rule
1. Hold on making this perfect as the design is likely changing and the yellow buttons might disappear entirely.
1. Make the buttons maintain the small-screen padding at 20px right-left and otherwise fill the space between.
1. Yep, still way off on the plus/minus centering.

**Comment by jjoteal** [comment]
Hi @meiqimichelle - here's a list of the issues I am still seeing this morning:

1) + and - symbols in expand/collapse still not aligning properly:
![image](https://cloud.githubusercontent.com/assets/12192706/8549034/8c46d9b6-2496-11e5-8717-11041c9de115.png)

2) The "Advanced Search" text  seems to have some sort of "residue" around it -- like an outer shadow or something gray & fuzzy?
![image](https://cloud.githubusercontent.com/assets/12192706/8549117/faa119d0-2496-11e5-95eb-96694207a9e2.png)

3) Just noting here that the "By the Numbers" section is still not styled, so I am unable to conduct a design audit for this section.

4) Just as a heads up, the content in the "Check Out These Schools" section will be links

5) Ensure there is ~14px space between the noun project icon and the top of the text in the individual listings in the "Check Out These Schools" section

6) Just noting here that the "Paying for College" section will be changing per a conversation with Lisa & Erie yesterday.

**Comment by meiqimichelle** [comment]
I have a PR coming that addresses:

1. Spacing in the 'check out these schools' section -- 14px above and 20px below
1. Another shot at the + spacing
1. Base styles for the 'by the numbers section'
1. Fuzzy Advanced Search -- I think it is something with the font rendering in that color on white.
1. Buttons should now fill their containers at small sizes and display at 100% of width rather than continuing as a set width as in wider implementations.

**Comment by jjoteal** [comment]
@meiqimichelle let me know when you need me to do another review!

**Comment by jjoteal** [comment]
@meiqimichelle -- here is a clipped screenshot of revised mobile and desktop homepage with the new "Paying for College" single promo for CFPB. Please note that in order to keep the columns even on the desktop version, I needed to add 1 additional listing in the "Check Out These Schools" section -- so there are now 4 "listings" vs. just 3.

![image](https://cloud.githubusercontent.com/assets/12192706/8640225/e43a4028-28be-11e5-98ab-43b4927e47d0.png)

![image](https://cloud.githubusercontent.com/assets/12192706/8640224/d1c7f228-28be-11e5-8c1c-27078a7d7cf6.png)

**Comment by meiqimichelle** [comment]
@jjoteal I think I've transferred all the remaining tasks from this list to separate issues, as we talked about last Friday. Please feel free to add if I've missed anything! Several are ready for your review but I didn't assign them to you since I'm not sure where Lisa will place them in the prioritization. 

How do you think we should a design implementation when it still has fine-tuning? What I mean is -- do we now (or, when we're ready) que up an issue about mobile layout home for acceptance?

**Comment by jjoteal** [comment]
@meiqimichelle i think once we've resolved all of the mobile design issues, we create a new issue for homepage mobile layout acceptance.

**Comment by meiqimichelle** [comment]
@jjoteal The challenge for me is to figure out how to share/accept "halfway". It sounds like @LisaGee wants a midway-through acceptance. As in, a point at which she chooses when a design bug is prioritized to fix or not, and in the meantime we move on to another part of the site. If we wait for acceptance till all the bugs are fixed, that won't work with what she wants.

**Comment by jjoteal** [comment]
@meiqimichelle perhaps we assign all bugs to the backlog as well so then @LisaGee can prioritize them? Let's plan on discussing how to best handle this during today's stand-up.

**Comment by meiqimichelle** [comment]
@jjoteal Sounds good! FWIW, I think all the bugs *do* go to backlog now. We will ask Lisa how she wants to be notified of the still-buggy designs.

**Comment by meiqimichelle** [comment]
@jjoteal As per our discussion at standup yesterday, should we close this issue in favor of the bugs we filed? We could also open another issue called "Consumer tool mobile design MVP" or something for Lisa's acceptance.

**Comment by jjoteal** [comment]
Closing issue as all items have been moved to separate issues.
