### ISSUE TITLE
BUG (design enhancement): use consistent orientation in the student body section

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#674]
The type of institution icon is primarily a vertically aligned image, whereas the layout of the number of undergraduates text is horizontal. Put together, the juxtaposition feels more cobbled together than visually streamlined. I recommend creating a icon with stronger horizontals.

![image](https://cloud.githubusercontent.com/assets/8903924/9504820/af4a314a-4c0c-11e5-985a-c85031ab6ef3.jpg)

**Comment by barkimedes** [comment]
@kimballce I *think* what you're saying has been addressed in that (regardless of width), things are generally centered. Would you say that it looks consistent enough to close the issue? :wink: 

(This image is at a window width that seems comparable to the original issue)

<img width="451" alt="screen shot 2015-11-12 at 12 36 46 am" src="https://cloud.githubusercontent.com/assets/1174867/11111284/83800b7e-88d5-11e5-90ff-0e067812f981.png">
