### ISSUE TITLE
BUG:  how do we want to portray "no data" instead of 0?

### ISSUE THREAD

**Issue by m-hsiang** [18F/college-choice#676]
Eg, many places where it says 0, the answer is not actually 0, there is just no data.  

<img width="840" alt="screen shot 2015-08-26 at 3 03 40 pm" src="https://cloud.githubusercontent.com/assets/1036641/9506004/7e30b7bc-4c13-11e5-8fd6-74f46aeb0cd5.png">

**Comment by LisaGee** [comment]
Should be resolved by #273
