### ISSUE TITLE
Bug: Graph not matching numbers 

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#678]
On Dell desktop, at 5:32, with google chrome, screen size is one column. 

https://college-choice.18f.gov/search/?completion_rate=0..0.13&sort=advantage:desc&page=5 

When changing the graduation rate percentage to a low number several school's picture graphs do not match the numbers.

![image](https://cloud.githubusercontent.com/assets/7342162/9555683/bc825af4-4d9c-11e5-9770-b51df7afd67e.png)

**Comment by LisaGee** [comment]
this link now shows Data Not Available for 0%
