### ISSUE TITLE
BUG: Average Actual Cost and Graduation Rate are 0 for UMD-BC

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#687]
Edge browser; Windows 10.

Pretty sure that wouldn't be the average actual cost and graduation rates shouldn't actually be as they appear here:
https://college-choice.18f.gov/school/?163259-University-of-Maryland-Baltimore

**Comment by LisaGee** [comment]
The data appears to be Not Available. Display issue solved by #273
