### ISSUE TITLE
BUG: Average Cost hovertext is showing for all three bars

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#688]
Edge Browser and Chrome; Windows 10

Average Cost hovertext appears for Graduation Rate and Salary 10 Years After
https://college-choice.18f.gov/school/?163259-University-of-Maryland-Baltimore

![image](https://cloud.githubusercontent.com/assets/7342162/9555532/a3138b52-4d9b-11e5-8a55-9fff0e7592e1.png)

hrk

**Comment by LisaGee** [comment]
Handled by #420
