### ISSUE TITLE
BUG: Hovertext over labels of National Average Lines

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#689]
Edge Browser; Windows 10.

When I hover over $17,706, hover text with "value:" and "median:" is unnecessary and confusing. This happens over many of the labels for the average lines.
https://college-choice.18f.gov/school/?166656-MCPHS-University

![image](https://cloud.githubusercontent.com/assets/8903924/9511136/47c9cb36-4c41-11e5-9c48-f7a59041d623.png)
hrk

**Comment by LisaGee** [comment]
Related to #448 .
Consider removing the hover over graphs altogether.

**Comment by barkimedes** [comment]
I think they've been removed. Closing as resolved (please someone reopen if this was a mistake on my part!)
