### ISSUE TITLE
BUG: Hovertext "Above Average" appears over up arrow for "Average Actual Cost"

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#690]
Edge browser; Windows 10.

Don't need hovertext "Above Average" when hovering over red up arrow.
https://college-choice.18f.gov/school/?166656-MCPHS-University

![image](https://cloud.githubusercontent.com/assets/7342162/9555434/0ed34112-4d9b-11e5-9abc-ca49d430e8cf.png)

hrk

**Comment by LisaGee** [comment]
consider removing hover from graph

**Comment by barkimedes** [comment]
Is there still a hover on the graph? I don't see it (chrome, mac), but I don't know if that's a feature that was removed or if I'm just not doing it right. Can someone confirm this isn't an issue anymore? Then we can close it :grin:

**Comment by barkimedes** [comment]
See #448
