### ISSUE TITLE
BUG: Hovertext "Average Actual Cost" appearing for "Students Paying Down Their Debt"

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#691]
Edge browser; Windows 10.

Hovertext for "Students Paying Down Their Debt" is the text for "Average Actual Cost".
https://college-choice.18f.gov/school/?166656-MCPHS-University

![image](https://cloud.githubusercontent.com/assets/8903924/9511261/abdf5d56-4c42-11e5-8e57-7dada5d18968.png)
hrk

**Comment by LisaGee** [comment]
Handled by #420
