### ISSUE TITLE
BUG: Hovertext "Graduation Rate" appearing for "Race/Ethnicity" in "Student Body"

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#695]
Edge browser; Windows 10.

Hovertext for "Graduation Rate" appears when I hover over "Race/Ethnicity"
https://college-choice.18f.gov/school/?166656-MCPHS-University
![image](https://cloud.githubusercontent.com/assets/7342162/9555507/758c5916-4d9b-11e5-89ee-580e22672feb.png)

hrk

**Comment by LisaGee** [comment]
Should be addressed by #420
