### ISSUE TITLE
BUG: Hovertext "Graduation Rate" appearing for "Test Scores" in "Selectivity" section

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#696]
Edge browser; Windows 10.

Hovertext "Graduation Rate" appears when I hover over "Test Scores" in "Selectivity" section.
https://college-choice.18f.gov/school/?166656-MCPHS-University
![image](https://cloud.githubusercontent.com/assets/7342162/9555493/5d068650-4d9b-11e5-898a-6b8aa7077293.png)

hrk

**Comment by LisaGee** [comment]
Should be addressed by #420
