### ISSUE TITLE
BUG: Nevada State College data question

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#699]
Edge browser; Windows 10.

They are listed 15th most when sorted by threshold earnings in this search:
https://college-choice.18f.gov/search/?&major=psychology&degree=b&size=medium&sort=advantage:desc

But their graduation rate is low, so that's surprising.

**Comment by LisaGee** [comment]
Well... Multiple things here:
1. Salary 10 years after entry is now displayed as Data Not Available.
2. I agree that it is very odd that they do so well by Threshold earnings, but have a graduation rate of 15%. This does match what's in the data file. Will check with Clare on the data itself. Editing Story to reflect this issue.

**Comment by LisaGee** [comment]
I just have a guess here, which is that they have a pretty high percentage of adult students (58%) and a high percentage of part-time students (62%). Most likely a lot of their students are already working while in the program, so they’re close to/exceeding the threshold when they start. Even if they don’t finish, they may already be on track to hit about the average for a high school graduate.
