### ISSUE TITLE
BUG: On Desktop, need to do something with the 21st slot of the page on search results page.

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#701]
Edge browser; Windows 10.

Because there are 20 results per page, but they are arranged in a 3x7 grid, there is a blank in the last spot on each results page. Confusing - makes it seem like you are at the end of the results. Make 21 results per page to fill out grid.
https://college-choice.18f.gov/search/?&major=psychology&degree=b&size=medium&sort=advantage:desc&page=0

hrk

**Comment by LisaGee** [comment]
If it's more work to change the paging of the results, we should figure out something else to do with that last slot, as having it be empty makes it look like there are no more results. 
@jjoteal at a minimum, let's design some kind of graphic that we can put in there.

**Comment by meiqimichelle** [comment]
Now that we're showing 4-up schools on the results page, I think this is OBE. That last slot should be filled now. Moving to accept.

**Comment by LisaGee** [comment]
Closed b/c we're now 4 columns wide and there is no more empty slot.
