### ISSUE TITLE
BUG: "Share" to Google Chrome just opens google.com

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#702]
Edge browser and Chrome; Windows 10.

When I click "Share", then "Google Chrome", it just opens Google Chrome to google.com

![image](https://cloud.githubusercontent.com/assets/7342162/9555310/2b45cb9a-4d9a-11e5-8885-5dbf8f16dfdc.png)

hrk

**Comment by LisaGee** [comment]
@kimballce Do other "mailto:" links work on this same computer?

**Comment by kimballce** [comment]
Pretty sure this is just a quirk of my new, not fully configured computer. Closing.
