### ISSUE TITLE
BUG: "Share" application icons are pixelated

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#703]
Edge browser and Chrome; Windows 10.

These icons for Chrome, Mail, etc. look pretty pixelated.
![image](https://cloud.githubusercontent.com/assets/7342162/9555293/107a75cc-4d9a-11e5-9bae-e2abd0afa65a.png)

hrk

**Comment by LisaGee** [comment]
@kimballce What's the "Edge" browser?

**Comment by kimballce** [comment]
Edge is the new, default web browser for Windows 10. (https://technet.microsoft.com/en-us/library/Mt156988(v=VS.85).aspx)

**Comment by meiqimichelle** [comment]
For the record, this display is not something we control on our end. I'm guessing that's the default display when you click on a `mailto` link in Edge.

**Comment by kimballce** [comment]
I think you're correct. I'll close this.
