### ISSUE TITLE
BUG: Bar graphs showing even for 0-values or no values

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#704]
Edge browser; Windows 10.

When I click the double arrows to see the last results
![image](https://cloud.githubusercontent.com/assets/8903924/9512304/1ad8fbda-4c4e-11e5-8ac6-1ea8a1b6a61a.png)

It takes me to a page where many of the results have either 0-values or no values, but still show positive bar graphs:
![image](https://cloud.githubusercontent.com/assets/7342162/9555247/dd4dc294-4d99-11e5-9380-ce780780c30e.png)

When I refresh the page, the positive bar graphs go away:
![image](https://cloud.githubusercontent.com/assets/7342162/9555263/ee1ae020-4d99-11e5-9c8f-5ca3e3c0f462.png)

hrk

**Comment by LisaGee** [comment]
@kimballce Can you try again? I think this has been resolved, but would like to confirm. Thanks!

**Comment by kimballce** [comment]
@LisaGee , yes it appears to be resolved. Data showed up on the first page load, and the "Data Not Available" tag clears up the confusion.

**Comment by ErieMeyer** [comment]
Woo hoo!
