### ISSUE TITLE
BUG (content): homepage - criteria are plural

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#707]
Homepage should read "Enter criteria that are important to you" under "Find Schools By:"
![image](https://cloud.githubusercontent.com/assets/8903924/9512459/17e62a5e-4c50-11e5-8c79-ca7aa4f2d0eb.png)
hrk

**Comment by LisaGee** [comment]
@ErieMeyer - Can you make this sentence more user friendly and attuned to our audience, but also grammatically correct?

**Comment by ErieMeyer** [comment]
Yes! Switching to "Enter things that are important to you." for now. PR comin.

**Comment by kimballce** [comment]
@ErieMeyer personally I still prefer "Enter criteria that are important to you" . It's more specific, and the audience knows what criteria are. My (Heather's) point was just that the "is" should be changed to "are".

**Comment by LisaGee** [comment]
Should be taken care of in #888
