### ISSUE TITLE
BUG: Program/Degree list is missing some basic categories, like Economics

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#715]
Economics was my major in college, but I don't see it listed as an option.

![image](https://cloud.githubusercontent.com/assets/8903924/9520657/0799c60a-4c97-11e5-9cd3-95c84165e2d1.png)

**Comment by LisaGee** [comment]
@claremcann - What category would Economics fall under?

**Comment by LisaGee** [comment]
Should be handled by #144
