### ISSUE TITLE
ENHANCEMENT: The original search results designs had the 2-year or 4-year indicators at the top of the card. Should we consider displaying so it is more obvious whether a school is a 2-year or 4-year?

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#720]
Original design:

![image](https://cloud.githubusercontent.com/assets/12192706/9530057/a9bcf2c0-4ccb-11e5-89f2-4725a24cf6c3.png)

Assigning @LisaGee for a decision.

**Comment by barkimedes** [comment]
There are pretty clear indicators that a school is 2 or 4 years from the icon set at the top.

**Comment by LisaGee** [comment]
@barkimedes – I think this was referring to the Search Results page, which at the moment, does not indicate what “type” a school is: 2 or 4 year or public, private or for profit, ….
