### ISSUE TITLE
ENHANCEMENT: New style for special designation on school page

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#723]

**Comment by LisaGee** [comment]
@jjoteal -- Not sure exactly what this is referring to, so not sure how to prioritize it. Can you provide a bit more context? Thanks.

**Comment by jjoteal** [comment]
Sorry @LisaGee , this was me being fast to record the item during stand up yesterday. This is a new ticket to change the style of things like "HCBU" on the individual school page to something other than black text that is highlighted in yellow. This style would also be used for religious affiliation.

**Comment by LisaGee** [comment]
@jjoteal Is the new design done? Is this ticket just for implementation?

**Comment by LisaGee** [comment]
@jjoteal And is this ticket different from #724

**Comment by jjoteal** [comment]
@LisaGee here is the new design:

![image](https://cloud.githubusercontent.com/assets/12192706/9588059/fd9c1076-4ff3-11e5-881d-1dc9e690e2c3.png)

Was thinking these "chicklets" would be the same design for special mission and religious affiliation as shown. So yes, it is technically a dupe of #724.

If you are ok with this design, please reassign to Michelle for implementation.

**Comment by LisaGee** [comment]
I'm good.

**Comment by meiqimichelle** [comment]
Should be live in dev with #966

**Comment by meiqimichelle** [comment]
<img width="873" alt="screen shot 2015-09-01 at 11 57 55 am" src="https://cloud.githubusercontent.com/assets/4827522/9613600/2f7f026c-50a1-11e5-9351-35e91da6b849.png">

**Comment by ErieMeyer** [comment]
Looks great on dev!

**Comment by ErieMeyer** [comment]
🇺🇸🇺🇸
