### ISSUE TITLE
Bug: Back button in search results doesn't work.

### ISSUE THREAD

**Issue by hollyallen** [18F/college-choice#725]
Today 8/27/2015 1:51pm on Staging (https://federalist.18f.gov/preview/18F/college-choice/staging/)
Firefox 40.0 on Mac

Steps to reproduce:
1. Search for colleges, get a list of results (A)
2. Refine your search in the search results page, get a new list of results (B)
3. Click the Back button on the browser

Expected result: URL changes, results list changes from B to A
Actual result: URL changes, but result list is still B

**Comment by LisaGee** [comment]
Seems realted to #645

**Comment by LisaGee** [comment]
Not specific to Firefox.
Also related to #645?

**Comment by LisaGee** [comment]
closing in favor of #877

**Comment by LisaGee** [comment]
Re-opening as this has clearer steps to Repro than #877

**Comment by LisaGee** [comment]
Closing again in favor of #947
