### ISSUE TITLE
As a developer, I'd like to see example APIs that are correct, so I can easily test the API

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#730]
I think this was one of the fields where the name changed
median earnings:
https://ccapi-staging.18f.gov/v1/schools?fields=school.name,id,2011.earnings.6_yrs_after_entry.median&sort=2011.earnings.6_yrs_after_entry.median:desc

**Comment by ultrasaurus** [comment]
fixed in the dictionary for the next big field update, but also just made the example use the same fields as the consumer tool, since those are the fields we want to most frequently test.  (this is done locally, but want to test a bit more before updating server)

**Comment by ultrasaurus** [comment]
fixed on dev

**Comment by ultrasaurus** [comment]
and now on staging

**Comment by ultrasaurus** [comment]
To test, click all the links and see if it looks like there is data there (was getting Internal Server Error for ones that included earnings): https://ccapi-staging.18f.gov

**Comment by ultrasaurus** [comment]
Four Year School with over 2000 students:
https://ccapi-staging.18f.gov/v1/schools?school.degrees_awarded.predominant=3&2013.student.size__range=2000..&fields=id,2013.student.admission_rate.overall,2013.completion.rate_suppressed.overall,school.name,2013.student.size&sort=2013.completion.rate_suppressed.overall:desc

generates this error:
```
{
"errors": [
  {
    "error": "field_not_found",
    "input": "2013.student.admission_rate.overall",
    "message": "The input field '2013.student.admission_rate.overall' (in the fields parameter) is not a field in this dataset."
   }
]
}
```

**Comment by ultrasaurus** [comment]
I believe in the pre-1.0 API scrub, this was moved from the `student` category to the `admissions` category

This is the correct query:

https://ccapi-production.18f.gov/v1/schools?school.degrees_awarded.predominant=3&2013.student.size__range=2000..&fields=id,2013.admissions.admission_rate.overall,2013.completion.rate_suppressed.overall,school.name,2013.student.size&sort=2013.completion.rate_suppressed.overall:desc

**Comment by yozlet** [comment]
This has now been pushed to staging, and the updated URLs are in the links on the front page of https://ccapi-staging.18f.gov/

**Comment by barkimedes** [comment]
I tried it out; looks like i'm getting results. So :us:
