### ISSUE TITLE
MVP for Data Tool

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#737]
1. Intro
2. Data Insights carousel
3. Download papers:
   a. Technical
   b. Policy
4. Download data sets:
   a. All data
   b. Scorecard data
   c. Most recent data
   d. What's new from NSLDS
   e. Post-school earnings
5. API Documentation
   a. Overview explaining Data Buckets and Key Take-aways (Download?)
   b. Data Dictionary Download
   c. 5 example queries

**Comment by LisaGee** [comment]
@diego- Could you take a crack at coming up with 5 good examples.
Maybe something along the lines of:
1. All Data for School 1
2. All Data for School 2
3. Interesting Completion Data for 4 year schools by race:  Fields: 
PCTPELL, 
C150_4, 
C150_4_WHITE
C150_4_BLACK
C150_4_HISP
C150_4_ASIAN
C150_4_AIAN
C150_4_NHPI
C150_4_2MOR
C150_4_NRA
C150_4_UNKN
C150_4_WHITENH
C150_4_BLACKNH

4. School Names, 2011 Median Earnings and 2011 Debt and 2011 Repayment, sorted Descending by 2011 Repayment:
md_earn_wne_p10
GRAD_DEBT_MDN
RPY_3YR_RT

5. Anything jump out at you?

**Comment by LisaGee** [comment]
@meiqimichelle Given the requirements, what do you think is the simplest, fastest and least risky :-) way to get to the MVP?

**Comment by LisaGee** [comment]
@ErieMeyer Got any thoughts on sample queries that you think would be useful for Developers?

**Comment by meiqimichelle** [comment]
Remaining:
- [ ] one remaining query sample
- [ ] pdfs for download (policy, tech, dictionary)
- [ ] full data download
- [ ] sample/subset csvs
- [ ] review 10 quotes in carousel, if we keep all of them need to make carousel taller. recommend choosing less than 10.

**Comment by meiqimichelle** [comment]
I moved the remaining tasks to #1015 and am moving the MVP to accept.

**Comment by meiqimichelle** [comment]
The data tool should be live on `staging` minus the downloads as listed above.

**Comment by jjoteal** [comment]
Closing this one, as remaining tasks are in #1015
