### ISSUE TITLE
Should we send developers to GitHub for any reason? Link on the site

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#747]
@ErieMeyer Do we want to make any reference to building in the open and welcoming developer contributions and here is a link to our GitHub repo in the Data Tool someplace?

**Comment by ErieMeyer** [comment]
Yes!

**Comment by ErieMeyer** [comment]
Michelle -- can you link up the GitHub link on the footer of Dev to github.com/18f/college-choice?

**Comment by meiqimichelle** [comment]
Should be live on `dev`

**Comment by ErieMeyer** [comment]
I believe I just tested this on staging and it was working super well!

https://federalist.18f.gov/preview/18F/college-choice/staging/data/
