### ISSUE TITLE
BUG: entering zip code and mile radius, zero results, then went back to change mile radius and find schools button doesn't work 

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#750]
This was at 2:21 pm on a Dell Desktop with Chrome.  Screen size was one column.  I entered just the zip code and put 20 mile radius.  Search yielded zero results. Hit back button, changed mile radius to 50 and clicked find schools.  No response from website.  Will not show any results. 

https://college-choice.18f.gov/search/?zip=22304&distance=50&online=1&sort=advantage:desc 

![capture](https://cloud.githubusercontent.com/assets/13317147/9553920/48073fb6-4d90-11e5-9752-1ee5c0ae4991.PNG)

**Comment by LisaGee** [comment]
This is due to #877 . Looking at the URL, I can see that you had Online Only schools checked. Probably accidentally.
