### ISSUE TITLE
93% of what quota?

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#752]
sent this over email (to college-choice email list), putting in github so we don't lose it.  

https://console.18f.gov

![image](https://cloud.githubusercontent.com/assets/41906/9556052/8d43e1f6-4d86-11e5-9c54-b19403eb6b77.png)

**Comment by ultrasaurus** [comment]
@ozzyjohnson @dlapiduz what is the quota in the upper-right?  do we need to raise it?

**Comment by ozzyjohnson** [comment]
That's the overall capacity limit for your project in Cloud Foundry. I
cranked it up.

**Comment by diego-** [comment]
Specifically RAM usage per CF team
    current_memory_usage / memory limit * 100
