### ISSUE TITLE
BUG: Hovering over info for "graduation rate" and "salary after 10 years" describes "average actual cost"

### ISSUE THREAD

**Issue by dmedfsa** [18F/college-choice#762]
Hovering over "info" for graduation rate does not provide information describing graduation rate calculation, but instead provides information about average actual cost.

![bug03](https://cloud.githubusercontent.com/assets/14021621/9556633/5c02240e-4da4-11e5-8871-d696c66bd30b.png)

**Comment by dmedfsa** [comment]
![bug04](https://cloud.githubusercontent.com/assets/14021621/9556766/48592b40-4da5-11e5-8ca0-039a684dc827.png)

**Comment by LisaGee** [comment]
Should be addressed by #420
