### ISSUE TITLE
BUG: ugly drop down 

### ISSUE THREAD

**Issue by lm27** [18F/college-choice#763]
![image](https://cloud.githubusercontent.com/assets/14021942/9556654/8490fc10-4da4-11e5-8473-ee9a8f4b2ccf.png)
 4:48 PM on Friday, tried to search for Pennsylvania and got an ugly drop down

**Comment by LisaGee** [comment]
@lm27 Could you add more context please? What Device, OS, Browser and exact steps to reproduce. How did you try to search - did you type P, did you click the down arrow? and what do you mean by "ugly" is it that there are 2 down arrows or something else? Thanks.

**Comment by barkimedes** [comment]
@lm27 I can't reproduce this; can you provide more information on how you got that to happen? Otherwise we'll have to close the issue as not reproducible. Thanks!

**Comment by lm27** [comment]
I don’t know

**Comment by barkimedes** [comment]
No problem. If it comes up again, hopefully someone will report it. Closing the issue. Thanks!
