### ISSUE TITLE
Information hover problems

### ISSUE THREAD

**Issue by mgunja** [18F/college-choice#764]
When you hover over info on the main page over "Graduation Rate" and "Salary 10 years after", it gives you the information for "Average Actual Cost."

Hovering over the info tab on "Typical Total Cost" and "Typical Monthly Loan Payment" and "Students Receiving Federal Aid" under the Financial Aid & Debt tab gives you the information for "Graduation Rate"

**Comment by LisaGee** [comment]
Should be addressed by #420
