### ISSUE TITLE
BUG-No US Virgin Islands search option

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#771]
Dropdown menu for location lists states, the District and US overseas territories but not the US Virgin Islands/
![img_3458](https://cloud.githubusercontent.com/assets/13874735/9556776/59e8df86-4da5-11e5-9fed-81bc929a5f04.PNG)

**Comment by LisaGee** [comment]
It is there, just alphabetically mixed in with the states. Listed as Virgin Islands, right after Virginia.

Should be taken care of by #863
