### ISSUE TITLE
BUG: program search feature doesn't work 

### ISSUE THREAD

**Issue by lm27** [18F/college-choice#780]
5:04 pm I tried to search for foreign language, literature and linguistics programs and the search yielded nothing. 

![image](https://cloud.githubusercontent.com/assets/14021942/9557043/cc4d6956-4da6-11e5-977b-ccbfba5d6d34.png)

**Comment by LisaGee** [comment]
@lm27 Can you please provide more information for this issue, namely: device, platform, browser & version #, and a URL is required.
When I do it, i get 1,113 results using this URL: https://college-choice.18f.gov/search/?major=language&sort=advantage:desc

**Comment by barkimedes** [comment]
@lm27 Is there any further information you can provide on this issue? Did you have any other search fields specified? If not, we'll close the issue as not reproducible. Thank you!

**Comment by lm27** [comment]
I don’t know

**Comment by barkimedes** [comment]
No problem. If it comes up again, hopefully someone will report it. Closing the issue. Thanks!
