### ISSUE TITLE
On SAT, 0 displayed in writing rather than N/a

### ISSUE THREAD

**Issue by jennbell** [18F/college-choice#782]
On SAT, 0 displayed in writing rather than N/a

**Comment by LisaGee** [comment]
@jennbell Can you provide more info for this ticket? At a minimum need the URL or School Name. I don't know where you are looking. Thanks.

**Comment by jennbell** [comment]
Hi there. It was Catholic university, SAT Writing. I took a screen shot but alas had trouble attaching from the iPad 😊. Thans!

Sent from my Windows Phone
________________________________

**Comment by barkimedes** [comment]
Shows "No Writing data available." now. Closing. @jennbell Feel free to reopen if you see the issue again.
