### ISSUE TITLE
BUG-No way to select criteria from dropdown menu in iPhone 5 (chrome)

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#786]
No way to select criteria from dropdown menu in iPhone 5 (chrome)

**Comment by LisaGee** [comment]
@claremccann can you provide some additional info: URL and screenshot and Steps To Repro if possible. Not sure to what you are referring.

**Comment by barkimedes** [comment]
@claremccann Do you have more info about what you were referring to? Do you know if this is still an issue or can we close it?

**Comment by claremccann** [comment]
No idea, sorry, I don't have an iPhone so think someone must have used my profile to post this.

**Comment by barkimedes** [comment]
I'll go ahead and close it then. If it is still an issue, someone will report it again.
