### ISSUE TITLE
BUG-"religious affiliation" dropdown screen does not populate in filter your results

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#790]
"regligious affiliation" dropdown screen does not populate in filter your results.  Shows "special designation" dropdown.

**Comment by LisaGee** [comment]
@claremccann can you provide more info? URL, Device, OS, Browser & version plus a screenshot would be helpful. Not sure I understand the ticket as it is written.

**Comment by barkimedes** [comment]
@claremccann Is this still an issue? I don't see either option under "Filter your results", but I do see both under "Edit search". Does this look right to you? If so, can we close this issue?

**Comment by claremccann** [comment]
No idea, sorry, I'm guessing someone else posted this from my profile.

**Comment by barkimedes** [comment]
I'll go ahead and close it. If this is still an issue, someone will report it again.
