### ISSUE TITLE
BUG: Student Body Race/Ethnicity should have definitions for acronym.

### ISSUE THREAD

**Issue by sharonleu** [18F/college-choice#808]
The definitions for race/ethnicity should have definitions for acronym.

<img width="352" alt="screen shot 2015-08-28 at 5 19 13 pm" src="https://cloud.githubusercontent.com/assets/14021544/9557317/11c1e848-4da9-11e5-91e8-05058c9e287a.png">

**Comment by LisaGee** [comment]
Edited to be non-duplicative of #485.

**Comment by hollyallen** [comment]
Race/Ethnicity is now displayed properly I believe. See https://collegescorecard.ed.gov/school/?166683-Massachusetts-Institute-of-Technology

@lisagee @barkimedes okay to resolve this?

**Comment by LisaGee** [comment]
Agreed. Closing
