### ISSUE TITLE
BUG: University of Chicago net price calculator

### ISSUE THREAD

**Issue by samquinney2** [18F/college-choice#813]
![image3](https://cloud.githubusercontent.com/assets/14021663/9557339/37a4da98-4da9-11e5-8c70-928fbcc3d197.PNG)

iphone5, safari, 5:21 pm issue: for "Calculate Your exact net price" for University of Chicago it takes you to a broken url

**Comment by LisaGee** [comment]
Error in data. Reporting to Clare to feed back to IPEDS.
