### ISSUE TITLE
BUG: Student body - missing % Pell

### ISSUE THREAD

**Issue by sharonleu** [18F/college-choice#815]
No information or graphic on percent pell.
(Univ of Maryland - College Park)

Macbook Pro Chrome
8/28/15 5:23
<img width="632" alt="screen shot 2015-08-28 at 5 22 19 pm" src="https://cloud.githubusercontent.com/assets/14021544/9557369/7a1c1efe-4da9-11e5-93a7-db507e45d4f7.png">

**Comment by LisaGee** [comment]
Should be fixed by #423
