### ISSUE TITLE
BUG: Style issue - "graduation rate" graph is a centimeter higher than parallel graph

### ISSUE THREAD

**Issue by dmedfsa** [18F/college-choice#817]
Under the "Graduation and Retention" screen, the "graduation rate" graph is a centimeter higher on the screen than the "students who return after their first year."  This is somewhat distracting.

![bug06](https://cloud.githubusercontent.com/assets/14021621/9557384/99cf9870-4da9-11e5-8686-f2b2bc412ae3.PNG)

**Comment by LisaGee** [comment]
Here's a URL where you can see it. https://college-choice.18f.gov/school/?173920-Minnesota-State-University-Mankato
To see it, you may have to reduce your browser width until "Students WhoReturn After Their First Year" breaks into 3 lines.

**Comment by LisaGee** [comment]
Simplest solution would be to change words to be a shorter description.

**Comment by ErieMeyer** [comment]
![image](https://cloud.githubusercontent.com/assets/1626026/9694882/a0b74e9a-532a-11e5-9bfa-f56bc28d985c.png)

Has been addressed!
