### ISSUE TITLE
BUG: SAT Scores Overlapping

### ISSUE THREAD

**Issue by Valer038** [18F/college-choice#820]
https://college-choice.18f.gov/school/?174066-University-of-Minnesota-Twin-Cities

Time: 5:23pm
Date: 8/28/15
System: Chrome (PC)

SAT Scores near the end of the spectrum overlap and make it difficult to read.

![image](https://cloud.githubusercontent.com/assets/14021610/9557400/b68f41d6-4da9-11e5-8c95-84dbd030e55f.png)

**Comment by LisaGee** [comment]
Overlap should be handled by #102
