### ISSUE TITLE
BUG: No national average line on U of Wisconsin Financial Aid and Debt 

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#822]
On a Mac, on safari, with screen size of one column.  When looking at information for the University of Wisconsin-Madison the financial aid and debt tab, students paying down their debt, there is no national average black line. 

https://college-choice.18f.gov/school/?240444-University-of-Wisconsin-Madison 

![screen shot 2015-08-28 at 5 22 00 pm](https://cloud.githubusercontent.com/assets/13317147/9557355/5df458cc-4da9-11e5-93b5-610d2fa6b52c.png)

**Comment by LisaGee** [comment]
Dupe of #466
