### ISSUE TITLE
Selectivity

### ISSUE THREAD

**Issue by sharonleu** [18F/college-choice#823]
In narrower view (still 3 columns), the numbers are squished and overlap.

Macbook Pro Chrome
8/28/15 5:26 PM

<img width="621" alt="screen shot 2015-08-28 at 5 25 11 pm" src="https://cloud.githubusercontent.com/assets/14021544/9557433/f2c6b616-4da9-11e5-8a46-889520050d5f.png">

**Comment by LisaGee** [comment]
Should be fixed by #102
