### ISSUE TITLE
Enhancement: iPad - make Filter results independently scrollable

### ISSUE THREAD

**Issue by vgvg** [18F/college-choice#825]
This would work well if the filter results was scrollable independent of the page, that way when clicking "Find Schools", the actual results are still in the viewport, and not way above the viewport.

Screenshot shows that the results are not in the viewport, so it looks like nothing was found

<img width="1017" alt="screenshot 2015-08-28 17 26 48" src="https://cloud.githubusercontent.com/assets/815256/9557448/123dfb94-4daa-11e5-8d51-b3b5db0bd46f.png">

Must scroll up the page to see the results:
<img width="1015" alt="screenshot 2015-08-28 17 26 54" src="https://cloud.githubusercontent.com/assets/815256/9557464/3843367e-4daa-11e5-98ae-d3ca754f88c5.png">

**Comment by LisaGee** [comment]
I like this idea, but need to evaluate risk for any change in this implementation about how it would work across all browsers.
