### ISSUE TITLE
BUG: Test scores percentiles not labelled

### ISSUE THREAD

**Issue by sharonleu** [18F/college-choice#828]
The percentiles for scores are missing.

Macbook Pro Chrome
8/28/15 5:28

**Comment by LisaGee** [comment]
@sharonleu - Hi Sharon, Can you specify what school you were looking at when you saw this issue? It would be great to include: URL of the page you were on, a screenshot Thanks.

**Comment by barkimedes** [comment]
@sharonleu There isn't enough information here to reproduce this bug, so I'm closing it. But if you are able to provide more information, then please feel free to reopen it. Thanks!
