### ISSUE TITLE
BUG: Not enough right margin on "Find Schools" button on iphone display

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#83]
![image](https://cloud.githubusercontent.com/assets/12192706/8528917/7b874212-23e4-11e5-96df-211f30a21ef6.png)

Should have the same margin as the left side.

**Comment by meiqimichelle** [comment]
@jjoteal This is the same issue as the one we're working through in #67 about button size on smaller screen sizes. What button width would you like? Right now that are all set to 280px wide.
