### ISSUE TITLE
Tooltip text wrong in some places

### ISSUE THREAD

**Issue by hollyallen** [18F/college-choice#830]
https://federalist.18f.gov/preview/18F/college-choice/staging/school/?122454-San-Francisco-Art-Institute

![screen shot 2015-08-28 at 2 31 28 pm](https://cloud.githubusercontent.com/assets/3476681/9557484/3404b772-4d91-11e5-8370-13e12acf9005.png)

**Comment by LisaGee** [comment]
Should be addressed by #420
