### ISSUE TITLE
BUG: Test scores ACT data missing

### ISSUE THREAD

**Issue by sharonleu** [18F/college-choice#831]
No scores provided for ACT, should be labelled data not available.
Univ MD College Park

Macbook Pro Chrome
8/28/15

<img width="621" alt="screen shot 2015-08-28 at 5 25 11 pm" src="https://cloud.githubusercontent.com/assets/14021544/9557480/52866e3e-4daa-11e5-82d2-1714bcc1ed8b.png">

**Comment by LisaGee** [comment]
Should be handled by #528
