### ISSUE TITLE
BUG: iPad - "Find Schools" button on filter pane extends past container

### ISSUE THREAD

**Issue by vgvg** [18F/college-choice#833]
When pane is open:
<img width="341" alt="screenshot 2015-08-28 17 29 16" src="https://cloud.githubusercontent.com/assets/815256/9557492/65c618aa-4daa-11e5-9f8f-ba4cd50175c7.png">

When closed, it still shows up on the left side of the page:
<img width="59" alt="screenshot 2015-08-28 17 30 15" src="https://cloud.githubusercontent.com/assets/815256/9557501/7a6952ea-4daa-11e5-819c-29f9abba8ecd.png">

**Comment by LisaGee** [comment]
Should be addressed by #898
