### ISSUE TITLE
BUG: Academics Most Popular Programs

### ISSUE THREAD

**Issue by sharonleu** [18F/college-choice#837]
Most popular programs does not have sentence: "These are the most popular programs at this school"

Macbook Pro Chrome
8/28/15

<img width="653" alt="screen shot 2015-08-28 at 5 33 56 pm" src="https://cloud.githubusercontent.com/assets/14021544/9557553/fce864c2-4daa-11e5-8bca-3b8965413625.png">

**Comment by LisaGee** [comment]
I think that's covered by the title: "Most Popular Programs".
