### ISSUE TITLE
BUG: Four-column search results are too skinny at some browser widths

### ISSUE THREAD

**Issue by dnesting** [18F/college-choice#841]
Chrome/MacOS

1. Have a wide browser window
2. Perform a search (e.g. https://college-choice.18f.gov/search/?sort=advantage:desc&page=171)
3. Gradually shrink the width of the window until the four columns start to get compressed

The text starts running together and graph tops start shifting down inconsistently before the layout flips to two columns.  This implies there are ranges of browser widths that are ugly.

![image](https://cloud.githubusercontent.com/assets/7342162/9557582/37312ae2-4dab-11e5-852d-82289737c36e.png)

**Comment by LisaGee** [comment]
maybe make the switch to 2 cards-width at an earlier break point?

**Comment by jjoteal** [comment]
This is looking good from a visual design perspective.

**Comment by ErieMeyer** [comment]
:us:
