### ISSUE TITLE
Text formatting issue - 

### ISSUE THREAD

**Issue by mgunja** [18F/college-choice#845]
The high numbers on student selectivity run into the top score.

![image](https://cloud.githubusercontent.com/assets/14021629/9557300/e6ead53a-4da8-11e5-9905-2c75b6525413.png)
![image](https://cloud.githubusercontent.com/assets/14021629/9557631/802ddfce-4dab-11e5-8f99-0bffe14a3958.png)

**Comment by LisaGee** [comment]
Should be addressed by #102
