### ISSUE TITLE
on iphone5 graphs are missing a key for what the line means and what its value is

### ISSUE THREAD

**Issue by rongoro** [18F/college-choice#848]
On the info page for a school the graphs hard to understand because the line isn't identified by a key or value.

![img_2230](https://cloud.githubusercontent.com/assets/58707/9557701/1b3dfecc-4dac-11e5-9d94-d3d336682e33.PNG)

**Comment by LisaGee** [comment]
This is actually true at the moment across all platforms. Should be addressed by #466
