### ISSUE TITLE
ENHANCEMENT: percent with earnings above high school average

### ISSUE THREAD

**Issue by samquinney2** [18F/college-choice#852]
![img_5](https://cloud.githubusercontent.com/assets/14021663/9557733/6d04a044-4dac-11e5-8dbb-84423ba34e97.PNG)

iphone 5, safari, 5:44 PM, issue: The percentage of students earning above a high school diploma should have a national average, right now it doesn't have a reference point to what is average.

**Comment by barkimedes** [comment]
@samquinney2 This doesn't sound like it was an iphone-specific issue, and the national average is displayed now in the chart. So I'm closing this issue as resolved. Please feel free to reopen if it turns out that it is not really closed. Thanks!
