### ISSUE TITLE
on OSX chrome when one of the info icons is "suburban" it overflows into the "Medium" icon

### ISSUE THREAD

**Issue by rongoro** [18F/college-choice#856]
https://college-choice.18f.gov/school/?113218-Cuyamaca-College

![screen shot 2015-08-28 at 5 48 29 pm](https://cloud.githubusercontent.com/assets/58707/9557854/6859fb60-4dad-11e5-87d9-6b2874df2963.png)

(for a good looking example you can look here:  https://college-choice.18f.gov/school/?166656-MCPHS-University)

**Comment by jjoteal** [comment]
This looks good from a visual design perspective!
