### ISSUE TITLE
BUG: Graduation & Rate / Students Who Return After Their First Year / above, at, or below average

### ISSUE THREAD

**Issue by schakj** [18F/college-choice#858]
Shows above average, but this should not be displayed, per policy decision.

**Comment by LisaGee** [comment]
@schakj Can you provide more info via email to me and Clare? Not sure I'm following. Thanks.

**Comment by schakj** [comment]
If you look at the bar chart that displays the percentage of students who return after their first year, it will show text that says something like "Above Average."   This should not be displayed.  I think the college I was looking at was Carleton College.

**Comment by barkimedes** [comment]
@LisaGee @schakj 'Tis true, we have "above average" and "below average" labels on the charts. Is this really not supposed to be there?

**Comment by barkimedes** [comment]
I think we're OK.
