### ISSUE TITLE
Issues / possible enhancements

### ISSUE THREAD

**Issue by imetzg** [18F/college-choice#860]
- The national average line for the percentage of students paying down their debt is missing
- Text for race/ethnicity terms needs to be finalized
- Percentage of students receiving Pell Grants is missing
- Numbers denoting range of test scores can overlap with min. and max. values

Possible enhancements:

- Add caveats to contextualize certain information. For example, the community college I searched had an average amount of student debt of around $10,000, which could be deeply off-putting to students interested in a junior college. Perhaps better clarify that most community college students don't need to take out any loans to cover the cost of attending a community college, and that the figure reflects the experience of the small percentage of people that do take on debt to attend.

- Since students care a lot about how far away a college is from home, perhaps it's worth it to make it even easier to sort colleges by this preference. Perhaps students could search by time it takes to drive or fly to the university from their zip code, in addition to or instead of miles.

- Why not use Google Maps for the tiles? Students could dive into these maps to find out how to travel to the university, what entertainment venues exist near the university, etc.

**Comment by LisaGee** [comment]
@imetzg Great suggestions. Have captured them in individual tickets for future consideration.: #905, #906, #907. All the bugs you reported already have open issues.

Closing this ticket.
