### ISSUE TITLE
ENHANCEMENT: When searching, include "online-only" as an option under states rather than a checkbox

### ISSUE THREAD

**Issue by dmedfsa** [18F/college-choice#864]
Currently, a student who is searching for a specific school or set of schools who clicks "online-only" will increase the number of his/her search results by all online-only schools.  This would likely be something someone would rarely want.  Instead, a student who specifically wants to see online-only schools would want to have that as a specific search option.

Also, if you search by location and check the "online-only" checkbox, it indicates online-only schools that are headquartered in that state.  Few, if any, students would want to restrict his/her search of online-only institutions by where the institution is headquartered.

Suggest including ALL online-only schools as a search field under "state" instead.

**Comment by barkimedes** [comment]
@LisaGee Is there an online only option somewhere? I've been clicking around tool and I can't find it anywhere. Was it removed?

**Comment by barkimedes** [comment]
@jjoteal Do you know if this is still a valid issue? I can't find the online-only option anywhere :disappointed:

**Comment by barkimedes** [comment]
Closing in favor of #1142.
