### ISSUE TITLE
Bug: On Test Scores-University of Wisconsin-Madison-SAT section-Text Overlap Error 

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#866]
On Mac on Safari on 1 Column Screen---> Under Wisconsin-Madison test scores, under Math, the text is overlapped and blurry. 

https://college-choice.18f.gov/school/?240444-University-of-Wisconsin-Madison

![screen shot 2015-08-28 at 5 57 25 pm](https://cloud.githubusercontent.com/assets/13317147/9557949/4bcd1710-4dae-11e5-9e3a-f8297ab03faf.png)

**Comment by LisaGee** [comment]
Overlap should be handled by #102
