### ISSUE TITLE
Bug: Wisconsin-Madison "i" shows incorrect information

### ISSUE THREAD

**Issue by NatalieEMoore** [18F/college-choice#868]
On safari--on mac--on one column screen.

Most popular programs, available area of study, test scores, and race/ethnicity all show the same information when hovering over "i" which is incorrect. 

image that shows: 
![screen shot 2015-08-28 at 6 12 13 pm](https://cloud.githubusercontent.com/assets/13317147/9558159/59475eb2-4db0-11e5-927d-a5794ebba437.png)

![screen shot 2015-08-28 at 6 10 15 pm](https://cloud.githubusercontent.com/assets/13317147/9558132/1a3d99c0-4db0-11e5-8f30-4b3f4084d2ad.png)

![screen shot 2015-08-28 at 6 09 59 pm](https://cloud.githubusercontent.com/assets/13317147/9558133/1a4819e0-4db0-11e5-9942-24305f797587.png)

https://college-choice.18f.gov/school/?240444-University-of-Wisconsin-Madison

**Comment by LisaGee** [comment]
Should be addressed by #420
