### ISSUE TITLE
BUG:  Spelling out acronyms for race/ethnicity options

### ISSUE THREAD

**Issue by sullivanse** [18F/college-choice#870]
I'm using IE 11.  Accessing this link at 6;13pm:  https://college-choice.18f.gov/school/?164988-Boston-University

It seems like "nhpi" and "aian" should be spelled out rather than listed as an acronym. Also, there are underscores in the two of the terms.

![image](https://cloud.githubusercontent.com/assets/9384522/9558193/b7dd1af2-4db0-11e5-85e7-3eb7e5dff688.png)

**Comment by LisaGee** [comment]
Handled by #808
