### ISSUE TITLE
BUG: "Choose a degree" lists only associate's and bachelor's degree as options

### ISSUE THREAD

**Issue by dmedfsa** [18F/college-choice#872]
The list of search options for types of degrees only provides options for bachelor's and associate's degrees.  There are a number of other types of lower-level credentials (certificates, diplomas, etc.) that students could be looking for, and these should be represented.

**Comment by LisaGee** [comment]
For discussion re: goals of tool.

**Comment by LisaGee** [comment]
This should be resolved as part of #951. We should also list "Certificate" as an option under the drop down.

**Comment by LisaGee** [comment]
This tool is actually specifically designed for schools that offer Associates and Bachelors. The target audience is students looking for those types of programs. Those should be the only 2 listed in the drop-down. The data for other schools is of course available via the API for anyone to make use of.
