### ISSUE TITLE
Bug: Layout issues on small on-column screens (like iPhone or desktop)

### ISSUE THREAD

**Issue by vgvg** [18F/college-choice#873]
Found by @NatalieEMoore!

When the filter pane is open, it creates scrollable space at the bottom of the page, and to the sides. It also covers the entire viewport (which in itself is ok), but clicking "Find Schools" doesn't hide the pane, so there's no signal to the user that the search went through.

**Comment by LisaGee** [comment]
@NatalieEMoore Can you add some steps to repro and screenshots here. I'm not sure I understand the issue. Thanks.

**Comment by NatalieEMoore** [comment]
@LisaGee I was on your mac so I can't do the screenshot.  @vgvg do you have a mac?

**Comment by barkimedes** [comment]
I don't think this is an issue anymore since they changed how the filter drop down thingy works. And I can't reproduce it on a very narrow window on my mac. @NatalieEMoore feel free to reopen if you can reproduce, but I don't think this is a problem anymore.
