### ISSUE TITLE
Bug: Data showing as 0% in label instead of N/A

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#878]
Yeshiva College of the Nations Capital shows as 0% grad rate when searching men's only schools, but bar graph shows as Data Not Available.

**Comment by LisaGee** [comment]
C150_4_POOLED_SUPP==PrivacySuppressed for this school.
Not Available should be displaying in Label as well as Graph.

**Comment by LisaGee** [comment]
Dupe of #903
