### ISSUE TITLE
BUG: Right side of search results cut off when expanding filters

### ISSUE THREAD

**Issue by dnesting** [18F/college-choice#883]
Chrome on MacOS

1. Browser width to four columns
2. Perform a search
3. Click the 'Filter and edit your search'

A drawer appears on the left to apply filters on the data, and the content on the right appears to get pushed off the right side of the screen, truncating things after the third column, including pagination and sorting.  Resizing the browser seems to shift things around a little bit but does not correct the problem.

![image](https://cloud.githubusercontent.com/assets/7342162/9559072/b7c818a4-4dbb-11e5-9a7d-3f1520d859a4.png)

**Comment by LisaGee** [comment]
Compare to other drawer UX?

**Comment by barkimedes** [comment]
This doesn't happen anymore now that filter and edit search are overlays. Closing as resolved.
