### ISSUE TITLE
Review every label and text entry

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#888]
Make sure everything is actually labeled correctly.

**Comment by LisaGee** [comment]
Perhaps use #684 suggestion: I think it reads better to replace the infinitive with a gerund.

**Comment by jjoteal** [comment]
FYI -- this is done. Error on dev right now, so I can't proof the changes yet...

![image](https://cloud.githubusercontent.com/assets/12192706/9609451/c3358670-50a1-11e5-9b3f-e6e1adaf2072.png)

Once that is up and running, I will proceed with proofing!

**Comment by jjoteal** [comment]
Moving to accept for @LisaGee review!

**Comment by ErieMeyer** [comment]
The vs. their from https://github.com/18F/college-choice/issues/694 still is an issue here

![screen shot 2015-09-03 at 12 29 21 am](https://cloud.githubusercontent.com/assets/1626026/9650585/436bbf62-51d3-11e5-9854-402463b1d82b.png)

Also -- content from https://github.com/18F/college-choice/issues/684 is not "making" -- but I also think that the sidebar is being replaced with "get the best deal" box

(all of this from dev)

**Comment by LisaGee** [comment]
Copy edits all made. @meiqimichelle to check for conflicts and merge.

**Comment by LisaGee** [comment]
Done!
