### ISSUE TITLE
Filter & Edit Enhancements

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#889]
1. Can we make the font size a bit bigger? This is good functionality and I feel like it's getting a little lost.
2. Can we make the text read "Filter and Modify Search"
3. Can the the text be clickable, as well as the hamburger nav?

![image](https://cloud.githubusercontent.com/assets/12847090/9560167/7d468e22-4dd4-11e5-9353-b68e2ea218f4.png)

**Comment by meiqimichelle** [comment]
This is related to #751

**Comment by meiqimichelle** [comment]
Closing in favor of #984
