### ISSUE TITLE
Desktop styles for  homepage

### ISSUE THREAD

**Issue by meiqimichelle** [18F/college-choice#89]

**Comment by meiqimichelle** [comment]
@jjoteal Feel free to do a design review on the desktop home styles. Now that we've established the 'issue all the design tweaks as bugs' process, you can have at this whenever you like.

Some notes:
- I have an issue already for the 'Paying for College' design update
- I asked Shawn about 'advanced search' -- I can't remember if we have an issue already for that. Maybe you remember?

**Comment by jjoteal** [comment]
@meiqimichelle to be clear, should I record all of my separate design issues as individual bugs? Let me know and I'll proceed accordingly.

Regarding your question about "Advanced Search," do you simply mean adding the additional search methods (i.e. Institution Type, Selectivity, Diversity, etc.)?

**Comment by meiqimichelle** [comment]
Correct on the individual design issues -- one per issue, and label as 'bug'. 

Regarding 'advanced search,' I mean everything under the 'once you click 'advanced search' stuff -- which I think is the additional search methods. Sarah suggested this morning that we pull the pieces of that part out into separate issues as well since each requires new API calls. (I was assuming it would be one issue for 'get the advanced search working' but sounds like that will get us into the same problem as we had with the homescreens -- too much in one issue).

**Comment by meiqimichelle** [comment]
@jjoteal Should we turn this issue into the 'Consumer tool desktop home MVP' issue that Lisa recommended? In that case, it should stay open until we're happy enough with the styles for an MVP and can pass it on for Lisa's review.

**Comment by jjoteal** [comment]
Closing in lieu of separate issues for these items.
