### ISSUE TITLE
Change order of elements for Search

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#896]
Based on usability testing feedback from Jess, users are just typing in the school name, since it's the first element and is expanded. This kind of defeats the purpose as we want students to look for options that fit their criteria, not just home immediately in on their one school that they have in their head.

I'd suggest this order:
1. Programs/Degree (expanded). Move Degree above Program
2. Location (2nd - collapsed)
3. Size (collapsed)
4. Name (collapsed)
5. Advanced Search (collapsed)

Sarah made a similar point that students know what degree they are seeking. It didn't come up in Usability Testing, but we also did not probe for that. 
@jjoteal Let's add that to our baseline question set.

It also makes it more likely that students will be comparing like schools with like, as referenced in #886 

And hopefully simple enough change to be able to go in before 1.0 Launch.

**Comment by LisaGee** [comment]
This was actually opened by LisaGee. Shared computer...

**Comment by meiqimichelle** [comment]
This looks like
<img width="722" alt="screen shot 2015-09-01 at 11 30 57 am" src="https://cloud.githubusercontent.com/assets/4827522/9612905/19245af2-509d-11e5-84be-27d2fb03d7b8.png">

Is this OK @jjoteal @LisaGee ? If yes, I will merge.

**Comment by LisaGee** [comment]
Looks great!

**Comment by ErieMeyer** [comment]
Looks great on dev!

**Comment by ErieMeyer** [comment]
LGTM on staging!
