### ISSUE TITLE
The Find Schools button tip seems to be visible when it shouldn't be.

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#898]
Steps to Repro:
1. Have your IE11 browser window, about 1056 pixels wide (see 4 columns of schools, but they're a little mushed).
2. Go to: https://college-choice.18f.gov/search/?name=Providence&sort=advantage:desc
3. Scroll down to bottom of the page.
4. See the tip of a green button peeking out.

Expected Results:
No green button at all, as I never clicked to expand the drawer.

![image](https://cloud.githubusercontent.com/assets/12847090/9564278/30358638-4e6f-11e5-981e-480a562b046c.png)

**Comment by LisaGee** [comment]
True in Chrome too.

Steps to repro:
https://college-choice.18f.gov/search/?name=Missouri&sort=advantage:desc
1. Scroll down to where the button would be if the drawer were expanded.
3. re-size your browser window horizontally and you will see if poking out more or less at various widths.

![image](https://cloud.githubusercontent.com/assets/12847090/9564301/2f23911c-4e70-11e5-9a28-bfb4c0504238.png)

**Comment by LisaGee** [comment]
See #833 for screenshot of how the button expands beyond the container even when open: "Find Schools" button on filter pane extends past container

**Comment by LisaGee** [comment]
per @meiqimichelle : This should be resolved with #1008.
Moving to accept.

**Comment by ErieMeyer** [comment]
Looks awesome -- cannot recreate.
