### ISSUE TITLE
As a consumer, I want to be able to find more info about earnings

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#912]
Hi!

For this earnings figure, I believe we need a lil' "more info"
![image](https://cloud.githubusercontent.com/assets/1626026/9569515/f8ba3758-4f3b-11e5-8fff-9a7caab35d7e.png)

Here it is without the icon:

![image](https://cloud.githubusercontent.com/assets/1626026/9569512/dbf27b3a-4f3b-11e5-8b1e-88480294550c.png)

**Comment by meiqimichelle** [comment]
To @ErieMeyer for review of #1063 and merge if OK.

**Comment by meiqimichelle** [comment]
Ready for review on `dev`

**Comment by ErieMeyer** [comment]
![image](https://cloud.githubusercontent.com/assets/1626026/9697613/07a81054-5361-11e5-842c-c63d6edb50b4.jpg)

**Comment by ErieMeyer** [comment]
The "I" appears to have different styling and unable to click on it from iPhone safari (dev)

**Comment by meiqimichelle** [comment]
This one changed -- we put a sub-head in this section and the info icon went there. Moving to accept to see if the new functionality resolves this problem or not.

**Comment by ErieMeyer** [comment]
Working on dev!

**Comment by LisaGee** [comment]
And on staging!
