### ISSUE TITLE
DESIGN Q: Should there be a circle around the % of students with Pell grants?

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#917]
![image](https://cloud.githubusercontent.com/assets/1626026/9553793/6775bdd8-4d8f-11e5-9d57-8980412dab8f.png)

In socieo-economic diversity

Brought over from this: https://github.com/18F/college-choice/issues/465

**Comment by jjoteal** [comment]
I say we cut it since we can't do the graph that shows the circle 35% 'filled' -- let's just have a number like the rest of the non-graph facts for consistency.

**Comment by ErieMeyer** [comment]
+1

**Comment by jjoteal** [comment]
Cool. Reassigning to @meiqimichelle then so she can remove it.

**Comment by LisaGee** [comment]
not a high priority given where we are at the moment.

**Comment by barkimedes** [comment]
Closing. There is no circle now. @jjoteal Feel free to reopen in case I missed something, but see no circle.
