### ISSUE TITLE
As a site operator, I would like to be able to see what's happening on elasticsearch

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#920]
There's an elasticsearch plugin called [marvel](https://www.elastic.co/products/marvel), that seems to have nice monitoring for a cluster

**Comment by ultrasaurus** [comment]
@ozzyjohnson is working on this

**Comment by ozzyjohnson** [comment]
This is ready to go. I can implement given a window to swap out backing Elasticsearch instances.

**Comment by hollyallen** [comment]
I believe this is complete, correct @ozzyjohnson ?

**Comment by ozzyjohnson** [comment]
This is ready, but only available when a new instance is created. 

Here's the 18 year indexer running this morning:

<img width="1107" alt="screen shot 2015-09-03 at 7 20 25 am" src="https://cloud.githubusercontent.com/assets/3709182/9657146/88d9ecde-520c-11e5-8baa-f0f4a066035c.png">

**Comment by hollyallen** [comment]
Great. Is that the new production elasticsearch?

**Comment by ultrasaurus** [comment]
started documenting this here:  https://github.com/18F/college-choice-data/blob/master/doc/LIVE.md

open issue:  https://github.com/18F/college-choice/issues/1099

I'd like to put URLs for all the environments in the doc before considering this complete

**Comment by ultrasaurus** [comment]
documented at the top of this doc:  https://github.com/18F/college-choice-data/blob/master/doc/LIVE.md
along with explanation of how to get credentials out of CF env using the make_proxy script

@ozzyjohnson is fixing up: https://ed-ex-eservice-proxy.18f.gov/_plugin/marvel/kibana -- all other links work for me

**Comment by ultrasaurus** [comment]
all the links work for me now

**Comment by ultrasaurus** [comment]
I think @yozlet should accept -- read the docs and make sure you can click on the links to marvel at the visibility we now have into Elasticsearch

cc @dnesting

**Comment by dnesting** [comment]
Ideally, we'd have visibility into ES in New Relic.  I think @ozzyjohnson was exploring this as a long-term thing but I don't know if that's being tracked here or if we should have a separate issue for it.  It's great that we have the proxy but it's more useful if we can aggregate metrics and graphs in one place.

**Comment by ozzyjohnson** [comment]
There's an NR release I'll be testing shortly for Docker reporting and a
broker update which should allow pushing keys into each container for the
possibility of more granular info.

I held off on these last week as they'd have been introduced pre-launch,
but post-load testing. Not worth it.

**Comment by yozlet** [comment]
All the Marvel links work for me, though I'm currently seeing that `indexing` doesn't have a running `eservice`:

```
Angelou:real-data yoz$ cf t -s indexing

API endpoint:   https://api.18f.gov (API version: 2.29.0)
User:           jeremy.grahame@gsa.gov
Org:            ed
Space:          indexing
Angelou:real-data yoz$ ./cf-service-proxy/make-proxy.sh -s eservice -up
  - Service not found: eservice
```

**Comment by ozzyjohnson** [comment]
Indexing has two eservices named eservice-a and eservice-b. They each have
a proxy.

**Comment by yozlet** [comment]
:+1:
