### ISSUE TITLE
BUG: Missing "i" icon and tooltip on Socio-Economic Diversity Label

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#924]
![image](https://cloud.githubusercontent.com/assets/12192706/9583348/d827f08c-4fd8-11e5-8ed0-9b2d088ba425.png)

Missing "i" and tooltip

**Comment by LisaGee** [comment]
Has a sentence describing it below, so low priority.

**Comment by jjoteal** [comment]
Marking as a DISPLAY issue (though i know it is a low priority). 

Tooltip text is associated with glossary.yaml term "socio-eco"

**Comment by ErieMeyer** [comment]
Looks good!

**Comment by ErieMeyer** [comment]
:us:
