### ISSUE TITLE
BUG: For MVP, remove circle around Socio-Economic Diversity data point

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#925]
![image](https://cloud.githubusercontent.com/assets/12192706/9583368/f1019fae-4fd8-11e5-8539-04522e297abc.png)

Remove the circle around "14%" for the MVP for consistency.

**Comment by jjoteal** [comment]
Also marking this is as a DISPLAY issue, as crossing fingers that we can address this for launch (i know it's not a priority though!

**Comment by ErieMeyer** [comment]
Looks great on dev!

**Comment by ErieMeyer** [comment]
:us:
