### ISSUE TITLE
BUG: Need a label + "i" icon + toolip above metric of "earning more than those with a high school diploma" for consistency sake

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#926]
Current screenshot:

![image](https://cloud.githubusercontent.com/assets/12192706/9583408/29cea3c2-4fd9-11e5-9a8a-f0f53802faf2.png)

Need label associated with metric for consistency and so we can attribute an "i" icon and tooltip with it.

@ErieMeyer perhaps you have good language suggestions after speaking with Dana?

**Comment by LisaGee** [comment]
Missing from a few other places on this page too and this one has a sentence to explain it, so low priority.

**Comment by LisaGee** [comment]
Similar to #924

**Comment by meiqimichelle** [comment]
More discussion in #1063.

**Comment by ErieMeyer** [comment]
Looks good on dev

**Comment by ErieMeyer** [comment]
:us:
