### ISSUE TITLE
Write additional content blurbs for the Data Tool Homepage

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#929]
1) Edit text under "Introduction to the Data"
2) Small blurb under "Download the Data"

**Comment by jjoteal** [comment]
Just an update that these are done. Just waiting for the Pull Request to merge...

**Comment by meiqimichelle** [comment]
Should be live on `dev` with #959 .

**Comment by meiqimichelle** [comment]
I also removed the second button in the downloads section, replaced with csv size, and removed the subpages from nav that we're not including in v1.

**Comment by jjoteal** [comment]
@meiqimichelle the little blurb I inserted for the Download the Data and Documentation sections are not displaying. Is there by chance a pull request that hasn't merged yet?

**Comment by meiqimichelle** [comment]
@jjoteal This is what I see on `dev`. Is it what you were expecting?
![screen shot 2015-09-02 at 7 00 36 am](https://cloud.githubusercontent.com/assets/4827522/9633217/80022f80-5140-11e5-8088-843d6cfb7239.png)

**Comment by jjoteal** [comment]
Yep, that is correct! Perhaps I have the wrong dev URL? I was clicking on the only one that was available for the Data site in college-choice-data...

**Comment by meiqimichelle** [comment]
It should just be the normal Federalist dev url plus `/data/` at the end. We'll get the new footers pushed live today with the link to /data so you won't have to go searching next time :)

**Comment by ErieMeyer** [comment]
Looks good to me!
