### ISSUE TITLE
As a student, I would like to enter "berk" in the Name field and see University of California-Berkeley as one of my results

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#934]

**Comment by LisaGee** [comment]
Seems to be a frequent use case. From a user:
-----Original Message-----
Very cool so far.

Testing the "Share This School" and search function.

1.  Using the "School name" search function, I typed in "Virginia" (and nothing else).  https://college-choice.18f.gov/search/?name=Virginia&sort=advantage:desc 

2.  It returned 15 results but not the University of Virginia (as I would have expected).  

RECOMMENDATION: Might I suggest that search includes search results for any word result versus first word result.  A similar search for Oregon results in no result finding for University of Oregon | https://college-choice.18f.gov/search/?name=Oregon&sort=advantage:desc

**Comment by ultrasaurus** [comment]
yeah, people keep running into that, need to do some experimentation to let you know

**Comment by cew821** [comment]
I had a very similar problem. "Phoenix" had no result, nor did "Phoenix University" or "university of phenix." 

It seems like the search feature should be using some kind of fuzzy text search so that it doesn't require exact matches (I assume this needs to be implemented in the API).

**Comment by cew821** [comment]
Looks like the "berk" case is working in staging. However, a few other cases are not working:

1. "phoenix university" should probably surface "university of phoenix"

2. "pheonix" (mis-spelling) should probably work

3. "phoenix college" should also probably return "university of phoenix" --- since college and university are often thought of as synonyms 

4. "phoenix online" should also probably work

**Comment by LisaGee** [comment]
Agree with all of Charles' options. Only 1. is required for 1.0 Launch, but all the others are also good things.

The other additional use case is
5. When I search for "berk" or "Berk", I should see "University of California at Berkeley", as well as "Berkeley College".

**Comment by ultrasaurus** [comment]
FYI "University of California at Berkeley" is actually "University of California-Berkeley" in our data set, so we need to make sure to tokenize based on - as well as space (currently using standard tokenizer which splits words based on these and other common english word-break characters)

**Comment by ultrasaurus** [comment]
I've addressed the top priority of this bug and a couple of the use cases from @cew821 

Here are the sample API calls:
0. "berk" finds "University of California-Berkeley" (and other results) https://ccapi-ex.18f.gov/v1/schools?school.name=berk&fields=school.name
1. "phoenix university" should find "university of phoenix" https://ccapi-ex.18f.gov/v1/schools?school.name=phoenix%20university&fields=school.name
4. "phoenix online" finds "University of Phoenix-Online Campus" https://ccapi-ex.18f.gov/v1/schools?school.name=phoenix%20online&fields=school.name

would be awesome if @LisaGee and @cew821 could test again!

**Comment by LisaGee** [comment]
Confirming also against data
0. "berk" in the excel shows 13 schools, as does the API call above. And I verified that they all match.
1. Search for "phoenix" gives same number in Excel and API. Search for "phoenix" and "university" gives same results in Excel and API.
4. API call and Excel for "phoenix" and "online" results in 2 schools. both.

Looking good!

**Comment by LisaGee** [comment]
Tested a few others for good measure, like "virginia", "Phoenix", "PHOENIX", "PHOEN". All good.

fyi "nix", results in 0, which seems fine.

Nice Sarah!

**Comment by ErieMeyer** [comment]
Looks great on staging!
