### ISSUE TITLE
As a consumer, I want a way to contact the team with complaints, feedback.

### ISSUE THREAD

**Issue by hollyallen** [18F/college-choice#937]
As a consumer I want a way to contact the team with complaints, bug reports, data problems, etc.

**Comment by hollyallen** [comment]
Related to #264 but for the webapp

**Comment by LisaGee** [comment]
Oooof. Doesn't look like ED has a good solve for this yet.
How about at a minimum, we put a Contact Us link in the Footer?
Links to the same place Contact Us on ED.gov site go: http://www2.ed.gov/about/contacts/gen/index.html

Not pretty, but it's something....

**Comment by ErieMeyer** [comment]
LGTM on dev!

**Comment by ErieMeyer** [comment]
Working on staging!
