### ISSUE TITLE
BUG: Font too large for details under school name on Individual School page

### ISSUE THREAD

**Issue by jjoteal** [18F/college-choice#941]
Current display:

![image](https://cloud.githubusercontent.com/assets/12192706/9588178/bfbc93f6-4ff4-11e5-8f3a-7a2f92fac677.png)

Per original design files, the name of the school should be ~42px bold and the location, student population, and URL should be ~24px. If that font is too large per the new grid, then we should scale the type size down proportionately.

Screenshot of original design:

![image](https://cloud.githubusercontent.com/assets/12192706/9588237/2268d1fe-4ff5-11e5-8dda-9997a8fed2f3.png)

**Comment by meiqimichelle** [comment]
Should be live on dev with #966

**Comment by ErieMeyer** [comment]
Looks great on dev!

**Comment by ErieMeyer** [comment]
All set on staging!
