### ISSUE TITLE
Play By Play Launch List

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#946]

**Comment by diego-** [comment]
I think @hollyallen has a checklist to this effect?

**Comment by hollyallen** [comment]
I have been updating the "Engineering" sheet on the "TODOs to get us to Beta & to Launch" sheet in PICC on Google Docs. https://docs.google.com/spreadsheets/d/1BtjN7NSWeseA0C_IHwhnFV2-Y2pdwB6SmFkZd5_o0Ss/edit#gid=1199751241

I wouldn't call it a Play by Play list. Diego, I see a new doc called Deployment Plan, was that to be a play by play launch day list? 

In any case, we should make one that isn't the "TODOs" spreadsheet and I can take point on taht if desired.

**Comment by hollyallen** [comment]
I created a new sheet called "Beta Launch Play by Play" within the "TODOs to get us to Beta & to Launch" sheet in PICC on Google Docs. https://docs.google.com/spreadsheets/d/1BtjN7NSWeseA0C_IHwhnFV2-Y2pdwB6SmFkZd5_o0Ss/edit

I'm putting in there all the nitty gritty of what will happen when by who. Please help me make it correct.

@ozzyjohnson @ultrasaurus

**Comment by diego-** [comment]
holly is driving!
