### ISSUE TITLE
Enable a query to be constructed by passing in multiple institutions

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#948]
if we want to select specific schools, I think a query like this would be good; https://ccapi-staging.18f.gov/v1/schools?id=372213,104151

**Comment by LisaGee** [comment]
Would very much help #314

**Comment by ErieMeyer** [comment]
Tried to construct a URL, but not sure that I did it right: 

https://federalist.18f.gov/preview/18F/college-choice/staging/schools?id=166656,229337,197027

Should = United-States-Merchant-Marine-Academy, Texas-Tech-University-Health-Sciences-Center, MCPHS-University

![screen shot 2015-09-05 at 11 10 13 am](https://cloud.githubusercontent.com/assets/1626026/9699874/b4f8f982-53be-11e5-9305-4f10188e3e63.png)

**Comment by ultrasaurus** [comment]
https://ccapi-staging.18f.gov/v1/schools?id=166656,229337,197027

**Comment by ultrasaurus** [comment]
https://ccapi-staging.18f.gov/v1/schools?id=166656,229337,197027&fields=school.name,id

**Comment by hollyallen** [comment]
Looks good to me.
