### ISSUE TITLE
When I search by Bachelors Degree (and no other criteria), the results should be any school where CIPxxBACHL > 0 

### ISSUE THREAD

**Issue by LisaGee** [18F/college-choice#953]
I believe today we are returning any schools where PREDDEG==3

**Comment by LisaGee** [comment]
@ultrasaurus @shawnbot How risky are these changes?

**Comment by LisaGee** [comment]
We decided too risky for launch.

**Comment by hollyallen** [comment]
I think in this case we will need the bachelordeg==1 field that @claremccann is having added. See #951.

**Comment by abisker** [comment]
Other items to complete before this issue can be resolved:
- [ ] Frontend query updates
- [ ] Testing (#951 tests should cover)

**Comment by barkimedes** [comment]
:us: Yay! Also, tested on my mac/chrome. This has also been tested by many folks on many devices
