### ISSUE TITLE
Get icons for school page

### ISSUE THREAD

**Issue by meiqimichelle** [18F/college-choice#96]
We need to acquire the icons on the individual school pages:
![4eb5b16a-2556-11e5-85c9-fffffae3470a](https://cloud.githubusercontent.com/assets/4827522/8599675/c01a57b4-2616-11e5-9d7a-c60a3bdd9a8a.png)

@jjoteal Where are these from? Also, I think the one on the right is suuuuper similar to an old 'groups' icon from Facebook (interesting Medium article on this [here](https://medium.com/@caitlinwinner/how-we-changed-the-facebook-friends-icon-dc8526ea9ea8) ). I recommend using a different one so that we're not unintentionally brand-linking to FB (or, use something closer to their newer version).

This is in response to a task in #44.

**Comment by LisaGee** [comment]
Love the article!

**Comment by jjoteal** [comment]
@meiqimichelle these are from The Noun Project (except for the "4", which is just a font). Happy to find an alternative for "small." I'll also find icons for the other states (private; rural, suburban; large). Stay tuned!

**Comment by jjoteal** [comment]
Here are the icons for the school page. They are all from The Noun Project, though I tweaked a couple to be a bit more clear. @LisaGee let us know if you approve of these choices and then we can purchase and I can generate SVGs for the custom ones.

![image](https://cloud.githubusercontent.com/assets/12192706/8640117/0a26c4fe-28bb-11e5-98dd-66388dca78da.png)

**Comment by meiqimichelle** [comment]
@LisaGee Are these OK to purchase? This issue is blocking #44 (the issue on completing the intro section of the individual school pages).

**Comment by LisaGee** [comment]
Approved.

Although 2 things:

1.       We should get the icons for a less than 2 year school as well, b/c eventually we may be including Certificate programs as well.

2.       Public vs. Private iconography makes me laugh, but also a little uncomfortable.  Is Private a plantation homestead??

3.       Also, we’ll need a Private For Profit icon.

**Comment by meiqimichelle** [comment]
@jjoteal Can you send me the links to the noun project files when you're ready? I'll purchase through 18F.

**Comment by jjoteal** [comment]
@LisaGee take a look at these revised options:

![image](https://cloud.githubusercontent.com/assets/12192706/8753573/ccf898c2-2c8a-11e5-9f49-23148faebe19.png)


1) Certificate icon ok?
2) There are a few options for Private -- any of these work for you?
3) Private for Profit icon ok?

**Comment by jjoteal** [comment]
@meiqimichelle here are links to the approved icons so far:

1) Urban = https://thenounproject.com/search/?q=urban&i=1566
2) Suburban = https://thenounproject.com/search/?q=house&i=5270 and https://thenounproject.com/search/?q=trees&i=145351 (please note that I'll need to do some illustrator work here to put these 2 icons together. Accordingly, please download the SVG version and pass along)
3) https://thenounproject.com/search/?q=rural&i=29770
4) Small, Medium, Large = https://thenounproject.com/search/?q=crowd&i=38516 (please use the raw file for the Large icon. I will need to modify for the Small and Medium icons, so please download the SVG version and pass along)

Please note that the 2- and 4- year icons are just a font (48px bold).

Text associated with the icons is 16px bold.

**Comment by LisaGee** [comment]
I think Certificate is fine for the time being. And we’ll let the ED folks weigh in. It may end up needing to just be <2, but we’ll cross that bridge….

I think we’re going to have a hard time with iconography for Public vs Private vs For Profit (the $ made me laugh tho!). I think the important thing is that we don’t want Public to look accessible to everyone and Private to look exclusive.  We almost want to make sure that students don’t care if a school is public or private. We kind of only care if a school is not for profit or for-profit. I wonder if the only difference between Private and Public is that one has in-state tuition option? Maybe we do it that way:

1.       Not for profit vs for profit

2.       Checkmark for has in-state tuition option

What do y’all think?

**Comment by meiqimichelle** [comment]
@jjoteal I've put in the purchase request for the icons you provided links for. They will be here soon!

Any progress on the public/private iconography? @LisaGee , I like your thought on highlighting non-profit versus for-profit instead of public/private, and then highlighting an in-state tuition option.

**Comment by LisaGee** [comment]
I did a bit more looking at definitions on the web and I’m pretty comfortable going not-for-profit, for-profit and in-state/in-district tuition. Let’s do it!

Thanks,

--Lsia

**Comment by jjoteal** [comment]
Ok cool. So I'm understanding correctly, we are:

1) Killing the public, private, and private for profit icons completely
2) Replacing them with not-for-profit and for-profit icons
3) Adding an in-state/in-district tuition indicator that could be used in conjunction with either not-for-profit and for-profit

@LisaGee Can you confirm that I've outlined that correctly?

**Comment by LisaGee** [comment]
Yes please!

And you are technically correct in theory, however in practice in-state/in-district tuition is only for Public schools, which are by definition not-for-profit… But overall, yes.

**Comment by ErieMeyer** [comment]
Love this idea

**Comment by meiqimichelle** [comment]
@jjoteal The icons in [this comment](https://github.com/18F/college-choice/issues/96#issuecomment-122356985) have been purchased. I put them in PICC > Design > Assets. Back to you for editing the ones you need to :)

**Comment by LisaGee** [comment]
Since Jess is on vacation for the week, can you pop them in without edits and we’ll swap them out after Jess returns? Thanks.

**Comment by jjoteal** [comment]
FYI @meiqimichelle I modified the purchased SVGs and created icons for:
- Suburban
- Medium
- Small

You can find the .svgs named accordingly on Google Drive > PICC > Designs > Consumer Tool > Assets

**Comment by jjoteal** [comment]
@meiqimichelle you can find the approved Certificate icon for purchase here:
https://thenounproject.com/search/?q=certificate&i=10265

**Comment by jjoteal** [comment]
@LisaGee thoughts on these Not-for-Profit and For-Profit icons?

![image](https://cloud.githubusercontent.com/assets/12192706/8879163/44384eea-31f5-11e5-9fd2-2987059d2e62.png)

I know we were trying to avoid $ signs... thoughts on the price tag? Still too blatant?

**Comment by saintsoup52** [comment]
Sorry if I am late to this party... but as Lisa said... "In-State Tuition" and "Out of State Tuition" tags are only for public schools which are different then not-for profit or for-profit.

I think it would be great to have three different icons for each of the the types of schools... I have seen plenty of studies showing many students at for profit schools did not know they were attending a for profit school. The more we can help make it easier to distinguish one from the other, the better students will be.

**Comment by jjoteal** [comment]
@saintsoup52 Lisa said "in-state/in-district tuition is only for Public schools, which are by definition not-for-profit" so I was assuming Public schools are equal to Not for Profit. Hence, just the 2 icons: Not-for-Profit and For-Profit. @LisaGee have I misunderstood?

**Comment by saintsoup52** [comment]
Thank you for asking... There are three types of schools:
Public
Private, non-profit (usually called "Private")
Private, for-profit (usually called "For Profit")

We would want a different icon for each of them.

**Comment by jjoteal** [comment]
@LisaGee can you confirm this? Per above, it seemed like the confirmed instructions were:

1) Killing the public, private, and private for profit icons completely
2) Replacing them with not-for-profit and for-profit icons
3) Adding an in-state/in-district tuition indicator that could be used in conjunction with either not-for-profit and for-profit

Is that not the case? Is it what @saintsoup52 is asking for instead?

**Comment by jjoteal** [comment]
@LisaGee assigning this one to you so we can clarification on the above comments. Per the conversation between @saintsoup52 and I, could you tell us what school type icons are needed? Is it:

A) Not-for-Profit and For-Profit (with an In-State Tuition indicator)

or 

B) Public, Private Non-Profit, Private For-Profit

?

**Comment by LisaGee** [comment]
Let's do the thing I originally specified. If we have to come back and revisit, we can (and we may have to, but I'd like to make the argument for doing it the way I suggested). adn for the for-profit school icon, I actually do like the homestead with the $ -- I think that paints the picture quite nicely. I was concerned when it was being used to describe Private, but I think it actually works really well for For Profit. Thanks!

**Comment by saintsoup52** [comment]
This is definitely not a blocker for going into testing… But there is a BIG difference between private (non-profit) and public schools.

A public school is run by the state / local government and usually costs 1/3rd as much as private school run by a non-profit entity.

The differences between public and private (non-profit) is one of the most important differentiations that this college choice tool can makes

Additionally…

Ø  private (non-profits) do not charge “in-state” tuition, only public schools charge in-state tuition

Ø  no one calls a private school a “non-profit” (it is just called private)

**Comment by jjoteal** [comment]
@meiqimichelle here are the links to the remaining icons for purchasing:

https://thenounproject.com/search/?q=government%20building&i=143674

https://thenounproject.com/search/?q=price+tag&i=78865

Please download and post to the PICC folder on Google Drive when purchased, as I will have to edit them before we implement. Thanks!

**Comment by meiqimichelle** [comment]
@jjoteal Thanks! I've put in the request for purchase and will keep you updated.

**Comment by meiqimichelle** [comment]
Sigh. I just sent @LisaGee an email for approval. That is still required in our new purchase process and I didn't know that. Once I forward that to the right place, they'll go ahead and buy.

**Comment by meiqimichelle** [comment]
The icons should be in our shared assets folder @jjoteal :D

**Comment by jjoteal** [comment]
Thanks, Michelle! Per Lisa's most recent comment, it sounds like we are going with the homestead with the $ for For-Profit, so I'll just work from the Not-for-Profit icon and add a $ sign. Feel free to use the Not-for-Profit as-is in implementation (https://thenounproject.com/search/?q=government%20building&i=143674) and then I'll have the For-Profit icon your way this afternoon.

**Comment by jjoteal** [comment]
@meiqimichelle  For-Profit icon is now in PICC in the shared assets folder. File name is for-profit.svg

**Comment by LisaGee** [comment]
I think the purchaser needs to confirm that these icons were appropriately acquired and they can accept the story. I think that's @meiqimichelle

**Comment by meiqimichelle** [comment]
This task is complete. We have the icons.
