### ISSUE TITLE
Feature: As a researcher, I want to know where/how to ask and answer questions about this data

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#960]
I propose making the tag "collegescorecard" to keep branding consistent.

Then, we should link this to the "stack exchange" icon on the data tool. http://opendata.stackexchange.com/questions/tagged/collegescorecard

**Comment by meiqimichelle** [comment]
Should be live on `dev`. I have it set to open in a new tab. Let me know if that's not right.

**Comment by LisaGee** [comment]
Moved this to accept based on @meiqimichelle comments. Feel free to bump back, if not.

**Comment by ErieMeyer** [comment]
Done!
