### ISSUE TITLE
Layering bug with Under Investigation tooltip

### ISSUE THREAD

**Issue by hollyallen** [18F/college-choice#971]
https://federalist.18f.gov/preview/18F/college-choice/dev/search/?name=Community%20Christian%20College&sort=advantage:desc
Chrome

I was testing the fix to #943 (HCM2 flag) and sadly found this overlapping problem in the dev environment: 

![screen shot 2015-09-01 at 4 35 14 pm](https://cloud.githubusercontent.com/assets/3476681/9619663/383a3298-50c7-11e5-9601-8da4ef8acc34.png)

**Comment by hollyallen** [comment]
This is still happening on dev today: https://federalist.18f.gov/preview/18F/college-choice/dev/search/?name=Ultrasound%20Medical%20Institute&sort=advantage:desc

**Comment by LisaGee** [comment]
Another option would be to shorten the text.
@meiqimichelle if it's an easy code fix, that's great, else we'll edit the text down.

**Comment by meiqimichelle** [comment]
@shawnbot -- I wasn't able to find a solution to this in css, perhaps this is a JS deal? Or I'm just missing the proper place to override a rouge `z-index` :P

**Comment by meiqimichelle** [comment]
Looks like
![screenshot 2015-09-08 14 26 06](https://cloud.githubusercontent.com/assets/4827522/9747979/31c9f9e2-5636-11e5-8fb7-b56563dabda2.png)

Ready for review on dev

**Comment by ErieMeyer** [comment]
Looks good on dev!

**Comment by ErieMeyer** [comment]
Looks great on staging!
