### ISSUE TITLE
Bug -- MSI labels may be mutually exclusive

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#977]
New Mexico State University-Grants shows up as HSI, which is good. But it's also NASNTI, yet that label doesn't show up.

**Comment by claremccann** [comment]
Or maybe just all NANTIs don't show up?

**Comment by LisaGee** [comment]
There was a separate bug for NANTIs that has been fixed, but not pushed to prod yet.
Spelman is an example where you see 2 different designations working.
