### ISSUE TITLE
As a developer, I want to be able to use the API and figure out what are the best and worst schools in terms of debt

### ISSUE THREAD

**Issue by ultrasaurus** [18F/college-choice#98]

**Comment by ultrasaurus** [comment]
@ErieMeyer @LisaGee what column would I look at for this?

**Comment by ErieMeyer** [comment]
hi

**Comment by LisaGee** [comment]
DEBT_MDN is column name. Represents the Media Debt for all students as they enter repayment.

**Comment by LisaGee** [comment]
I bet this is done. @diego-  - Can you confirm and if so, close? Thanks.

**Comment by diego-** [comment]
Not working in dev or staging. Testing with following query: https://ccapi-staging.18f.gov/school?id=135717&fields=2013.median_debt.completers.overall

returns internal server error message.

**Comment by ultrasaurus** [comment]
@diego- I think you meant:  https://ccapi-staging.18f.gov/school?id=135717&fields=2013.aid.median_debt.completers.overall
