### ISSUE TITLE
BUG: U.S. Department of Education footer is not located at the foot of the webpage

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#981]
Edge browser, Windows 10

https://college-choice.18f.gov/search/?zip=20009&sort=advantage:desc
When I click the "Filter Results" link on the left and scroll down, I see that the sidebar extends far below the "U.S. Department of Education" footer.

The footer should always be at the true foot of the webpage.

![image](https://cloud.githubusercontent.com/assets/8903924/9629238/294bde44-513f-11e5-8221-3e202537a133.png)

**Comment by meiqimichelle** [comment]
This was resolved in passing with #1058 and changing the drawer to dropdowns (that part to-be-merged).

**Comment by ErieMeyer** [comment]
:us:
