### ISSUE TITLE
BUG: Advanced Search distinction seems arbitrary; consider removing the distinction?

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#982]
When I look at all the different criteria I could be searching and filtering by in the "Normal" search, it's not obvious to me why the criteria in "Advanced Search" are pulled out separately. The line between the two categories seems arbitrary, and I would just as soon have them all on one layout.

![image](https://cloud.githubusercontent.com/assets/8903924/9629421/6d5036d4-5140-11e5-9515-b76d510d0000.png)

**Comment by meiqimichelle** [comment]
We removed the advanced search distinction as per #890 .
