### ISSUE TITLE
BUG: Accessing Institution Type fields on sidebar requires multiple clicks

### ISSUE THREAD

**Issue by kimballce** [18F/college-choice#983]
Institution Type fields are grouped under "Advanced Search", but currently Institution Type is the only category under Advanced Search.

This means I have to click the "Advanced Search +" link, and then the expansion button by Institution Type before I can start searching.

Recommendation: have Institution Type category automatically expand when clicking "Advanced Search +". (or: do away with Advanced Search)

**Comment by meiqimichelle** [comment]
We removed Advanced Search for now since we don't have a whole ton under there yet. That content is now its own normal search area called Type, as per #890.
