### ISSUE TITLE
Bug: Search results not pulling up all schools

### ISSUE THREAD

**Issue by claremccann** [18F/college-choice#986]
Windows, google Chrome

Tried to search "Purdue" and got three Purdue campuses (Main, North Central, and Calumet). However, it's not pulling up Indiana University-Purdue University-Indianapolis and Indiana University-Purdue University-Fort Wayne. So seems like it's only pulling up results that start with the word searched, which is great for "universities of" but less great for this case.

**Comment by claremccann** [comment]
Similarly, can't pull up any University of Texas schools. I think there may be issues with searching for "University of" schools.

**Comment by LisaGee** [comment]
Dupe of #934
