### ISSUE TITLE
ENHANCEMENT: Add "Notices" link in footers

### ISSUE THREAD

**Issue by ErieMeyer** [18F/college-choice#996]
Investigating additional links for footer -- these are the ones that the new DOI site has in the footer.

For my research:

https://www.doi.gov/privacy
https://www.doi.gov/disclaimer
https://www.doi.gov/accessibility
https://www.doi.gov/notices

**Comment by ErieMeyer** [comment]
Ok! Looks like by linking "Notices" only, we're covered.

Notices link is here: http://www2.ed.gov/notices/index.html?src=ft

**Comment by meiqimichelle** [comment]
@jjoteal Thoughts on where to put this one?

**Comment by jjoteal** [comment]
I would add it next to Contact Us. So you would do something like:

Contact Us   |   Notices


Note the vertical pipe.

**Comment by meiqimichelle** [comment]
Nice, muy bueno. On it!

**Comment by meiqimichelle** [comment]
@ErieMeyer for your review in #1065. Merge if OK.

**Comment by meiqimichelle** [comment]
Ready for review on `dev`

**Comment by ErieMeyer** [comment]
Great job on dev

**Comment by ErieMeyer** [comment]
:us:
